objects/ADL_Survey__c.object
<CustomObject>
    <description>Created for Marketing Cloud.</description>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>ADLs</relationshipLabel>
        <relationshipName>ADL_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ADL</label>
    <nameField>
        <displayFormat>ADL-{0000000000}</displayFormat>
        <label>ADL Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ADLs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Cancer__c.object
<CustomObject>
    <description>Created for Marketing Cloud Survey.</description>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>ONCs</relationshipLabel>
        <relationshipName>Cancers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ONC</label>
    <nameField>
        <displayFormat>ONC-{0000000000}</displayFormat>
        <label>ONC Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ONCs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ADL__c</fullName>
        <label>ADL</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DIET__c</fullName>
        <label>DIET</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HEALTH_MEDICAL__c</fullName>
        <label>HEALTH MEDICAL</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SES__c</fullName>
        <label>SES</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SUBJECTIVE_ENGLISH__c</fullName>
        <label>SUBJECTIVE ENGLISH</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WOMENS_HEALTH__c</fullName>
        <label>WOMENS HEALTH</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>isProject2_Participant__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isProject2 Participant</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Diet__c.object
<CustomObject>
    <description>Created for Marketing cloud Survey</description>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>DIETs</relationshipLabel>
        <relationshipName>Diets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DIET</label>
    <nameField>
        <displayFormat>DIET-{0000000000}</displayFormat>
        <label>DIET Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DIETs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/HealthMedical_Survey__c.object
<CustomObject>
    <description>created for Marketing cloud survey</description>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>HMs</relationshipLabel>
        <relationshipName>HealthMedical_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>HM</label>
    <nameField>
        <displayFormat>HM-{0000000000}</displayFormat>
        <label>HM Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/QPAR__c.object
<CustomObject>
    <description>cREATED FOR MARKETING CLOUD</description>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>QPARs</relationshipLabel>
        <relationshipName>QPARs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>QPAR</label>
    <nameField>
        <displayFormat>QPAR-{0000000000}</displayFormat>
        <label>QPAR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QPARs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SES__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>SESs</relationshipLabel>
        <relationshipName>SESs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SES</label>
    <nameField>
        <displayFormat>SES-{0000000000}</displayFormat>
        <label>SES Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SESs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Social_Stressor_Survey__c.object
<CustomObject>
    <description>Created for Marketing Cloud Survey</description>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>SOCSTRESSs</relationshipLabel>
        <relationshipName>Social_Stressor_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SOCSTRESS</label>
    <nameField>
        <displayFormat>SOCSTRESS-{0000000000}</displayFormat>
        <label>SOCSTRESS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOCSTRESSs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Social_Support_Survey__c.object
<CustomObject>
    <description>Created for Marketing Cloud Survey</description>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>SOCSUPPs</relationshipLabel>
        <relationshipName>Social_Support_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SOCSUPP</label>
    <nameField>
        <displayFormat>SOCSUPP-{0000000000}</displayFormat>
        <label>SOCSUPP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOCSUPPs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Subjective_English_Survey__c.object
<CustomObject>
    <description>Created for Marketing Cloud Survey.</description>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>SUBENGs</relationshipLabel>
        <relationshipName>Subjective_English_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SUBENG</label>
    <nameField>
        <displayFormat>SUBENG-{0000000000}</displayFormat>
        <label>SUBENG Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SUBENGs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Swls_Survey__c.object
<CustomObject>
    <description>for marketing cloud</description>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>SWLSs</relationshipLabel>
        <relationshipName>Swls_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SWLS</label>
    <nameField>
        <displayFormat>SWLS-{0000000000}</displayFormat>
        <label>SWLS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SWLSs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Womens_Health__c.object
<CustomObject>
    <description>survey for marketing cloud</description>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>WOMs</relationshipLabel>
        <relationshipName>Womens_Healths</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WOM</label>
    <nameField>
        <displayFormat>WOM-{0000000000}</displayFormat>
        <label>WOM Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WOMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BatchSurveyStatusUpdateTemp.cls
/*
@author            : Santhosh Nookilla
@description       : Schedulable Batch Class for Unlocking Surveys
@test class        : BatchSurveyStatusUpdateTempTest
*/

global class BatchSurveyStatusUpdateTemp implements Database.Batchable<SObject>, Schedulable {

    public String objectName;
    public String fieldName;
    public String conFieldName;

    global BatchSurveyStatusUpdateTemp(String objectName, String fieldName, String conFieldName) {
        this.objectName = objectName;
        this.fieldName = fieldName;
        this.conFieldName = conFieldName;
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Id, ' + fieldName + ' FROM ' + objectName + ' WHERE CreatedDate <= N_DAYS_AGO:365 AND CreatedDate >= N_DAYS_AGO:389';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext bc, List<SObject> scope) {
        Set<Id> recordIds = new Set<Id>();

        for (SObject obj : scope) {
            recordIds.add((Id)obj.get(fieldName));
        }              

        String dynamicQuery = 'SELECT Id, ' + conFieldName + ' FROM Contact WHERE Id IN :recordIds AND isProject2_Participant__c != true';
        List<Contact> contactsToUpdate = Database.query(dynamicQuery); 
        
        for (SObject obj : scope) {
            for (Contact contact : contactsToUpdate) {
                if (contact.Id.equals(obj.get(fieldName)) && contact.get(conFieldName) == 'Opened') {
                    contact.put(conFieldName, 'Completed');
                }
            }
        }

        if (!contactsToUpdate.isEmpty()) {
            update contactsToUpdate;
        }
        
        System.debug('No of Surey Records: '+recordIds.size());
        System.debug('No of contactsToUpdate: '+contactsToUpdate.size());
    }

    global void finish(Database.BatchableContext context) {
    }

    global void execute(SchedulableContext sc) {
        
        BatchSurveyStatusUpdateTemp surveyHM = new BatchSurveyStatusUpdateTemp('HealthMedical_Survey__c', 'Contact_Name__c', 'HEALTH_MEDICAL__c');
		Database.executeBatch(surveyHM);

		BatchSurveyStatusUpdateTemp surveySES = new BatchSurveyStatusUpdateTemp('SES__c', 'Contact_Name__c', 'SES__c');
		Database.executeBatch(surveySES);
        
        BatchSurveyStatusUpdateTemp surveyWH = new BatchSurveyStatusUpdateTemp('Womens_Health__c', 'Contact_Name__c', 'WOMENS_HEALTH__c');
		Database.executeBatch(surveyWH);
        
        BatchSurveyStatusUpdateTemp surveySE = new BatchSurveyStatusUpdateTemp('Subjective_English_Survey__c', 'Contact_Name__c', 'SUBJECTIVE_ENGLISH__c');
		Database.executeBatch(surveySE);

		BatchSurveyStatusUpdateTemp surveyADL = new BatchSurveyStatusUpdateTemp('ADL_Survey__c', 'Contact_Name__c', 'ADL__c');
		Database.executeBatch(surveyADL);

        BatchSurveyStatusUpdateTemp surveyDIET = new BatchSurveyStatusUpdateTemp('Diet__c', 'Contact_Name__c', 'DIET__c');
		Database.executeBatch(surveyDIET);
        
        BatchSurveyStatusUpdateTemp surveySWLS = new BatchSurveyStatusUpdateTemp('Swls_Survey__c', 'Contact_Name__c', 'SWLS__c');
		Database.executeBatch(surveySWLS);
        
        BatchSurveyStatusUpdateTemp surveyQPAR = new BatchSurveyStatusUpdateTemp('QPAR__c', 'Contact_Name__c', 'QPAR__c');
		Database.executeBatch(surveyQPAR);
        
        BatchSurveyStatusUpdateTemp surveySOCSTR = new BatchSurveyStatusUpdateTemp('Social_Stressor_Survey__c', 'Contact_Name__c', 'SOCIAL_STRESSOR__c');
		Database.executeBatch(surveySOCSTR);
        
        BatchSurveyStatusUpdateTemp surveySOCSUP = new BatchSurveyStatusUpdateTemp('Social_Support_Survey__c', 'Contact_Name__c', 'SOCIAL_SUPPORT__c');
		Database.executeBatch(surveySOCSUP);
        
        BatchSurveyStatusUpdateTemp surveyCANCER = new BatchSurveyStatusUpdateTemp('Cancer__c', 'Contact_Name__c', 'CANCER__c');
		Database.executeBatch(surveyCANCER);
        
        BatchSurveyStatusUpdateTemp surveyCOVID = new BatchSurveyStatusUpdateTemp('COVID_Survey__c', 'Contact__c', 'COVID__c');
		Database.executeBatch(surveyCOVID);
        
        BatchSurveyStatusUpdateTemp surveyBRAIN = new BatchSurveyStatusUpdateTemp('Personal_and_Family_History_of_Brain__c', 'Contact__c', 'BRAIN_DISEASE__c');
		Database.executeBatch(surveyBRAIN);
        
        BatchSurveyStatusUpdateTemp surveyFHAD = new BatchSurveyStatusUpdateTemp('FHAD_Survey__c', 'Contact__c', 'FHAD__c');
		Database.executeBatch(surveyFHAD);
        
        BatchSurveyStatusUpdateTemp surveySLEEP = new BatchSurveyStatusUpdateTemp('Sleep_Survey__c', 'Contact__c', 'SLEEP__c');
		Database.executeBatch(surveySLEEP);
        
        BatchSurveyStatusUpdateTemp surveyPERSTR = new BatchSurveyStatusUpdateTemp('Perceived_Stress_Scale__c', 'Contact__c', 'PERCEIVED_STRESS__c');
		Database.executeBatch(surveyPERSTR);
        
        BatchSurveyStatusUpdateTemp surveyANXIETY = new BatchSurveyStatusUpdateTemp('Anxiety_Survey__c', 'Contact__c', 'ANXIETY__c');
		Database.executeBatch(surveyANXIETY);

    }
}