objects/Bean_Game__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bean Games</relationshipLabel>
        <relationshipName>Bean_Games</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Left_Hand_Average__c</fullName>
        <formula>(
        VALUE(LEFT(LeftHand_1_ExerciseTime__c, FIND(&quot;:&quot;, LeftHand_1_ExerciseTime__c) - 1)) +
        VALUE(LEFT(LeftHand_2_ExerciseTime__c, FIND(&quot;:&quot;, LeftHand_2_ExerciseTime__c) - 1)) +
        VALUE(LEFT(LeftHand_3_ExerciseTime__c, FIND(&quot;:&quot;, LeftHand_3_ExerciseTime__c) - 1)) +
        VALUE(LEFT(LeftHand_4_ExerciseTime__c, FIND(&quot;:&quot;, LeftHand_4_ExerciseTime__c) - 1))
    )*60 / 4
+

    (
        VALUE(MID(LeftHand_1_ExerciseTime__c, FIND(&quot;:&quot;, LeftHand_1_ExerciseTime__c) + 1, LEN(LeftHand_1_ExerciseTime__c))) +
        VALUE(MID(LeftHand_2_ExerciseTime__c, FIND(&quot;:&quot;, LeftHand_2_ExerciseTime__c) + 1, LEN(LeftHand_2_ExerciseTime__c))) +
        VALUE(MID(LeftHand_3_ExerciseTime__c, FIND(&quot;:&quot;, LeftHand_3_ExerciseTime__c) + 1, LEN(LeftHand_3_ExerciseTime__c))) +
        VALUE(MID(LeftHand_4_ExerciseTime__c, FIND(&quot;:&quot;, LeftHand_4_ExerciseTime__c) + 1, LEN(LeftHand_4_ExerciseTime__c)))
    ) / 4</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Left Hand Average</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Right_Hand_Average__c</fullName>
        <formula>(
VALUE(Left(RightHand_1_ExerciseTime__c, FIND(&quot;:&quot;, RightHand_1_ExerciseTime__c) - 1)) +
VALUE(Left(RightHand_2_ExerciseTime__c, FIND(&quot;:&quot;, RightHand_2_ExerciseTime__c) - 1)) +
VALUE(Left(RightHand_3_ExerciseTime__c, FIND(&quot;:&quot;, RightHand_3_ExerciseTime__c) - 1)) +
VALUE(Left(RightHand_4_ExerciseTime__c, FIND(&quot;:&quot;, RightHand_4_ExerciseTime__c) - 1))
)*60 / 4

+

(
VALUE(MID(RightHand_1_ExerciseTime__c, FIND(&quot;:&quot;, RightHand_1_ExerciseTime__c) + 1, LEN(RightHand_1_ExerciseTime__c))) +
VALUE(MID(RightHand_2_ExerciseTime__c, FIND(&quot;:&quot;, RightHand_2_ExerciseTime__c) + 1, LEN(RightHand_2_ExerciseTime__c))) +
VALUE(MID(RightHand_3_ExerciseTime__c, FIND(&quot;:&quot;, RightHand_3_ExerciseTime__c) + 1, LEN(RightHand_3_ExerciseTime__c))) +
VALUE(MID(RightHand_4_ExerciseTime__c, FIND(&quot;:&quot;, RightHand_4_ExerciseTime__c) + 1, LEN(RightHand_4_ExerciseTime__c)))
) / 4</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Right Hand Average</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Bean Game</label>
    <nameField>
        <displayFormat>BGN-{00000000}</displayFormat>
        <label>Bean Game Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bean Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Bean_Game__c</fullName>
        <label>Bean Game</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Education_Attainment__c</fullName>
        <formula>IF( OR(ISPICKVAL( Highest_level_of_education_completed__c , &apos;Up to 8 Years&apos;), ISPICKVAL( Highest_level_of_education_completed__c , &apos;Completed 8th Grade (Elementary or Primary School Graduate)&apos;), ISPICKVAL( Highest_level_of_education_completed__c , &apos;Some High School&apos;) ) , 1,
 IF(ISPICKVAL( Highest_level_of_education_completed__c , &apos;High School Diploma (Baccalaureate)&apos;), 2,  IF(ISPICKVAL( Highest_level_of_education_completed__c , &apos;Some College (Some University)&apos;), 3,  IF(ISPICKVAL( Highest_level_of_education_completed__c , &apos;College Degree (University Graduate)&apos;), 4,  IF(ISPICKVAL( Highest_level_of_education_completed__c , &apos;Post Graduate Degree (Masters or Doctorate)&apos;), 5, 0) ) ) ) 
 )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Education Attainment</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sex__c</fullName>
        <description>Test-taker&apos;s biological sex</description>
        <label>Sex</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Intersex</fullName>
                </value>
                <value>
                    <fullName>Prefer not to answer</fullName>
                    <isActive>false</isActive>
                    <label>Prefer not to answer</label>
                </value>
                <value>
                    <fullName>unknown</fullName>
                    <isActive>false</isActive>
                    <label>unknown</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Game_Detail__c.object
<CustomObject>
    <description>This object is having game information and dependency for other game.</description>
    <fields>
        <fullName>Max_Score__c</fullName>
        <description>The Maximum Score that participant can Score By Playing the Game</description>
        <inlineHelpText>The Maximum Score that participant can Score By Playing the Game</inlineHelpText>
        <label>Max Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Game Detail</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Game Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Participant_Dashboard__c.object
<CustomObject>
    <fields>
        <fullName>Data_Name__c</fullName>
        <label>Data Name</label>
        <length>26</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Data_Value__c</fullName>
        <label>Data Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Game_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Game Detail</label>
        <referenceTo>Game_Detail__c</referenceTo>
        <relationshipLabel>Participant Dashboards</relationshipLabel>
        <relationshipName>DashBoard_Datas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Participant Dashboard</label>
    <nameField>
        <label>Participant Dashboard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participant Dashboards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Participant_Game_Info__c.object
<CustomObject>
    <description>This object is having details of the participant&apos;s game.</description>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to contact, saving contact id, will show contact name at front-end.</description>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Participant Game Infos</relationshipLabel>
        <relationshipName>Participant_Game_Infos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Count_Of_No_Of_Correct_Answered__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Count Of No Of Correct Answered</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Count_Of_No_of_Question_Attempted__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Count Of No of Question Attempted</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Count_Of_Total_Reaction_Time__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Count Of Total Reaction Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Game_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to game, saving game id, will show game name at front-end.</description>
        <label>Game Name</label>
        <referenceTo>Game_Detail__c</referenceTo>
        <relationshipLabel>Participant Game Infos</relationshipLabel>
        <relationshipName>Participant_Game_Infos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Game_Play_Status__c</fullName>
        <label>Game Play Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not-Completed</fullName>
                    <default>true</default>
                    <label>Not-Completed</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>No_Of_Correct_Answered__c</fullName>
        <description>Count the correct answers were responded by the participant</description>
        <label>No. Of Correct Answered</label>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Is_Correct__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Is_Practice_Question__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>Participant_Game_Response__c.Participant_Game_InfoID__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>No_of_Question_Attempted__c</fullName>
        <description>Count of question from participant responses.</description>
        <label>No. of Question Attempted</label>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Is_Practice_Question__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>Participant_Game_Response__c.Participant_Game_InfoID__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Reaction_Time__c</fullName>
        <description>This field represents, the total time taken by the participant.</description>
        <label>Total Reaction Time</label>
        <summarizedField>Participant_Game_Response__c.Reaction_Time_in_ms__c</summarizedField>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Is_Practice_Question__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>Participant_Game_Response__c.Participant_Game_InfoID__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>User_Device__c</fullName>
        <description>Device at which test was conducted.(e.g. Desktop, iPad, iPhone, Android.)</description>
        <label>User Device</label>
        <length>56</length>
        <type>Text</type>
    </fields>
    <label>Participant Game Info</label>
    <nameField>
        <displayFormat>PGI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Game Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/People_Like_You_Data__c.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <label>Age</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Average__c</fullName>
        <formula>( High_Average__c  +  Low_Average__c )/2</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Average</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Education__c</fullName>
        <label>Education</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Game_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Game Name</label>
        <referenceTo>Game_Detail__c</referenceTo>
        <relationshipLabel>People Like You Data</relationshipLabel>
        <relationshipName>People_Like_You_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>High_Average__c</fullName>
        <label>High Average</label>
        <precision>8</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Low_Average__c</fullName>
        <label>Low Average</label>
        <precision>8</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sex__c</fullName>
        <label>Sex</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Intersex</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>People Like You Data</label>
    <nameField>
        <displayFormat>PLUD-{000000}</displayFormat>
        <label>People Like You Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People Like You Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ParticipantVIPResultsController.cls
/* Created By: Sibi dahy
** Created On: 17/08/2021
** Description/Purpose: Why and where it is used [TM-203]-It was Created for Catchment and Expanded Game Users Dashboards
** Methods: {getMyGameDetails,getDashboardDataForloggedInUser,getGuestUserGameDetails,getDashboardData}
** Test Class: {ParticipantResultsController_Test} {Code Coverage:96%}
** Controller for catchment results page and Expanded myResults page
** Modify By : Sibi Sathyan for Longitudinal Requirement 
*/
public without sharing class ParticipantVIPResultsController
{   
    @AuraEnabled(cacheable=true)
    public static DashboardData getDashboardDataForloggedInUser (String gameName)
    {
        List<User> lstUsers = [SELECT Id,ContactId From User where Id =: UserInfo.getUserId() AND ContactId != null];
        String ContactId = lstUsers[0].ContactId;
        return getDashboardData(ContactId, gameName);
    }
    
    @AuraEnabled(cacheable=true) 
    public static DashboardData getDashboardData (String contactId, String gameName)
    {
        Map<String, Integer> mapOtherData = new Map<String, Integer>();
        Map<String, Integer> mapWhatHappendWithAgeData = new Map<String, Integer>();
        Map<String, Integer> mapPlyAverageValuesData = new Map<String, Integer>();
        String userDevice;
        Id currPGIId;        
        mapOtherData.put('YourScore',0);
        mapOtherData.put('isGamePlayed',0); 
        mapOtherData.put('CorrectAnswers',0); 
        mapOtherData.put('ReactionTime',0); 
        mapOtherData.put ('People Like You', 0);
        mapPlyAverageValuesData.put ('LowAverage', 0);
        mapPlyAverageValuesData.put ('HighAverage', 0); 
        DashboardData objDashboardData = new DashboardData();
        
        List<Participant_Game_Info__c> pgis = [SELECT Count_Of_No_Of_Correct_Answered__c, Count_Of_No_of_Question_Attempted__c,
                                              Count_Of_Total_Reaction_Time__c, No_Of_Correct_Answered__c,
                                              No_of_Question_Attempted__c,Total_Reaction_Time__c, User_Device__c,Id,CreatedDate
                                              FROM Participant_Game_Info__c 
                                              WHERE Contact_Name__c =: contactId  
                                              AND Game_Name__r.Name =:gameName
                                              AND ((Count_Of_No_Of_Correct_Answered__c != null
                                              AND Count_Of_No_of_Question_Attempted__c != null
                                              AND Count_Of_Total_Reaction_Time__c != null
                                              AND Count_Of_No_Of_Correct_Answered__c >0
                                              AND Count_Of_No_of_Question_Attempted__c >0
                                              AND Count_Of_Total_Reaction_Time__c >0) 
                                              OR (No_Of_Correct_Answered__c != null
                                              AND No_of_Question_Attempted__c != null
                                              AND Total_Reaction_Time__c != null
                                              AND No_Of_Correct_Answered__c >0
                                              AND No_of_Question_Attempted__c >0
                                              AND Total_Reaction_Time__c >0))
                                              AND Game_Play_Status__c = 'Completed'
                                              ORDER BY CreatedDate DESC LIMIT 1];
        if(pgis.size()>0){
            for(Participant_Game_Info__c pgi : pgis){
                if(pgi.CreatedDate.Date() >= Date.Today()-1){
                	pgi.Count_Of_No_of_Question_Attempted__c = pgi.No_of_Question_Attempted__c;
                    pgi.Count_Of_No_Of_Correct_Answered__c = pgi.No_Of_Correct_Answered__c;
                    pgi.Count_Of_Total_Reaction_Time__c = pgi.Total_Reaction_Time__c;
            	}  
            }                      
        } 
        
        for(Participant_Game_Info__c objInfo:pgis)
        {
            userDevice = objInfo.User_Device__c;
            currPGIId= objInfo.Id;
            //changes was made to remove dependency of RollUp summary fields on PGI 
             if(objInfo.Count_Of_No_Of_Correct_Answered__c != null && objInfo.Count_Of_No_of_Question_Attempted__c != null   && objInfo.Count_Of_Total_Reaction_Time__c != null &&  Integer.valueOf(objInfo.Count_Of_No_of_Question_Attempted__c) >0 &&  Integer.valueOf(objInfo.Count_Of_No_Of_Correct_Answered__c)>0 && Integer.valueOf(objInfo.Count_Of_Total_Reaction_Time__c)>0)                             
            {
                mapOtherData.put('isGamePlayed',1);
                mapOtherData.put('YourScore', Integer.valueOf(objInfo.Count_Of_Total_Reaction_Time__c/objInfo.Count_Of_No_of_Question_Attempted__c));
                mapOtherData.put('CorrectAnswers', Integer.valueOf(objInfo.Count_Of_No_Of_Correct_Answered__c));
                mapOtherData.put('ReactionTime', Integer.valueOf(objInfo.Count_Of_Total_Reaction_Time__c / objInfo.Count_Of_No_of_Question_Attempted__c));
                mapOtherData.put('UserDevice', objInfo.User_Device__c=='DESKTOP'?0:1); 
            }
        }
        Contact objCon = [SELECT Sex__c,Age__c,Education_Attainment__c FROM Contact WHERE Id=:contactId ];
        Decimal age = objCon.Age__c;
        Decimal pluage,lowage,highage; 
        if(age>85){
            lowage = 80;
            highage = 115;
        }
        else if(age<18){
            lowage = 18;
            highage = 28;
        }
        else if(age<28){
            lowage = 18;
            highage = age+10;
        }
        else{
            lowage = age-10;
            highage = age+10;
        }        
        pluage = age == null ? 18 : age;
        pluage = pluage < 18 ? 18 : pluage;
        pluage = pluage > 90 ? 90 : pluage;
        Decimal edu_att = objCon.Education_Attainment__c;
        edu_att = edu_att == null ? 1 : edu_att;
        String sex = objCon.Sex__c;
        
        mapPlyAverageValuesData.put ('MaxValue', Integer.valueOf([SELECT Max_Score__c FROM Game_Detail__c where Name=:gameName LIMIT 1].Max_Score__c) );
        List<Participant_Game_Info__c> peopleLikeYouPGIList = [SELECT Count_Of_Total_Reaction_Time__c ,Count_Of_No_of_Question_Attempted__c,Count_Of_No_Of_Correct_Answered__c
                                           FROM Participant_Game_Info__c 
                                           WHERE Contact_Name__r.Age__c > 0
                                           AND Contact_Name__r.Age__c >= :lowage
                                           AND Contact_Name__r.Age__c <= :highage
                                           AND User_Device__c != ''
                                           AND Contact_Name__r.Sex__c != ''
                                           AND Contact_Name__r.Education_Attainment__c != null
                                           AND Count_Of_No_Of_Correct_Answered__c >0
                                           AND Count_Of_No_of_Question_Attempted__c >0
                                           AND Count_Of_Total_Reaction_Time__c >0
                                           AND Game_Name__r.Name =: gameName
                                           AND Id != :currPGIId
                                           Order by CreatedDate DESC
                                           LIMIT 49990];
        List<Decimal> quartileValues = new List<Decimal>();
        if(peopleLikeYouPGIList !=null && peopleLikeYouPGIList.size() >= 25){ 
            if(gameName == 'DLTRS' || gameName == 'Deary Simple And Complex Reaction Time' || gameName == 'Flanker'){
                        Decimal sumReationTime = 0;
                        List<Decimal> reacttimeList = new List<Decimal>();
                        for (Participant_Game_Info__c peopleLikeYouPGI : peopleLikeYouPGIList) {
                            Decimal reactTime = peopleLikeYouPGI.Count_Of_Total_Reaction_Time__c / peopleLikeYouPGI.Count_Of_No_of_Question_Attempted__c;
                            sumReationTime += reactTime;
                            reacttimeList.add(reactTime);      
                        }
                        Decimal reactTimeAvg =   sumReationTime / peopleLikeYouPGIList.size();
                        if(reactTimeAvg != null){
                            mapOtherData.put ('People Like You', Integer.valueOf(reactTimeAvg));
                        }
                		quartileValues.addAll(reacttimeList);
                	}
            else{      
                        Decimal sumcorrAnswer = 0;    
                        Decimal corrAnswerMax = 0;
                        List<Decimal> corrAnswersList = new List<Decimal>();
                        for (Participant_Game_Info__c peopleLikeYouPGI : peopleLikeYouPGIList) { 
                            Decimal corrAnswer = peopleLikeYouPGI.Count_Of_No_Of_Correct_Answered__c;
                            sumcorrAnswer += corrAnswer;
                            corrAnswersList.add(corrAnswer);
                        }
                        Decimal corrAnswerAvg =   sumcorrAnswer / peopleLikeYouPGIList.size();
                        if(corrAnswerAvg != null){
                            mapOtherData.put ('People Like You', Integer.valueOf(corrAnswerAvg));
                        }  
                		quartileValues.addAll(corrAnswersList);
                	}            
                      	quartileValues.sort();                
                        Integer dataSize = quartileValues.size();
                        Integer q1Index = Math.ceil((dataSize + 1) / 4.0).intValue();
                        Integer q2Index = Math.ceil((dataSize + 1) / 2.0).intValue();
                        Integer q3Index = Math.ceil(3 * (dataSize + 1) / 4.0).intValue();
                        
                        if (dataSize > 0) {
                            Integer lowAverage = Integer.valueOf(quartileValues[q1Index - 1]);
                            Integer highAverage = Integer.valueOf(quartileValues[q3Index - 1]);
                            if(lowAverage != null){
                                mapPlyAverageValuesData.put ('LowAverage', lowAverage);
                            }
                            if(highAverage != null){
                                mapPlyAverageValuesData.put ('HighAverage', highAverage);                                      
                            }
                        }
        	}
        	else{
            List<People_Like_You_Data__c> objLikeYouList = [SELECT Education__c,Sex__c, Age__c,Average__c,High_Average__c,Low_Average__c,Game_Name__r.Max_Score__c
            FROM People_Like_You_Data__c
            WHERE Game_Name__r.Name =:gameName 
            AND Sex__c =:objCon.Sex__c AND Education__c>=: edu_att
            AND Age__c =:pluage Order BY Education__c ASC LIMIT 1];
                if(objLikeYouList.size()>0){
                    for(People_Like_You_Data__c peopleLikeYouData : objLikeYouList){
                        if(gameName=='Flanker'){
                            mapPlyAverageValuesData.put ('LowAverage', 564);
                            mapPlyAverageValuesData.put ('HighAverage', 963);    
                        }
                        else
                        {
                            mapPlyAverageValuesData.put ('LowAverage', Integer.valueOf(peopleLikeYouData.Low_Average__c));
                            mapPlyAverageValuesData.put ('HighAverage', Integer.valueOf(peopleLikeYouData.High_Average__c)); 
                        }  
                    }
                }
                else{
                    if(gameName=='Fake News') {
                        mapPlyAverageValuesData.put ('LowAverage', 8);
                        mapPlyAverageValuesData.put ('HighAverage', 16);   
                    }                   
                }
             
           }
      List<Participant_Dashboard__c> partDashboard = [SELECT Data_Value__c FROM Participant_Dashboard__c WHERE Game_Detail__r.Name=:gameName LIMIT 1];
            if(partDashboard !=null && partDashboard.size()>0){
            	mapOtherData.put('Overall Average', Integer.valueOf(partDashboard[0].Data_Value__c));
            }
            else{
                mapOtherData.put('Overall Average', 0);
            }
        objDashboardData.mapOtherData = mapOtherData;
        objDashboardData.mapPlyAverageValuesData = mapPlyAverageValuesData;
        return objDashboardData;
    }
    
    @AuraEnabled(cacheable=true)
    public static DashboardDataBean getDashboardDataBeanGame(String handSide){
        List<User> lstUsers = [SELECT Id,ContactId From User where Id =: UserInfo.getUserId() AND ContactId != null];
        String contactId = lstUsers[0].ContactId;
        //String contactId='0038G00000YESnyQAH';//Hardcoding for testing purpose
        String gameName = 'Bean Game';
        DashboardDataBean objDashboardData = new DashboardDataBean();
        Map<String, Decimal> mapOtherData = new Map<String, Decimal>();
        Map<String, Decimal> mapWhatHappendWithAgeData = new Map<String, Decimal>();
        Map<String, Decimal> mapPlyAverageValuesData = new Map<String, Decimal>();
        mapOtherData.put('YourScore',0);
        mapOtherData.put('isGamePlayed',0); 
        mapOtherData.put('CorrectAnswers',0); 
        mapOtherData.put('ReactionTime',0); 
        mapOtherData.put ('People Like You', 0);
        mapPlyAverageValuesData.put ('LowAverage', 0);
        mapPlyAverageValuesData.put ('HighAverage', 0); 
        
        List<Bean_Game__c> bean = [SELECT Right_Hand_Average__c,Left_Hand_Average__c,Contact__c 
            					  FROM Bean_Game__c where Contact__c = :contactId Order by CreatedDate DESC LIMIT 1];         
        if(bean.size()>0){
        	mapOtherData.put('isGamePlayed',1);  
            List<Participant_Dashboard__c> partDashboard;
            if(handSide == 'left'){
                mapOtherData.put('ReactionTime',bean[0].Left_Hand_Average__c);
                partDashboard = [SELECT Data_Value__c FROM Participant_Dashboard__c 
                                                        WHERE Game_Detail__r.Name=:gameName and 	
                                                        Data_Name__c='Overall Average Left Hand' LIMIT 1];
                mapPlyAverageValuesData.put('MaxValue', Integer.valueOf([SELECT Max_Score__c FROM Game_Detail__c 
                                                                         where Name=:gameName LIMIT 1].Max_Score__c));
            }
            else{
                mapOtherData.put('ReactionTime',bean[0].Right_Hand_Average__c);
                partDashboard = [SELECT Data_Value__c FROM Participant_Dashboard__c 
                                                        WHERE Game_Detail__r.Name=:gameName and 	
                                                        Data_Name__c='Overall Average Right Hand' LIMIT 1];
                mapPlyAverageValuesData.put('MaxValue', Integer.valueOf([SELECT Max_Score_2__c FROM Game_Detail__c 
                                                                         where Name=:gameName LIMIT 1].Max_Score_2__c));
            } 
            mapOtherData.put('Overall Average', Integer.valueOf(partDashboard[0].Data_Value__c)); 
            //Quartile calcualtion starts from here
            Contact objCon = [SELECT Sex__c,Age__c FROM Contact WHERE Id=:bean[0].Contact__c ];
            Decimal age = objCon.Age__c;
            Decimal pluage,lowage,highage; 
            if(age>85){
                lowage = 80;
                highage = 115;
            }
            else if(age<18){
                lowage = 18;
                highage = 28;
            }
            else if(age<28){
                lowage = 18;
                highage = age+10;
            }
            else{
                lowage = age-10;
                highage = age+10;
            }        
            pluage = age == null ? 18 : age;
            pluage = pluage < 18 ? 18 : pluage;
            pluage = pluage > 90 ? 90 : pluage;
            
            List<Bean_Game__c> beanPeopleLikeYou = [SELECT Right_Hand_Average__c,Left_Hand_Average__c 
                                                    FROM Bean_Game__c 
                                                    WHERE Contact__r.Age__c > 0
                                          			AND Contact__r.Age__c >= :lowage
                                           			AND Contact__r.Age__c <= :highage                                        
                                           			AND Contact__r.Sex__c != ''
                                           			AND Contact__r.Education_Attainment__c != null
                                                    AND  Id !=: bean[0].Id
                                                    Order by CreatedDate DESC
                                             	    LIMIT 49990];
            
             List<Decimal> quartileValues = new List<Decimal>();
             Decimal sumReationTime = 0;
             if(beanPeopleLikeYou !=null && beanPeopleLikeYou.size() > 0){//Check if 0 or 25                 
                  for (Bean_Game__c beangame : beanPeopleLikeYou) {
                      if(handSide == 'left'){
                        quartileValues.add(beangame.Left_Hand_Average__c);
                        sumReationTime += beangame.Left_Hand_Average__c;
                        
                    }
                    else{
                        quartileValues.add(beangame.Right_Hand_Average__c);
                        sumReationTime += beangame.Right_Hand_Average__c;
                    }
                  }
					mapOtherData.put ('People Like You', sumReationTime / beanPeopleLikeYou.size());                 
              }
              else {
                //Need to add if less numbers
              }        
        quartileValues.sort();                
        Decimal dataSize = quartileValues.size();
        Integer q1Index = Math.ceil((dataSize + 1) / 4.0).intValue();
        Integer q2Index = Math.ceil((dataSize + 1) / 2.0).intValue();
        Integer q3Index = Math.ceil(3 * (dataSize + 1) / 4.0).intValue();
        System.debug('q1Index: '+q1Index);
        System.debug('q2Index: '+q2Index);
        System.debug('q3Index: '+q3Index);
        System.debug('quartileValues: '+quartileValues);
          if (dataSize > 0) {
                            Decimal lowAverage = quartileValues[q1Index - 1].setScale(2, System.RoundingMode.HALF_UP);
                            Decimal highAverage = quartileValues[q3Index - 1].setScale(2, System.RoundingMode.HALF_UP);
                            if(lowAverage != null){
                                mapPlyAverageValuesData.put ('LowAverage', lowAverage);
                            }
                            if(highAverage != null){
                                mapPlyAverageValuesData.put ('HighAverage', highAverage);                                      
                            }
                        }
        }
		objDashboardData.mapOtherData = mapOtherData;    
        objDashboardData.mapPlyAverageValuesData = mapPlyAverageValuesData;
        return objDashboardData;
    }
    
    public class DashboardData
    {
        @AuraEnabled
        public Map<String, Integer> mapOtherData;
        /* @AuraEnabled
        public Integer age;
        @AuraEnabled
        public Map<String, Integer> mapWhatHappendWithAgeData; */
        @AuraEnabled
        public Map<String,Integer> mapPlyAverageValuesData;     
    }  
    
        public class DashboardDataBean
    {
        @AuraEnabled
        public Map<String, Decimal> mapOtherData;
        @AuraEnabled
        public Map<String,Decimal> mapPlyAverageValuesData;     
    }  
}