objects/Bean_Game__c.object
<CustomObject>
    <label>Bean Game</label>
    <nameField>
        <displayFormat>BGN-{00000000}</displayFormat>
        <label>Bean Game Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bean Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Bean_Game__c</fullName>
        <label>Bean Game</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Participant_Game_Info__c.object
<CustomObject>
    <description>This object is having details of the participant&apos;s game.</description>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to contact, saving contact id, will show contact name at front-end.</description>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Participant Game Infos</relationshipLabel>
        <relationshipName>Participant_Game_Infos</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Participant Game Info</label>
    <nameField>
        <displayFormat>PGI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Game Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BatchClassSpeechTaskUnlockTest.cls
@isTest
public class BatchClassSpeechTaskUnlockTest {

    @testSetup
    static void setup() {
     
        List<Contact> testContacts = new List<Contact>();
        List<Participant_Game_Info__c> testpgis = new List<Participant_Game_Info__c>();

        // Create test Contacts with CreatedDate within the last 365 days
        Date oneYearAgo = Date.today().addDays(-365);

        for (Integer i = 0; i < 10; i++) {
            testContacts.add(new Contact(LastName = 'Test Contact ' + i, CreatedDate = oneYearAgo));
        }
        insert testContacts;

        for (Contact con : testContacts) {
            testpgis.add(new Participant_Game_Info__c(Contact_Name__c = con.Id));
        }
        insert testpgis;
    }

    @isTest
    static void testBatchClassSpeechTaskUnlock() {
        
        Test.startTest();
        // Run the batch
        BatchClassSpeechTaskUnlock batchGU = new BatchClassSpeechTaskUnlock();
        String jobId = System.schedule('Test Batch', '0 0 23 * * ?', batchGU);

        Test.stopTest();

        List<Contact> updatedContacts = [SELECT Id,Speech_Task__c  FROM Contact];

        for (Contact con : updatedContacts) {

            System.assertEquals('Opened', con.Speech_Task__c);
        }
    }

   @isTest
    static void testExecuteMethod() {
        // Create a test scope
        List<Participant_Game_Info__c> testScope = new List<Participant_Game_Info__c>();
        
        // Create a test Contact record
        Contact testContact = new Contact(LastName = 'Test Contact');
        insert testContact;

        // Create a related Bean_Game__c record associated with the test Contact
        Participant_Game_Info__c testpgi = new Participant_Game_Info__c(Contact_Name__c = testContact.Id);
        insert testpgi;

        testScope.add(testpgi);

        Test.startTest();

        // Instantiate the batch class
        BatchClassSpeechTaskUnlock batchJob = new BatchClassSpeechTaskUnlock();

        // Execute the 'execute' method directly
        batchJob.execute(null, testScope);

        Test.stopTest();

        // Verify the results
        // Query the Contact record to check if the 'Bean_Game__c' field is updated as expected
        testContact = [SELECT Id, Speech_Task__c  FROM Contact WHERE Id = :testContact.Id];
        System.assertEquals('Opened', testContact.Speech_Task__c);
    }
}