objects/Bean_Game__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bean Games</relationshipLabel>
        <relationshipName>Bean_Games</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bean Game</label>
    <nameField>
        <displayFormat>BGN-{00000000}</displayFormat>
        <label>Bean Game Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bean Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Activation_Date__c</fullName>
        <description>Set current date when user created for new contact or historical contact.</description>
        <label>Activation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Bean_Game__c</fullName>
        <label>Bean Game</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ECog_12__c</fullName>
        <label>ECog 12</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>Language selected by test-taker at public application.</description>
        <inlineHelpText>If you are multi-lingual you may want to select the language that you are most fluent in</inlineHelpText>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                </value>
                <value>
                    <fullName>Español</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to mark duplicate contact records.</description>
        <inlineHelpText>This field contains the reference to parent contact which already have the data same/similar to this contact.</inlineHelpText>
        <label>Parent Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Duplicate_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ECog_12__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>ECog&apos;s-12</relationshipLabel>
        <relationshipName>ECog_s_12</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ECog-12</label>
    <nameField>
        <displayFormat>ECog-12-{0000000000}</displayFormat>
        <label>ECog-12 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ECog&apos;s-12</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TremendousSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>TremendousSettings</label>
    <fields>
        <fullName>AuthToken__c</fullName>
        <label>AuthToken</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Authorization__c</fullName>
        <label>Authorization</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CampaignId__c</fullName>
        <label>CampaignId</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContentType__c</fullName>
        <label>ContentType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CurrencyCode__c</fullName>
        <label>CurrencyCode</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DeliveryMethod__c</fullName>
        <label>DeliveryMethod</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Denomination__c</fullName>
        <label>Denomination</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EndpointURL__c</fullName>
        <label>EndpointURL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FundingSourceId__c</fullName>
        <label>FundingSourceId</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RestMethod__c</fullName>
        <label>RestMethod</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Spanish_CampaignId__c</fullName>
        <label>Spanish CampaignId</label>
        <length>22</length>
        <type>Text</type>
    </fields>
</CustomObject>

classes/SendRewardsToUsersECog12Batch.cls
public class SendRewardsToUsersECog12Batch implements Database.Batchable<SObject>, Schedulable, Database.AllowsCallouts {
    
    public void execute(SchedulableContext sc) {
        SendRewardsToUsersBatch sendReward = new SendRewardsToUsersBatch();
        Database.executeBatch(sendReward, 100);
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([
            SELECT Id, FirstName, Email, Language__c FROM Contact 
            WHERE Tremendous_Award_Sent_ECog_12__c = False 
            AND Enrolled_in_Paid_Campaign_ECog_12__c = True
            AND Parent_Contact__c = null
            AND Email != null
            AND Activation_Date__c != null
        ]);
    }

    public void execute(Database.BatchableContext bc, List<Contact> cons) {        
        List<Contact> contListUpd = new List<Contact>();
        try { 
            Map <Id, Contact> contMap = new Map <Id, Contact>(cons);  
            Set<Id> contIdSet = contMap.keySet();
            Set<Id> beanContIdSet = new Set<Id>();  
            Set<Contact> contsEligible = new Set<Contact>();
            System.debug('contIdSet: '+contIdSet);
          
            List<Bean_Game__c> beanList =  [select 	Contact__c from Bean_Game__c
                                                 where Contact__c in : contIdSet];            
           
            for(Bean_Game__c ship: beanList){
                beanContIdSet.add(ship.Contact__c);
            }
            System.debug('beanContIdSet: '+beanContIdSet);
            
           List<ECog_12__c> eCog2List =  [select 	Contact__c from ECog_12__c
                                                 where Contact__c in : beanContIdSet];            
           
            for(ECog_12__c eCog: eCog2List){
               contsEligible.add(contMap.get(eCog.Contact__c)); 
            }
            System.debug('contsEligible: '+contsEligible);
           
            TremendousSetting__c trmAPI = TremendousSetting__c.getValues('RewardsSettingEcog');
            for (Contact con : contsEligible) {
                contListUpd.add(con);
                system.debug('count--->' + contsEligible.size());
                con.Tremendous_Award_Sent_ECog_12__c = true;                
                SendRewardRequestWrapper request = new SendRewardRequestWrapper();           
                request.payment = new SendRewardRequestWrapper.Payment();
                request.payment.funding_source_id = trmAPI.FundingSourceId__c;    
                request.rewards = new List<SendRewardRequestWrapper.Rewards>();
                SendRewardRequestWrapper.Rewards reward = new SendRewardRequestWrapper.Rewards();
                reward.value = new SendRewardRequestWrapper.Value();
                reward.value.denomination = trmAPI.Denomination__c;
                reward.value.currency_code = trmAPI.CurrencyCode__c;    
                reward.delivery = new SendRewardRequestWrapper.Delivery();
                reward.delivery.method = trmAPI.DeliveryMethod__c;    
                reward.recipient = new SendRewardRequestWrapper.Recipient();
                reward.recipient.name = con.FirstName;
                reward.recipient.email = con.Email;                   
                if (con.Language__c == 'Español') {
                    reward.campaign_id = trmAPI.Spanish_CampaignId__c;                    
                } else {
                    reward.campaign_id = trmAPI.CampaignId__c;
                } 
                request.rewards.add(reward);
                String payload = JSON.serialize(request);
                system.debug('payload--->' + payload);
                HttpRequest req = new HttpRequest();
                req.setMethod(trmAPI.RestMethod__c);
                req.setEndpoint(trmAPI.EndpointURL__c);
                req.setHeader('Content-Type', trmAPI.ContentType__c);
                req.setHeader('Authorization', trmAPI.Authorization__c+' ' + trmAPI.AuthToken__c);
                req.setBody(payload);
                Http httpHeader = new Http();
                HttpResponse res = new HttpResponse();
                try{
                    res = httpHeader.send(req);
                }
                catch(Exception ex){
                    System.debug('inside second catch Exception');
                    ExceptionLogHandler.logException(ex, 'SendRewardsToconsBatch', 'Execute', 'Contact Id: ' +con.Id + ', Exception in Tremendous API '
                                                     +' Error Message: '+ex.getMessage());
                }                
                system.debug('res--->' + res.getBody());
                system.debug('statuscode--->' + res.getStatusCode());
                if (res.getStatusCode() != 200 && res.getStatusCode() != 202) {
                    System.debug('inside respose exception handling');
                    String errorDetails = 'Tremendous API Error - Respose Code: ' + res.getStatusCode() + ', Contact Id: ' +con.Id + ', Error Response: ' + res.getBody();
                    ExceptionLogHandler.logException(null, 'SendRewardsToconsBatch', 'Execute', errorDetails);
                }
            }
            if(contListUpd.size()>0){
                system.debug('inside update contact');
                Database.update(contListUpd, false);
            }                
        } 
        catch (Exception ex) {
            ExceptionLogHandler.logException(ex, 'SendRewardsToconsBatch', 'Execute', 'Exception in Tremendous API for Contact '
                                             +' Error Message: '+ex.getMessage());
            if(contListUpd.size()>0){
                system.debug('inside exception update contact');
                Database.update(contListUpd, false);
            }
        }
     }
    
    public void finish(Database.BatchableContext context) {
    }
}