objects/Bean_Game__c.object
<CustomObject>
    <fields>
        <fullName>Left_Hand_Average__c</fullName>
        <formula>(
        VALUE(LEFT(LeftHand_1_ExerciseTime__c, FIND(&quot;:&quot;, LeftHand_1_ExerciseTime__c) - 1)) +
        VALUE(LEFT(LeftHand_2_ExerciseTime__c, FIND(&quot;:&quot;, LeftHand_2_ExerciseTime__c) - 1)) +
        VALUE(LEFT(LeftHand_3_ExerciseTime__c, FIND(&quot;:&quot;, LeftHand_3_ExerciseTime__c) - 1)) +
        VALUE(LEFT(LeftHand_4_ExerciseTime__c, FIND(&quot;:&quot;, LeftHand_4_ExerciseTime__c) - 1))
    )*60 / 4
+

    (
        VALUE(MID(LeftHand_1_ExerciseTime__c, FIND(&quot;:&quot;, LeftHand_1_ExerciseTime__c) + 1, LEN(LeftHand_1_ExerciseTime__c))) +
        VALUE(MID(LeftHand_2_ExerciseTime__c, FIND(&quot;:&quot;, LeftHand_2_ExerciseTime__c) + 1, LEN(LeftHand_2_ExerciseTime__c))) +
        VALUE(MID(LeftHand_3_ExerciseTime__c, FIND(&quot;:&quot;, LeftHand_3_ExerciseTime__c) + 1, LEN(LeftHand_3_ExerciseTime__c))) +
        VALUE(MID(LeftHand_4_ExerciseTime__c, FIND(&quot;:&quot;, LeftHand_4_ExerciseTime__c) + 1, LEN(LeftHand_4_ExerciseTime__c)))
    ) / 4</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Left Hand Average</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Right_Hand_Average__c</fullName>
        <formula>(
VALUE(Left(RightHand_1_ExerciseTime__c, FIND(&quot;:&quot;, RightHand_1_ExerciseTime__c) - 1)) +
VALUE(Left(RightHand_2_ExerciseTime__c, FIND(&quot;:&quot;, RightHand_2_ExerciseTime__c) - 1)) +
VALUE(Left(RightHand_3_ExerciseTime__c, FIND(&quot;:&quot;, RightHand_3_ExerciseTime__c) - 1)) +
VALUE(Left(RightHand_4_ExerciseTime__c, FIND(&quot;:&quot;, RightHand_4_ExerciseTime__c) - 1))
)*60 / 4

+

(
VALUE(MID(RightHand_1_ExerciseTime__c, FIND(&quot;:&quot;, RightHand_1_ExerciseTime__c) + 1, LEN(RightHand_1_ExerciseTime__c))) +
VALUE(MID(RightHand_2_ExerciseTime__c, FIND(&quot;:&quot;, RightHand_2_ExerciseTime__c) + 1, LEN(RightHand_2_ExerciseTime__c))) +
VALUE(MID(RightHand_3_ExerciseTime__c, FIND(&quot;:&quot;, RightHand_3_ExerciseTime__c) + 1, LEN(RightHand_3_ExerciseTime__c))) +
VALUE(MID(RightHand_4_ExerciseTime__c, FIND(&quot;:&quot;, RightHand_4_ExerciseTime__c) + 1, LEN(RightHand_4_ExerciseTime__c)))
) / 4</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Right Hand Average</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Bean Game</label>
    <nameField>
        <displayFormat>BGN-{00000000}</displayFormat>
        <label>Bean Game Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bean Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Game_Detail__c.object
<CustomObject>
    <description>This object is having game information and dependency for other game.</description>
    <fields>
        <fullName>Max_Score_2__c</fullName>
        <label>Max Score 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Score__c</fullName>
        <description>The Maximum Score that participant can Score By Playing the Game</description>
        <inlineHelpText>The Maximum Score that participant can Score By Playing the Game</inlineHelpText>
        <label>Max Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Game Detail</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Game Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Participant_Dashboard__c.object
<CustomObject>
    <fields>
        <fullName>Data_Name__c</fullName>
        <label>Data Name</label>
        <length>26</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Data_Value__c</fullName>
        <label>Data Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Game_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Game Detail</label>
        <referenceTo>Game_Detail__c</referenceTo>
        <relationshipLabel>Participant Dashboards</relationshipLabel>
        <relationshipName>DashBoard_Datas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Participant Dashboard</label>
    <nameField>
        <label>Participant Dashboard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participant Dashboards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BatchGameResultDashboardBeanGameAVG.cls
public class BatchGameResultDashboardBeanGameAVG implements Database.Batchable<sObject>,Database.Stateful, Schedulable{
       Decimal leftHandTotal=0;
       Decimal rightHandTotal=0;
       Decimal leftTotalMax=0;
       Decimal rightTotalMax=0;
       Integer beanCount=0;
    
       public void execute(SchedulableContext sc) {
        BatchGameResultDashboardBeanGameAVG ResultAVG = new BatchGameResultDashboardBeanGameAVG();
        Database.executeBatch(ResultAVG);
       }
    
       public Database.QueryLocator start(Database.BatchableContext context) {
                return Database.getQueryLocator([SELECT Id,Left_Hand_Average__c,Right_Hand_Average__c FROM Bean_Game__c                                                
        ]);
    }

    public void execute(Database.BatchableContext context, List<Bean_Game__c> beanGames) {   
        for(Bean_Game__c bean : beanGames) {            
            leftHandTotal += bean.Left_Hand_Average__c;
            rightHandTotal += bean.Right_Hand_Average__c;
            leftTotalMax = bean.Left_Hand_Average__c > leftTotalMax ? bean.Left_Hand_Average__c : leftTotalMax; 
            rightTotalMax = bean.Right_Hand_Average__c > rightTotalMax ? bean.Right_Hand_Average__c : rightTotalMax; 
            beanCount++;
        }        
   }

    public void finish(Database.BatchableContext context) {
     	
        Decimal  overallLeftTime = (leftHandTotal)/beanCount;
        Decimal  overallRightTime = (rightHandTotal)/beanCount;
        
    	List<Participant_Dashboard__c> gameStatsToUpdate=[SELECT Data_Name__c,Data_Value__c,Game_Detail__r.Name FROM Participant_Dashboard__c
                                                         WHERE Game_Detail__r.Name ='Bean Game'];
        for(Participant_Dashboard__c gameOverAvg: gameStatsToUpdate){
            if(gameOverAvg.Data_Name__c=='Overall Average Right Hand'){
                gameOverAvg.Data_Value__c = overallRightTime;
            }
            if(gameOverAvg.Data_Name__c=='Overall Average Left Hand'){
                gameOverAvg.Data_Value__c = overallLeftTime;
            }
                                                              
         }
   
        Game_Detail__c beanGame=[SELECT Max_Score__c,Max_Score_2__c FROM Game_Detail__c WHERE name='Bean Game'];
        beanGame.Max_Score__c = leftTotalMax;
        beanGame.Max_Score_2__c = rightTotalMax;
        
		update gameStatsToUpdate; 
        update beanGame;
    }
 
}