objects/Community_Info__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This settings is to store dynamic values used for community user creation by automated process.</description>
    <fields>
        <fullName>Log_Exception__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If this check box is checked only then exception will log in Exception_Log__c else not.</description>
        <inlineHelpText>Check it if need to log exception in system.</inlineHelpText>
        <label>Log Exception</label>
        <type>Checkbox</type>
    </fields>
    <label>Community Info</label>
</CustomObject>

classes/ExceptionLogHandler_Test.cls
/*Created By: {Girikon(Pramod)} [Jira# TM-1395]
Created On: 29/07/2022
Description/Purpose: Test Class for ExceptionLogHandler
Coverage: 100%

Modification log --
Modified By: {####(####)} [Jira #]
Modified On: MM/DD/YYYY*/
@isTest
public class ExceptionLogHandler_Test
{ 
    @isTest
    public static void test1()
    {
        try
        {
            Community_Info__c setting = new Community_Info__c();
            setting.Name = 'Community Settings';
            setting.Log_Exception__c= true;
            insert setting; 
            
            integer i = 1/0;    
        }
        catch(exception ex)
        {
            ExceptionLogHandler.LogException(ex,'','','');
        }
    }
}