objects/Community_Info__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This settings is to store dynamic values used for community user creation by automated process.</description>
    <fields>
        <fullName>Log_Exception__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If this check box is checked only then exception will log in Exception_Log__c else not.</description>
        <inlineHelpText>Check it if need to log exception in system.</inlineHelpText>
        <label>Log Exception</label>
        <type>Checkbox</type>
    </fields>
    <label>Community Info</label>
</CustomObject>

objects/Exception_Log__c.object
<CustomObject>
    <description>Object to log exception somewhere in our defined system.</description>
    <fields>
        <fullName>Class__c</fullName>
        <description>To contain apex class name  where error logged.</description>
        <inlineHelpText>Apex class name where error logged.</inlineHelpText>
        <label>Class</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>To contain error full information i.e. stacktrace.</description>
        <inlineHelpText>Error complete details</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <description>To contain apex class method where error logged.</description>
        <inlineHelpText>Apex method name where error logged.</inlineHelpText>
        <label>Method</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>EL-{0000000000}</displayFormat>
        <label>Exception Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ExceptionLogHandler.cls
/*Created By: {Girikon(Pramod)} [Jira# TM-1395]
Created On: 29/07/2022
Description/Purpose: To capture exception log and make an entry in Databse.
Methods: logException
Test Class: ExceptionLogHandler_Test

Modification log --
Modified By: {####(####)} [Jira #]
Modified On: MM/DD/YYYY*/
public  class ExceptionLogHandler
{     
    //Save exception log 
    public static void logException(Exception ex,String className, String methodName, String description)
    {
        //Use following code to get various info from execption object
        if(ex!=null)
        {
            description = ex.getMessage() ;
            String stackTrace = ex.getStackTraceString().substringBefore('\n');
            className = stackTrace.substringAfter('.').substringBefore('.'); 
            methodName = stackTrace.substringBefore(':').substringAfter(className).substringAfter('.');    
        }                
        
        Community_Info__c mc = Community_Info__c.getValues('Community Settings');
        //Check whether we have to log exception or not
        if(mc!=null && mc.Log_Exception__c)
        {
            //Create instance of "Exception Log" object
            Exception_Log__c log = new Exception_Log__c();
            log.Class__c = className;
            log.Method__c = methodName;
            log.Description__c = description;
            //Create log in db
            Insert log;            
        }

    }
}