objects/Community_Info__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This settings is to store dynamic values used for community user creation by automated process.</description>
    <fields>
        <fullName>Games_Reactivation_Days__c</fullName>
        <description>It is used to set the number of days in which games can be reactivated.</description>
        <label>Games Reactivation Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Community Info</label>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Deary_Simple_And_Complex_Reaction_Time__c</fullName>
        <label>Deary Simple And Complex Reaction Time</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Verbal_Paired_Associates__c</fullName>
        <label>Verbal Paired Associates</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Game_Detail__c.object
<CustomObject>
    <description>This object is having game information and dependency for other game.</description>
    <label>Game Detail</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Game Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Participant_Game_Info__c.object
<CustomObject>
    <description>This object is having details of the participant&apos;s game.</description>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to contact, saving contact id, will show contact name at front-end.</description>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Participant Game Infos</relationshipLabel>
        <relationshipName>Participant_Game_Infos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Game_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to game, saving game id, will show game name at front-end.</description>
        <label>Game Name</label>
        <referenceTo>Game_Detail__c</referenceTo>
        <relationshipLabel>Participant Game Infos</relationshipLabel>
        <relationshipName>Participant_Game_Infos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Game_Play_Status__c</fullName>
        <label>Game Play Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not-Completed</fullName>
                    <default>true</default>
                    <label>Not-Completed</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Participant Game Info</label>
    <nameField>
        <displayFormat>PGI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Game Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ScheduleBatchOfGames.cls
// Created By: {Girikon(Shweta Khunteta)}
// Created On: 07/09/2021(DD/MM/YYYY
// Description/Purpose: [TM-185]-USED TO schedule Batch class(BatchOfGames)
// Methods: {Methods name in class}
// Test Class: {ScheduleBatchOfGamesTest} {88%}

global class ScheduleBatchOfGames implements Schedulable{
    
@ReadOnly 
 
global void execute (SchedulableContext ctx){ 
// List<AggregateResult> query = [SELECT MAX(CreatedDate) createddate,Game_Name__c gm,Contact_Name__c cnid 
//                               from Participant_Game_Info__c 
//                               where (createddate.addDays(2) < TODAY) AND  Game_Name__r.Name IN ('Deary Simple And Complex Reaction Time','Verbal Paired Associates')
                             
//                               AND (Contact_Name__r.Verbal_Paired_Associates__c ='Completed' OR Contact_Name__r.Deary_Simple_And_Complex_Reaction_Time__c='Completed') 
//                               GROUP BY Game_Name__c, Contact_Name__c]; 
// Map<String, Community_Info__c> mcs = Community_Info__c.getAll();
// Community_Info__c mc= new Community_Info__c() ;
//     if(mcs!=null && mcs.ContainsKey('Community Settings'))
//     { 
//        mc= mcs.get('Community Settings');
      
    
//     }
//     Integer activationdays=Integer.valueOf(mc.Games_Reactivation_Days__c);
    

//List<AggregateResult> query =[SELECT MAX(CreatedDate) createddate,Game_Name__c gm,Contact_Name__c cnid 
//                            from Participant_Game_Info__c 
//where unlock_game__c = true AND Game_Play_Status__c ='Completed' GROUP BY Game_Name__c, Contact_Name__c];  
                            
 

BatchOfGames bg = new BatchOfGames(); 
Database.executeBatch(bg); 
} 

}