objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Deary_Simple_And_Complex_Reaction_Time__c</fullName>
        <label>Deary Simple And Complex Reaction Time</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Face_Name_Associates__c</fullName>
        <label>Face-Name Associates</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Flanker__c</fullName>
        <label>Flanker</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Keep_Track__c</fullName>
        <label>Keep Track</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Letter_Number_Sequencing__c</fullName>
        <label>Letter-Number Sequencing</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_Discrimination__c</fullName>
        <label>Object Discrimination</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_Recognition_And_Similarity__c</fullName>
        <label>Object Recognition And Similarity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_Spatial__c</fullName>
        <label>Object Spatial</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_Temporal__c</fullName>
        <label>Object Temporal</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Verbal_Paired_Associates__c</fullName>
        <label>Verbal Paired Associates</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Game_Detail__c.object
<CustomObject>
    <description>This object is having game information and dependency for other game.</description>
    <fields>
        <fullName>Dependency__c</fullName>
        <label>Dependency</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Verbal Paired Associates</fullName>
                </value>
                <value>
                    <fullName>Deary Simple And Complex Reaction Time</fullName>
                </value>
                <value>
                    <fullName>Object Recognition And Similarity</fullName>
                </value>
                <value>
                    <fullName>Flanker</fullName>
                </value>
                <value>
                    <fullName>Face-Name Associates</fullName>
                </value>
                <value>
                    <fullName>Letter-Number Sequencing</fullName>
                </value>
                <value>
                    <fullName>Keep Track</fullName>
                </value>
                <value>
                    <fullName>Object Discrimination</fullName>
                </value>
                <value>
                    <fullName>Object Temporal</fullName>
                </value>
                <value>
                    <fullName>Object Spatial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reactivation_Days__c</fullName>
        <description>After how many days, game will be re-activated for a user.</description>
        <label>Reactivation Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Game Detail</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Game Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Participant_Game_Info__c.object
<CustomObject>
    <description>This object is having details of the participant&apos;s game.</description>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to contact, saving contact id, will show contact name at front-end.</description>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Participant Game Infos</relationshipLabel>
        <relationshipName>Participant_Game_Infos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Game_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to game, saving game id, will show game name at front-end.</description>
        <label>Game Name</label>
        <referenceTo>Game_Detail__c</referenceTo>
        <relationshipLabel>Participant Game Infos</relationshipLabel>
        <relationshipName>Participant_Game_Infos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Game_Play_Status__c</fullName>
        <label>Game Play Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not-Completed</fullName>
                    <default>true</default>
                    <label>Not-Completed</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Participant Game Info</label>
    <nameField>
        <displayFormat>PGI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Game Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GamesPageDependencyControllerTest.cls
@isTest public class GamesPageDependencyControllerTest {
    public static testMethod void gamesPageDependencyTest() {
        Contact con=new Contact(); 
            con.Object_Discrimination__c='Locked';
            con.Keep_Track__c='Locked';
            con.Letter_Number_Sequencing__c='Locked'; 
            con.Face_Name_Associates__c='Locked';
            con.Flanker__c='Opened';
            con.Object_Recognition_And_Similarity__c='Locked'; 
            con.Verbal_Paired_Associates__c='Locked';
            con.Deary_Simple_And_Complex_Reaction_Time__c='Locked';
            con.Object_Temporal__c='Locked';
            con.Object_Spatial__c='Locked';
            con.LastName='xyz';
        insert con;
        
        Game_Detail__c game1=new Game_Detail__c(Name='Deary Simple And Complex Reaction Time',Reactivation_Days__c=10,Dependency__c='');
        insert game1;
        Game_Detail__c game2=new Game_Detail__c(Name='Verbal Paired Associates',Reactivation_Days__c=10,Dependency__c='');
            insert game2;
        Game_Detail__c game3=new Game_Detail__c(Name='Object Recognition And Similarity',Reactivation_Days__c=10,Dependency__c='');
            insert game3;
        Game_Detail__c game4=new Game_Detail__c(Name='Flanker',Reactivation_Days__c=10,Dependency__c='Object Recognition And Similarity');
            insert game4;
        Game_Detail__c game5=new Game_Detail__c(Name='Face-Name Associates',Reactivation_Days__c=10,Dependency__c='Object Recognition And Similarity');
            insert game5;
        Game_Detail__c game6=new Game_Detail__c(Name='Letter-Number Sequencing',Reactivation_Days__c=10,Dependency__c='Object Recognition And Similarity');
            insert game6;
        Game_Detail__c game7=new Game_Detail__c(Name='Keep Track',Reactivation_Days__c=10,Dependency__c='Object Recognition And Similarity');
            insert game7;
        Game_Detail__c game8=new Game_Detail__c(Name='Object Discrimination',Reactivation_Days__c=10,Dependency__c='Object Recognition And Similarity');
            insert game8;
         Game_Detail__c game9=new Game_Detail__c(Name='Object Temporal',Reactivation_Days__c=10,Dependency__c='Object Recognition And Similarity');
            insert game9;
         Game_Detail__c game10=new Game_Detail__c(Name='Object Spatial',Reactivation_Days__c=10,Dependency__c='Object Recognition And Similarity');
            insert game10;
         
        Participant_Game_Info__c pGameInfo1 = new  Participant_Game_Info__c(Contact_Name__c=con.id,Game_Name__c=game1.id);
            insert pGameInfo1;
        Participant_Game_Info__c pGameInfo2 = new  Participant_Game_Info__c(Contact_Name__c=con.id,Game_Name__c=game2.id);
            insert pGameInfo2;
        Participant_Game_Info__c pGameInfo3 = new  Participant_Game_Info__c(Contact_Name__c=con.id,Game_Name__c=game3.id);
            insert pGameInfo3;
            Participant_Game_Info__c pGameInfo4 = new  Participant_Game_Info__c(Contact_Name__c=con.id,Game_Name__c=game4.id);
            insert pGameInfo4;
            Participant_Game_Info__c pGameInfo5 = new  Participant_Game_Info__c(Contact_Name__c=con.id,Game_Name__c=game5.id);
            insert pGameInfo5;
            Participant_Game_Info__c pGameInfo6 = new  Participant_Game_Info__c(Contact_Name__c=con.id,Game_Name__c=game6.id);
            insert pGameInfo6;
            Participant_Game_Info__c pGameInfo7 = new  Participant_Game_Info__c(Contact_Name__c=con.id,Game_Name__c=game7.id);
            insert pGameInfo7;
            Participant_Game_Info__c pGameInfo8 = new  Participant_Game_Info__c(Contact_Name__c=con.id,Game_Name__c=game8.id);
            insert pGameInfo8;
        
        String data4='{"Contact_Name__c":"'+con.id+'", "Game_Name__c":"'+pGameInfo3.Game_Name__c+'","Game_Play_Status__c":"Not Completed"}';
        String data5='{"Contact_Name__c":"'+con.id+'", "Game_Name__c":"'+pGameInfo2.Game_Name__c+'","Game_Play_Status__c":"Not Completed"}';
        String data6='{"Contact_Name__c":"'+con.id+'", "Game_Name__c":"'+pGameInfo1.Game_Name__c+'","Game_Play_Status__c":"Not Completed"}';
        String data7='{"Contact_Name__c":"'+con.id+'", "Game_Name__c":"'+pGameInfo4.Game_Name__c+'","Game_Play_Status__c":"Not Completed"}';
        String data8='{"Contact_Name__c":"'+con.id+'", "Game_Name__c":"'+pGameInfo5.Game_Name__c+'","Game_Play_Status__c":"Not Completed"}';
        String data9='{"Contact_Name__c":"'+con.id+'", "Game_Name__c":"'+pGameInfo6.Game_Name__c+'","Game_Play_Status__c":"Not Completed"}';
        String data10='{"Contact_Name__c":"'+con.id+'", "Game_Name__c":"'+pGameInfo7.Game_Name__c+'","Game_Play_Status__c":"Not Completed"}';
        String data11='{"Contact_Name__c":"'+con.id+'", "Game_Name__c":"'+pGameInfo8.Game_Name__c+'","Game_Play_Status__c":"Not Completed"}';
 
        Test.startTest();
        GamesPageDependencyController.triggerForUpdateContactGamesField(data4);
         GamesPageDependencyController.triggerForUpdateContactGamesField(data5);
         GamesPageDependencyController.triggerForUpdateContactGamesField(data6);
         GamesPageDependencyController.triggerForUpdateContactGamesField(data7);
         GamesPageDependencyController.triggerForUpdateContactGamesField(data8);
         GamesPageDependencyController.triggerForUpdateContactGamesField(data9);
         GamesPageDependencyController.triggerForUpdateContactGamesField(data10);
         GamesPageDependencyController.triggerForUpdateContactGamesField(data11);
        Test.stopTest();
    }
}