objects/Contact.object
<CustomObject>
    <fields>
        <fullName>HEALTH_MEDICAL__c</fullName>
        <label>HEALTH MEDICAL</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SES__c</fullName>
        <label>SES</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sex__c</fullName>
        <description>Test-taker&apos;s biological sex</description>
        <label>Sex</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Intersex</fullName>
                </value>
                <value>
                    <fullName>Prefer not to answer</fullName>
                    <isActive>false</isActive>
                    <label>Prefer not to answer</label>
                </value>
                <value>
                    <fullName>unknown</fullName>
                    <isActive>false</isActive>
                    <label>unknown</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/HealthMedical_Survey__c.object
<CustomObject>
    <description>created for Marketing cloud survey</description>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>HMs</relationshipLabel>
        <relationshipName>HealthMedical_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>HM</label>
    <nameField>
        <displayFormat>HM-{0000000000}</displayFormat>
        <label>HM Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SES__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>SESs</relationshipLabel>
        <relationshipName>SESs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SES</label>
    <nameField>
        <displayFormat>SES-{0000000000}</displayFormat>
        <label>SES Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SESs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BatchSurveyStatusUpdateTest.cls
/*
@author            : Santhosh Nookilla
@description       : Test Class for Unlocking Surveys
@class        	   : BatchSurveyStatusUpdate
*/

@isTest
public class BatchSurveyStatusUpdateTest {

    @testSetup
    static void createTestData() {
        
        List<Contact> contacts = new List<Contact>();
        List<HealthMedical_Survey__c> hmSurveys = new List<HealthMedical_Survey__c>();
        List<SES__c> sesSurveys = new List<SES__c>();
    
        Datetime oneYearAgo = Datetime.now().addDays(-365);
    
        for (Integer i = 1; i < 3; i++) {
    
            Contact contact = new Contact(
                LastName = 'Test Contact ' + i,
                Sex__c = 'Male',
                HEALTH_MEDICAL__c = 'Locked',
                SES__c = 'Locked'
            );
            insert contact; 
            
    
            HealthMedical_Survey__c hmSurvey = new HealthMedical_Survey__c(
                Contact_Name__c = contact.Id,
                CreatedDate = oneYearAgo
            );
            hmSurveys.add(hmSurvey);
    
            SES__c sesSurvey = new SES__c(
                Contact_Name__c = contact.Id,
                CreatedDate = oneYearAgo
            );
            sesSurveys.add(sesSurvey);
    
            contacts.add(contact);
        }
    
        system.debug('Contacts: ' + contacts);
        system.debug('HealthMedical_Surveys: ' + hmSurveys);
        system.debug('SES_Surveys: ' + sesSurveys);
    
        insert hmSurveys;
        insert sesSurveys;
    }


    @isTest
    static void testBatchExecute_SESSurvey() {
        Test.startTest();
    
        
        Datetime currentTime = Datetime.now();
        
        
        Integer minutesFromNow = 1; 
        Datetime scheduledTime = currentTime.addMinutes(minutesFromNow);
    
        
        String cronExpression = scheduledTime.second() + ' ' +
                                scheduledTime.minute() + ' ' +
                                scheduledTime.hour() + ' ' +
                                scheduledTime.day() + ' ' +
                                scheduledTime.month() + ' ' +
                                '?' + ' ' +
                                scheduledTime.year();
    
        
        String jobId = System.schedule('Test Batch Job', cronExpression, new BatchSurveyStatusUpdate('SES__c', 'Contact_Name__c', 'SES__c'));
 
        
        List<Contact> updatedContacts = [SELECT Id, SES__c FROM Contact WHERE Id IN (SELECT Contact_Name__c FROM SES__c)];
        System.assertEquals(2, updatedContacts.size());
    
        Test.stopTest();
    }
}