objects/Contact.object
<CustomObject>
    <fields>
        <fullName>First_degree_family_history_of_AD__c</fullName>
        <description>Is test-taker&apos;s brother or  sister diagnosed with alzheimer ever in past?</description>
        <label>First-degree family history of AD</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>I don’t know</fullName>
                </value>
                <value>
                    <fullName>I prefer not to answer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_degree_family_history_of_EO_AD__c</fullName>
        <description>Is Sibling  or parent diagnosed with alzhemer before age of 55?</description>
        <label>First-degree family history of EO-AD</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>I don’t know</fullName>
                </value>
                <value>
                    <fullName>I prefer not to answer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Health_Lifestyle_and_Medical__c</fullName>
        <label>Health, Lifestyle, and Medical</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Alzheimer’s Disease</fullName>
                </value>
                <value>
                    <fullName>Brain Disease</fullName>
                </value>
                <value>
                    <fullName>Cancer</fullName>
                </value>
                <value>
                    <fullName>Chronic Stress</fullName>
                </value>
                <value>
                    <fullName>Depression or Anxiety</fullName>
                </value>
                <value>
                    <fullName>Heart Disease</fullName>
                </value>
                <value>
                    <fullName>High Blood Pressure</fullName>
                </value>
                <value>
                    <fullName>Loss of Consciousness</fullName>
                    <label>Loss of Consciousness (more than 10 minutes)</label>
                </value>
                <value>
                    <fullName>Memory Problems</fullName>
                </value>
                <value>
                    <fullName>Parkinson’s Disease</fullName>
                </value>
                <value>
                    <fullName>Seizures</fullName>
                </value>
                <value>
                    <fullName>Sleep Problems</fullName>
                </value>
                <value>
                    <fullName>Smoker</fullName>
                </value>
                <value>
                    <fullName>Stroke</fullName>
                </value>
                <value>
                    <fullName>Type 1 Diabetes</fullName>
                </value>
                <value>
                    <fullName>Type 2 Diabetes</fullName>
                </value>
                <value>
                    <fullName>None of these Conditions Apply to Me</fullName>
                </value>
                <value>
                    <fullName>Alcohol/Drug Abuse</fullName>
                    <isActive>false</isActive>
                    <label>Alcohol/Drug Abuse</label>
                </value>
                <value>
                    <fullName>Brain Disease and/or Memory Problems</fullName>
                    <isActive>false</isActive>
                    <label>Brain Disease and/or Memory Problems</label>
                </value>
                <value>
                    <fullName>Depression or Anxiety,</fullName>
                    <isActive>false</isActive>
                    <label>Depression or Anxiety,</label>
                </value>
                <value>
                    <fullName>Diabetes</fullName>
                    <isActive>false</isActive>
                    <label>Diabetes</label>
                </value>
                <value>
                    <fullName>Dizzy Spells</fullName>
                    <isActive>false</isActive>
                    <label>Dizzy Spells</label>
                </value>
                <value>
                    <fullName>Smoking</fullName>
                    <isActive>false</isActive>
                    <label>Smoking</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Highest_level_of_education_completed__c</fullName>
        <description>Highest academic qualification of test-taker</description>
        <label>Highest level of education completed</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Up to 8 Years</fullName>
                </value>
                <value>
                    <fullName>Completed 8th Grade (Elementary or Primary School Graduate)</fullName>
                </value>
                <value>
                    <fullName>Some High School</fullName>
                </value>
                <value>
                    <fullName>High School Diploma (Baccalaureate)</fullName>
                </value>
                <value>
                    <fullName>Some College (Some University)</fullName>
                </value>
                <value>
                    <fullName>College Degree (University Graduate)</fullName>
                </value>
                <value>
                    <fullName>Post Graduate Degree (Masters or Doctorate)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Second_degree_family_history_of_AD__c</fullName>
        <description>(Grandparents, grandchildren, aunts, uncles, nephews, nieces, or half-siblings) Say yes if any diagnosed with alzheimer in past</description>
        <label>Second-degree family history of AD</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>I don’t know</fullName>
                </value>
                <value>
                    <fullName>I prefer not to answer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sex__c</fullName>
        <description>Test-taker&apos;s biological sex</description>
        <label>Sex</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Intersex</fullName>
                </value>
                <value>
                    <fullName>Prefer not to answer</fullName>
                    <isActive>false</isActive>
                    <label>Prefer not to answer</label>
                </value>
                <value>
                    <fullName>unknown</fullName>
                    <isActive>false</isActive>
                    <label>unknown</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CustomLoginControllerTest.cls
@isTest
public class CustomLoginControllerTest {
@isTest
    public static void LoginTest(){
        
        Id p = [select id from profile where name='Customer Community Login User Custom'].id;
        
        Account testAccount = new Account();
        testAccount.Name='Test Account' ;
        insert testAccount;

        contact con1= new contact();
        con1.FirstName='Test';
        con1.Email='test@abc.com';
        con1.Phone='76955';
        con1.LastName='Test';
        con1.Highest_level_of_education_completed__c='Up to 8 Years';
        con1.AccountId=testAccount.id;
        con1.sex__c='Male';
        insert con1;
        
        User user = new User(alias = 'test123', email='test123@noemail.com',
                    emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                    localesidkey='en_US', profileid = p, country='United States',IsActive =true,
                    ContactId = con1.Id,
                    timezonesidkey='America/Los_Angeles', username='tester@noemail.com');
       // User ur=new user(Username='sun@gmail.com.dev',firstname='sunil',ContactId=con1.id,LastName='singh', Email='sunil@gmail.com', Alias='sunsingh', TimeZoneSidKey='America/Los_Angeles', LocaleSidKey='en_US', EmailEncodingKey='UTF-8', ProfileId='00e01000000QLFDAA4', LanguageLocaleKey='en_US',UserRoleID='00E5e000000LgdKEAS');
        insert user;
        test.startTest();
       // CustomLoginController controller = new CustomLoginController();
        CustomLoginController.changePassword('xyz','xyz','xyzy');
        CustomLoginController.getFeedItem();
        CustomLoginController.getCurrentUser();
        CustomLoginController.getCurrentProfile();
         system.runAs(user) {
             CustomLoginController.getCurrentContact(); 
             RountingController rc = new RountingController();
            String url = rc.RountingPath();
        }    
        test.stopTest();
    }
       @isTest  
    public static void updatecon()
    {       
        contact conup= new contact();
         conup.LastName='Test Last Name';
        conup.Health_Lifestyle_and_Medical__c='Smoker';
        conup.First_degree_family_history_of_AD__c='Yes';
        conup.First_degree_family_history_of_EO_AD__c='Yes';
        conup.Second_degree_family_history_of_AD__c='Yes';    
        insert conup;
        
        Test.startTest();        
        contact conup1=[SELECT Id,Health_Lifestyle_and_Medical__c,First_degree_family_history_of_AD__c
        FROM Contact where Contact.Id =:conup.Id];
       
        CustomLoginController.upsertContact1(conup1);
        
        update conup;
        System.assertEquals('Smoker', conup.Health_Lifestyle_and_Medical__c);
        Test.stopTest(); 
    }
    
    @isTest  
    public static void restrictExpandedGamesTest()
    {       
			System.assert(!CustomLoginController.restrictExpandedGames('670674'), 'Success');
    }
    
}