objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Deary_Simple_And_Complex_Reaction_Time__c</fullName>
        <label>Deary Simple And Complex Reaction Time</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Digits__c</fullName>
        <label>Digits</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Face_Name_Associates__c</fullName>
        <label>Face-Name Associates</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fake_News__c</fullName>
        <label>Fake News</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Flanker__c</fullName>
        <label>Flanker</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Highest_level_of_education_completed__c</fullName>
        <description>Highest academic qualification of test-taker</description>
        <label>Highest level of education completed</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Up to 8 Years</fullName>
                </value>
                <value>
                    <fullName>Completed 8th Grade (Elementary or Primary School Graduate)</fullName>
                </value>
                <value>
                    <fullName>Some High School</fullName>
                </value>
                <value>
                    <fullName>High School Diploma (Baccalaureate)</fullName>
                </value>
                <value>
                    <fullName>Some College (Some University)</fullName>
                </value>
                <value>
                    <fullName>College Degree (University Graduate)</fullName>
                </value>
                <value>
                    <fullName>Post Graduate Degree (Masters or Doctorate)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Keep_Track__c</fullName>
        <label>Keep Track</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>Language selected by test-taker at public application.</description>
        <inlineHelpText>If you are multi-lingual you may want to select the language that you are most fluent in</inlineHelpText>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                </value>
                <value>
                    <fullName>Español</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Letter_Number_Sequencing__c</fullName>
        <label>Letter-Number Sequencing</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_Discrimination__c</fullName>
        <label>Object Discrimination</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_Recognition_And_Similarity__c</fullName>
        <label>Object Recognition And Similarity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_Spatial__c</fullName>
        <label>Object Spatial</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_Temporal__c</fullName>
        <label>Object Temporal</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project2_Enrollment_Date__c</fullName>
        <label>Project2 Enrollment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sex__c</fullName>
        <description>Test-taker&apos;s biological sex</description>
        <label>Sex</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Intersex</fullName>
                </value>
                <value>
                    <fullName>Prefer not to answer</fullName>
                    <isActive>false</isActive>
                    <label>Prefer not to answer</label>
                </value>
                <value>
                    <fullName>unknown</fullName>
                    <isActive>false</isActive>
                    <label>unknown</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tell_Me_More__c</fullName>
        <label>Tell Me More</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tell_Me__c</fullName>
        <label>Tell Me</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>This_That__c</fullName>
        <label>This and That</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Verbal_Paired_Associates__c</fullName>
        <label>Verbal Paired Associates</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Participant_Game_Info__c.object
<CustomObject>
    <description>This object is having details of the participant&apos;s game.</description>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to contact, saving contact id, will show contact name at front-end.</description>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Participant Game Infos</relationshipLabel>
        <relationshipName>Participant_Game_Infos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>test language get from consent page. ( Language selected by test-taker at public application.)</description>
        <label>Language</label>
        <length>56</length>
        <type>Text</type>
    </fields>
    <label>Participant Game Info</label>
    <nameField>
        <displayFormat>PGI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Game Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BatchContactGameStatusUpdateTestTempTest.cls
/*
*
@author            : Santhosh Nookilla
@description       : Test Class for Unlocking Games
@class        	   : BatchContactGameStatusUpdateTest
*  
*/
 
@isTest
public class BatchContactGameStatusUpdateTestTempTest {
    @testSetup
	static void createTestData() {
    List<Contact> contacts = new List<Contact>();
    List<Game_Detail__c> gameDetails = new List<Game_Detail__c>();
    List<Participant_Game_Info__c> participantGameInfos = new List<Participant_Game_Info__c>();
    List<Participant_Game_Response__c> participantGameResponses = new List<Participant_Game_Response__c>();

    Datetime oneYearAgo = Datetime.now().addDays(-400);
    Datetime nineMonthsAgo = Datetime.now().addDays(-400);
    Datetime sixMonthsAgo = Datetime.now().addDays(-400);
    Datetime threeMonthsAgo = Datetime.now().addDays(-400);

    for(Integer i = 0; i < 15; i++) {
        Contact c = new Contact();
        c.LastName = 'test contact' + i;
        c.Email = 'Test' + i + '@test.com'; 
        c.Sex__c = 'Male';
        c.Age__c = 34;
        c.Highest_level_of_education_completed__c = 'High School Diploma (Baccalaureate)';
        c.Language__c='Español';
        c.Flanker__c = 'Completed';
        c.Verbal_Paired_Associates__c = 'Completed';
        c.Letter_Number_Sequencing__c = 'Completed';
        c.Deary_Simple_And_Complex_Reaction_Time__c = 'Completed';
        c.Keep_Track__c = 'Completed';
        c.Object_Recognition_And_Similarity__c = 'Completed';
        c.Object_Discrimination__c = 'Completed';
        c.Object_Temporal__c = 'Completed';
        c.Face_Name_Associates__c = 'Completed';
        c.Object_Spatial__c = 'Completed';
        c.Fake_News__c = 'Completed';
        c.Digits__c = 'Completed';
        c.This_That__c= 'Completed';
        c.Tell_Me__c = 'Completed';
        c.Tell_Me_More__c = 'Completed';
        c.Project2_Enrollment_Date__c = null;
        contacts.add(c);
    }
    insert contacts;

    List<String> gameNames = new List<String>{'Flanker', 'Letter-Number Sequencing', 'Keep Track', 'Deary Simple And Complex Reaction Time',
        									 	'Object Discrimination', 'Object Temporal', 'Face-Name Associates', 'Object Spatial', 'Digits', 
        										'This & That', 'Verbal Paired Associates', 'Object Recognition And Similarity', 'Fake News', 
        										'Tell Me', 'Tell Me More' };
    for(String name : gameNames) {
        Game_Detail__c gd = new Game_Detail__c();
        gd.Name = name;
        gameDetails.add(gd);
    }
    insert gameDetails;

    for(Integer i = 0; i < 15; i++) {
        Participant_Game_Info__c pgi = new Participant_Game_Info__c();
        pgi.Contact_Name__c = contacts[i].Id;
        pgi.Game_Name__c = gameDetails[i].Id;
        pgi.Game_Play_Status__c = 'Completed';
        if (i < 4) {
            pgi.CreatedDate = threeMonthsAgo;
        } else if (i >= 4 && i < 9) {
            pgi.CreatedDate = sixMonthsAgo;
        } else if (i == 9) {
            pgi.CreatedDate = nineMonthsAgo;            
        } else {
            pgi.CreatedDate = oneYearAgo;
        }
        
        participantGameInfos.add(pgi);
    }
    insert participantGameInfos;

    for(Integer i = 0; i < 13; i++) {
        Participant_Game_Response__c pgr = new Participant_Game_Response__c();
        pgr.Contact_Name__c = contacts[i].Id; 
        pgr.Game_Name__c = gameDetails[i].Id; 
        pgr.Reaction_Time_in_ms__c = 5000; 
        pgr.Is_Correct__c = true; 
        pgr.Is_Practice_Question__c = false;  
        pgr.Participant_Game_InfoID__c = participantGameInfos[i].Id; 
        pgr.Participant_Response__c = 'Test'; 
        pgr.Question_Number__c = '1'; 
        pgr.Right_Answer__c = 'Test'; 
        participantGameResponses.add(pgr);
    }
    insert participantGameResponses;

    for(Integer i = 0; i < 3; i++) {
        system.debug('Contact ' + i + ': ' + contacts[i]);
        system.debug('PGI ' + i + ': ' + participantGameInfos[i]);
        system.debug('PGR ' + i + ': ' + participantGameResponses[i]);        
    }
                List<Participant_Game_Info__c> pgiList = [Select id, Game_Name__r.Name,Contact_Name__r.Id, Contact_Name__c, Game_Name__c
										FROM Participant_Game_Info__c 
										WHERE
										((Game_Name__r.Name IN ('Flanker', 'Letter-Number Sequencing', 'Keep Track', 'Deary Simple And Complex Reaction Time')
													AND CreatedDate < N_DAYS_AGO:99)
										OR (Game_Name__r.Name IN ('Object Discrimination', 'Object Temporal', 'Face-Name Associates', 'Object Spatial') 
													AND CreatedDate < N_DAYS_AGO:191)
										OR (Game_Name__r.Name IN ('Verbal Paired Associates', 'Object Recognition And Similarity') 
													AND CreatedDate < N_DAYS_AGO:373))
													AND Contact_Name__r.Project2_Enrollment_Date__c = null
                                         			and Language__c='Español'
                                                    ];

       system.debug('Total PGI :'+pgiList.size() );
}

        
        @isTest
    	private static void testBatchClass() {     
        Test.startTest();
    
        
        Datetime currentTime = Datetime.now();
        
        
        Integer minutesFromNow = 1; 
        Datetime scheduledTime = currentTime.addMinutes(minutesFromNow);
    
        
        String cronExpression = scheduledTime.second() + ' ' +
                                scheduledTime.minute() + ' ' +
                                scheduledTime.hour() + ' ' +
                                scheduledTime.day() + ' ' +
                                scheduledTime.month() + ' ' +
                                '?' + ' ' +
                                scheduledTime.year();
    
        
        String jobId = System.schedule('Test Batch Job', cronExpression, new BatchContactGameStatusUpdateTemp());
 
        
        List<Contact> updatedContacts = [SELECT Id, Flanker__c, Letter_Number_Sequencing__c, Keep_Track__c, Deary_Simple_And_Complex_Reaction_Time__c,
                                        Object_Discrimination__c, Object_Temporal__c, Face_Name_Associates__c, Object_Spatial__c, Digits__c,This_That__c,
                                        Verbal_Paired_Associates__c, Object_Recognition_And_Similarity__c, Fake_News__c, Tell_Me__c, Tell_Me_More__c FROM Contact];
        System.assertEquals(15, updatedContacts.size());
    
        Test.stopTest();
}
}