objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Deary_Simple_And_Complex_Reaction_Time__c</fullName>
        <label>Deary Simple And Complex Reaction Time</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Verbal_Paired_Associates__c</fullName>
        <label>Verbal Paired Associates</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Game_Detail__c.object
<CustomObject>
    <description>This object is having game information and dependency for other game.</description>
    <label>Game Detail</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Game Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Participant_Game_Info__c.object
<CustomObject>
    <description>This object is having details of the participant&apos;s game.</description>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to contact, saving contact id, will show contact name at front-end.</description>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Participant Game Infos</relationshipLabel>
        <relationshipName>Participant_Game_Infos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Game_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to game, saving game id, will show game name at front-end.</description>
        <label>Game Name</label>
        <referenceTo>Game_Detail__c</referenceTo>
        <relationshipLabel>Participant Game Infos</relationshipLabel>
        <relationshipName>Participant_Game_Infos</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Participant Game Info</label>
    <nameField>
        <displayFormat>PGI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Game Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ScheduleBatchOfGamesTest.cls
// Created By: {Girikon(Shweta Khunteta)}
// Created On: 08/09/2021(DD/MM/YYYY)
// Description/Purpose: test class for testing ScheduleBatchOfGames
// Methods: {execute}
// Apex Class: {ScheduleBatchOfGames}

@isTest
public with sharing class ScheduleBatchOfGamesTest 
{
    @testSetup static void setup() 
    {
    
      List<Contact> testContact = new List<Contact>();
      for(integer i = 0; i < 10; i++) 
      {
         Contact c = new Contact(LastName = 'NotFirstName'+i,
         //Email='LastName@gmail.com';
         Verbal_Paired_Associates__c='Completed',
        Deary_Simple_And_Complex_Reaction_Time__c='Completed');
        testContact.add(c);
      }
            insert testContact;
    
      Game_Detail__c game =new Game_Detail__c(Name='Verbal Paired Associates');
      insert game;
      List<Participant_Game_Info__c> pgList = new List<Participant_Game_Info__c>();
      pgList.add(new Participant_Game_Info__c(Contact_Name__c = testContact[0].Id,Game_Name__c=game.Id));
      pgList.add(new Participant_Game_Info__c(Contact_Name__c = testContact[0].Id,Game_Name__c=game.Id));
      insert pgList;
                     
    }
    public static testMethod void gameBatchtest()
    {
        Test.startTest();
        ScheduleBatchOfGames schedulebatchgame= new ScheduleBatchOfGames();
        String sch='0 0 0 ? * * *';
        System.schedule('Check scheduled status of games', sch, schedulebatchgame);
        Test.stopTest();
    }

}