objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Deary_Simple_And_Complex_Reaction_Time__c</fullName>
        <label>Deary Simple And Complex Reaction Time</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Enrolled_in_Paid_Campaign__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enrolled in Paid Campaign</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Face_Name_Associates__c</fullName>
        <label>Face-Name Associates</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Flanker__c</fullName>
        <label>Flanker</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Keep_Track__c</fullName>
        <label>Keep Track</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>Language selected by test-taker at public application.</description>
        <inlineHelpText>If you are multi-lingual you may want to select the language that you are most fluent in</inlineHelpText>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                </value>
                <value>
                    <fullName>Español</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Letter_Number_Sequencing__c</fullName>
        <label>Letter-Number Sequencing</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_Discrimination__c</fullName>
        <label>Object Discrimination</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_Recognition_And_Similarity__c</fullName>
        <label>Object Recognition And Similarity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_Spatial__c</fullName>
        <label>Object Spatial</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_Temporal__c</fullName>
        <label>Object Temporal</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tremendous_Award_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tremendous Award Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Verbal_Paired_Associates__c</fullName>
        <label>Verbal Paired Associates</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TremendousSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>TremendousSettings</label>
    <fields>
        <fullName>AuthToken__c</fullName>
        <label>AuthToken</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Authorization__c</fullName>
        <label>Authorization</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CampaignId__c</fullName>
        <label>CampaignId</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContentType__c</fullName>
        <label>ContentType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CurrencyCode__c</fullName>
        <label>CurrencyCode</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DeliveryMethod__c</fullName>
        <label>DeliveryMethod</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Denomination__c</fullName>
        <label>Denomination</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EndpointURL__c</fullName>
        <label>EndpointURL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FundingSourceId__c</fullName>
        <label>FundingSourceId</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RestMethod__c</fullName>
        <label>RestMethod</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Spanish_CampaignId__c</fullName>
        <label>Spanish CampaignId</label>
        <length>22</length>
        <type>Text</type>
    </fields>
</CustomObject>

classes/SendRewardsToUsersBatch.cls
public class SendRewardsToUsersBatch implements Database.Batchable<SObject>, Schedulable, Database.AllowsCallouts {
    
    public void execute(SchedulableContext sc) {
        SendRewardsToUsersBatch sendReward = new SendRewardsToUsersBatch();
        Database.executeBatch(sendReward, 100);
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([
            SELECT Id, Contact.FirstName, Contact.Email, Language__c
            FROM Contact 
            WHERE Tremendous_Award_Sent__c = False 
            AND Enrolled_in_Paid_Campaign__c = True 
            AND Verbal_Paired_Associates__c = 'Completed' 
            AND Deary_Simple_And_Complex_Reaction_Time__c = 'Completed' 
            AND Object_Recognition_And_Similarity__c = 'Completed' 
            AND Flanker__c = 'Completed' 
            AND Face_Name_Associates__c = 'Completed' 
            AND Letter_Number_Sequencing__c = 'Completed' 
            AND Keep_Track__c = 'Completed' 
            AND Object_Discrimination__c = 'Completed' 
            AND Object_Temporal__c = 'Completed' 
            AND Object_Spatial__c = 'Completed' 
        ]);
    }

    public void execute(Database.BatchableContext bc, List<Contact> cons) {
        try {
            for (Contact con : cons) {
                system.debug('count--->' + cons.size());
                con.Tremendous_Award_Sent__c = true;
                TremendousSetting__c trmAPI = TremendousSetting__c.getValues('RewardsSetting');
                SendRewardRequestWrapper request = new SendRewardRequestWrapper();           
                request.payment = new SendRewardRequestWrapper.Payment();
                request.payment.funding_source_id = trmAPI.FundingSourceId__c;    
                request.rewards = new List<SendRewardRequestWrapper.Rewards>();
                SendRewardRequestWrapper.Rewards reward = new SendRewardRequestWrapper.Rewards();
                reward.value = new SendRewardRequestWrapper.Value();
                reward.value.denomination = trmAPI.Denomination__c;
                reward.value.currency_code = trmAPI.CurrencyCode__c;    
                reward.delivery = new SendRewardRequestWrapper.Delivery();
                reward.delivery.method = trmAPI.DeliveryMethod__c;    
                reward.recipient = new SendRewardRequestWrapper.Recipient();
                reward.recipient.name = con.FirstName;
                reward.recipient.email = con.Email;                   
                if (con.Language__c == 'Español') {
                    reward.campaign_id = trmAPI.Spanish_CampaignId__c;                    
                } else {
                    reward.campaign_id = trmAPI.CampaignId__c;
                } 
                request.rewards.add(reward);
                String payload = JSON.serialize(request);
                system.debug('payload--->' + payload);
                HttpRequest req = new HttpRequest();
                req.setMethod(trmAPI.RestMethod__c);
                req.setEndpoint(trmAPI.EndpointURL__c);
                req.setHeader('Content-Type', trmAPI.ContentType__c);
                req.setHeader('Authorization', trmAPI.Authorization__c+' ' + trmAPI.AuthToken__c);
                req.setBody(payload);
                Http httpHeader = new Http();
                HttpResponse res = new HttpResponse();
                try{
                    res = httpHeader.send(req);
                }
                catch(Exception ex){
                    ExceptionLogHandler.logException(ex, 'SendRewardsToconsBatch', 'Execute', 'Exception in Tremendous API '
                                                     +' Error Message: '+ex.getMessage());
                }                
                system.debug('res--->' + res.getBody());
                system.debug('statuscode--->' + res.getStatusCode());
                if (res.getStatusCode() != 200 && res.getStatusCode() != 202) {
                    String errorDetails = 'API Error - Status Code: ' + res.getStatusCode() + 'Contact Id: ' +con.Id + ', Error Response: ' + res.getBody();
                    ExceptionLogHandler.logException(null, 'SendRewardsToconsBatch', 'ProcessAPIResponse', errorDetails);
                }
            }
            if(cons.size()>0){
                update cons;
            }                
        } 
        catch (Exception ex) {
            ExceptionLogHandler.logException(ex, 'SendRewardsToconsBatch', 'Execute', 'Exception in Tremendous API for Contact '
                                             +' Error Message: '+ex.getMessage());
            if(cons.size()>0){
                update cons;
            }
        }
     }
    
    public void finish(Database.BatchableContext context) {
    }
}