objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Education_Attainment__c</fullName>
        <formula>IF( OR(ISPICKVAL( Highest_level_of_education_completed__c , &apos;Up to 8 Years&apos;), ISPICKVAL( Highest_level_of_education_completed__c , &apos;Completed 8th Grade (Elementary or Primary School Graduate)&apos;), ISPICKVAL( Highest_level_of_education_completed__c , &apos;Some High School&apos;) ) , 1,
 IF(ISPICKVAL( Highest_level_of_education_completed__c , &apos;High School Diploma (Baccalaureate)&apos;), 2,  IF(ISPICKVAL( Highest_level_of_education_completed__c , &apos;Some College (Some University)&apos;), 3,  IF(ISPICKVAL( Highest_level_of_education_completed__c , &apos;College Degree (University Graduate)&apos;), 4,  IF(ISPICKVAL( Highest_level_of_education_completed__c , &apos;Post Graduate Degree (Masters or Doctorate)&apos;), 5, 0) ) ) ) 
 )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Education Attainment</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sex__c</fullName>
        <description>Test-taker&apos;s biological sex</description>
        <label>Sex</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Intersex</fullName>
                </value>
                <value>
                    <fullName>Prefer not to answer</fullName>
                    <isActive>false</isActive>
                    <label>Prefer not to answer</label>
                </value>
                <value>
                    <fullName>unknown</fullName>
                    <isActive>false</isActive>
                    <label>unknown</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Game_Detail__c.object
<CustomObject>
    <description>This object is having game information and dependency for other game.</description>
    <fields>
        <fullName>Max_Score__c</fullName>
        <description>The Maximum Score that participant can Score By Playing the Game</description>
        <inlineHelpText>The Maximum Score that participant can Score By Playing the Game</inlineHelpText>
        <label>Max Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Game Detail</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Game Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Participant_Dashboard__c.object
<CustomObject>
    <fields>
        <fullName>Data_Value__c</fullName>
        <label>Data Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Game_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Game Detail</label>
        <referenceTo>Game_Detail__c</referenceTo>
        <relationshipLabel>Participant Dashboards</relationshipLabel>
        <relationshipName>DashBoard_Datas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Participant Dashboard</label>
    <nameField>
        <label>Participant Dashboard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participant Dashboards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Participant_Game_Info__c.object
<CustomObject>
    <description>This object is having details of the participant&apos;s game.</description>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to contact, saving contact id, will show contact name at front-end.</description>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Participant Game Infos</relationshipLabel>
        <relationshipName>Participant_Game_Infos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Count_Of_No_Of_Correct_Answered__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Count Of No Of Correct Answered</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Count_Of_No_of_Question_Attempted__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Count Of No of Question Attempted</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Count_Of_Total_Reaction_Time__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Count Of Total Reaction Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Game_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to game, saving game id, will show game name at front-end.</description>
        <label>Game Name</label>
        <referenceTo>Game_Detail__c</referenceTo>
        <relationshipLabel>Participant Game Infos</relationshipLabel>
        <relationshipName>Participant_Game_Infos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Game_Play_Status__c</fullName>
        <label>Game Play Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not-Completed</fullName>
                    <default>true</default>
                    <label>Not-Completed</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>No_Of_Correct_Answered__c</fullName>
        <description>Count the correct answers were responded by the participant</description>
        <label>No. Of Correct Answered</label>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Is_Correct__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Is_Practice_Question__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>Participant_Game_Response__c.Participant_Game_InfoID__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>No_of_Question_Attempted__c</fullName>
        <description>Count of question from participant responses.</description>
        <label>No. of Question Attempted</label>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Is_Practice_Question__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>Participant_Game_Response__c.Participant_Game_InfoID__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Reaction_Time__c</fullName>
        <description>This field represents, the total time taken by the participant.</description>
        <label>Total Reaction Time</label>
        <summarizedField>Participant_Game_Response__c.Reaction_Time_in_ms__c</summarizedField>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Is_Practice_Question__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>Participant_Game_Response__c.Participant_Game_InfoID__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>User_Device__c</fullName>
        <description>Device at which test was conducted.(e.g. Desktop, iPad, iPhone, Android.)</description>
        <label>User Device</label>
        <length>56</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>participantFeatureImageURL__c</fullName>
        <label>participantFeatureImageURL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Participant Game Info</label>
    <nameField>
        <displayFormat>PGI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Game Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/People_Like_You_Data__c.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <label>Age</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Average__c</fullName>
        <formula>( High_Average__c  +  Low_Average__c )/2</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Average</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Education__c</fullName>
        <label>Education</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Game_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Game Name</label>
        <referenceTo>Game_Detail__c</referenceTo>
        <relationshipLabel>People Like You Data</relationshipLabel>
        <relationshipName>People_Like_You_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>High_Average__c</fullName>
        <label>High Average</label>
        <precision>8</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Low_Average__c</fullName>
        <label>Low Average</label>
        <precision>8</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sex__c</fullName>
        <label>Sex</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Intersex</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>People Like You Data</label>
    <nameField>
        <displayFormat>PLUD-{000000}</displayFormat>
        <label>People Like You Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People Like You Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ParticipantResultsController.cls
/* Created By: Sibi dahy
** Created On: 17/08/2021
** Description/Purpose: Why and where it is used [TM-203]-It was Created for Catchment and Expanded Game Users Dashboards
** Methods: {getMyGameDetails,getDashboardDataForloggedInUser,getGuestUserGameDetails,getDashboardData}
** Test Class: {ParticipantResultsController_Test} {Code Coverage:96%}
** Controller for catchment results page and Expanded myResults page
** Modify By : Sibi Sathyan for Longitudinal Requirement 
*/
public without sharing class ParticipantResultsController
{    
    
    @AuraEnabled(cacheable=true)
    public static DashboardData getDashboardDataForloggedInUser (String gameName)
    {
        List<User> lstUsers = [SELECT Id,ContactId 
                               From User 
                               where Id =: UserInfo.getUserId()
                               AND ContactId != null];
        String ContactId = lstUsers[0].ContactId;
        return getDashboardData(ContactId, gameName);
    }
    
    @AuraEnabled(cacheable=true) 
    public static DashboardData getDashboardData (String contactId, String gameName)
    {
        Map<String, Integer> mapOtherData = new Map<String, Integer>();
        Map<String, Integer> mapWhatHappendWithAgeData = new Map<String, Integer>();
        Map<String, Integer> mapPlyAverageValuesData = new Map<String, Integer>();
        String userDevice;
        Id currPGIId;        
        mapOtherData.put('YourScore',0);
        mapOtherData.put('isGamePlayed',0); 
        mapOtherData.put('CorrectAnswers',0); 
        mapOtherData.put('ReactionTime',0); 
        mapOtherData.put ('People Like You', 0);
        mapPlyAverageValuesData.put ('LowAverage', 0);
        mapPlyAverageValuesData.put ('HighAverage', 0); 
        DashboardData objDashboardData = new DashboardData();
        
        List<Participant_Game_Info__c> pgis = [SELECT 
                                              /*Added three fields to remove dependency PGR from PGI*/
                                              /* Added on 27/07/2022 */
                                              Count_Of_No_Of_Correct_Answered__c, Count_Of_No_of_Question_Attempted__c,
                                              Count_Of_Total_Reaction_Time__c, No_Of_Correct_Answered__c,
                                              No_of_Question_Attempted__c,Total_Reaction_Time__c, User_Device__c,Id,CreatedDate
                                              FROM Participant_Game_Info__c 
                                              WHERE Contact_Name__c =: contactId  
                                              AND Game_Name__r.Name =:gameName                                              
                                              ORDER BY CreatedDate DESC LIMIT 1];
        if(pgis.size()>0){
            for(Participant_Game_Info__c pgi : pgis){
                if(pgi.CreatedDate.Date() >= Date.Today()-1){
                	pgi.Count_Of_No_of_Question_Attempted__c = pgi.No_of_Question_Attempted__c;
                    pgi.Count_Of_No_Of_Correct_Answered__c = pgi.No_Of_Correct_Answered__c;
                    pgi.Count_Of_Total_Reaction_Time__c = pgi.Total_Reaction_Time__c;
            	}  
            }                      
        } 
        
        for(Participant_Game_Info__c objInfo:pgis)
        {
            userDevice = objInfo.User_Device__c;
            currPGIId= objInfo.Id;
            //changes was made to remove dependency of RollUp summary fields on PGI 
             if(objInfo.Count_Of_No_Of_Correct_Answered__c != null && objInfo.Count_Of_No_of_Question_Attempted__c != null   && objInfo.Count_Of_Total_Reaction_Time__c != null &&  Integer.valueOf(objInfo.Count_Of_No_of_Question_Attempted__c) >0 &&  Integer.valueOf(objInfo.Count_Of_No_Of_Correct_Answered__c)>0 && Integer.valueOf(objInfo.Count_Of_Total_Reaction_Time__c)>0)                             
            {
                mapOtherData.put('isGamePlayed',1);
                mapOtherData.put('YourScore', Integer.valueOf(objInfo.Count_Of_Total_Reaction_Time__c/objInfo.Count_Of_No_of_Question_Attempted__c));
                mapOtherData.put('CorrectAnswers', Integer.valueOf(objInfo.Count_Of_No_Of_Correct_Answered__c));
                mapOtherData.put('ReactionTime', Integer.valueOf(objInfo.Count_Of_Total_Reaction_Time__c / objInfo.Count_Of_No_of_Question_Attempted__c));
                mapOtherData.put('UserDevice', objInfo.User_Device__c=='DESKTOP'?0:1); 
            }
        }
        Contact objCon = [SELECT Sex__c,Age__c,Education_Attainment__c FROM Contact WHERE Id=:contactId ];
        Decimal age = objCon.Age__c;
        Decimal pluage,lowage,highage; 
        if(age>85){
            lowage = 80;
            highage = 115;
        }
        else if(age<18){
            lowage = 18;
            highage = 28;
        }
        else if(age<28){
            lowage = 18;
            highage = age+10;
        }
        else{
            lowage = age-10;
            highage = age+10;
        }        
        pluage = age == null ? 18 : age;
        pluage = pluage < 18 ? 18 : pluage;
        pluage = pluage > 90 ? 90 : pluage;
        Decimal edu_att = objCon.Education_Attainment__c;
        edu_att = edu_att == null ? 1 : edu_att;
        String sex = objCon.Sex__c;
        
        mapPlyAverageValuesData.put ('MaxValue', Integer.valueOf([SELECT Max_Score__c FROM Game_Detail__c where Name=:gameName LIMIT 1].Max_Score__c) );
        List<Participant_Game_Info__c> peopleLikeYouPGIList = [SELECT Count_Of_Total_Reaction_Time__c ,Count_Of_No_of_Question_Attempted__c,Count_Of_No_Of_Correct_Answered__c
                                           FROM Participant_Game_Info__c 
                                           WHERE Contact_Name__r.Age__c > 0
                                           AND Contact_Name__r.Age__c >= :lowage
                                           AND Contact_Name__r.Age__c <= :highage
                                           AND User_Device__c != ''
                                           AND Contact_Name__r.Sex__c != ''
                                           AND Contact_Name__r.Sex__c =:sex
                                           AND Contact_Name__r.Education_Attainment__c =:edu_att
                                           AND Count_Of_No_Of_Correct_Answered__c >0
                                           AND Count_Of_No_of_Question_Attempted__c >0
                                           AND Count_Of_Total_Reaction_Time__c >0
                                           AND Game_Name__r.Name =: gameName
                                           AND Id != :currPGIId
                                           Order by CreatedDate DESC
                                           LIMIT 49990];
        List<Decimal> quartileValues = new List<Decimal>();
        system.debug('First Query:'+peopleLikeYouPGIList.size());
        if(peopleLikeYouPGIList !=null && peopleLikeYouPGIList.size() < 25){
            peopleLikeYouPGIList = [SELECT Count_Of_Total_Reaction_Time__c ,Count_Of_No_of_Question_Attempted__c,Count_Of_No_Of_Correct_Answered__c
                                           FROM Participant_Game_Info__c 
                                           WHERE Contact_Name__r.Age__c > 0
                                           AND Contact_Name__r.Age__c >= :lowage
                                           AND Contact_Name__r.Age__c <= :highage
                                           AND User_Device__c != ''
                                           AND Contact_Name__r.Sex__c != ''
                                    	   AND Contact_Name__r.Sex__c =:sex
                                           AND Contact_Name__r.Education_Attainment__c != null
                                           AND Count_Of_No_Of_Correct_Answered__c >0
                                           AND Count_Of_No_of_Question_Attempted__c >0
                                           AND Count_Of_Total_Reaction_Time__c >0
                                           AND Game_Name__r.Name =: gameName
                                           AND Id != :currPGIId
                                           Order by CreatedDate DESC
                                           LIMIT 49990];
                    system.debug('Second Query:'+peopleLikeYouPGIList.size());
                    if(peopleLikeYouPGIList !=null && peopleLikeYouPGIList.size() < 25){
                    peopleLikeYouPGIList = [SELECT Count_Of_Total_Reaction_Time__c ,Count_Of_No_of_Question_Attempted__c,Count_Of_No_Of_Correct_Answered__c
                                           FROM Participant_Game_Info__c 
                                           WHERE Contact_Name__r.Age__c > 0
                                           AND Contact_Name__r.Age__c >= :lowage
                                           AND Contact_Name__r.Age__c <= :highage
                                           AND User_Device__c != ''
                                           AND Contact_Name__r.Sex__c != ''
                                           AND Contact_Name__r.Education_Attainment__c != null
                                           AND Count_Of_No_Of_Correct_Answered__c >0
                                           AND Count_Of_No_of_Question_Attempted__c >0
                                           AND Count_Of_Total_Reaction_Time__c >0
                                           AND Game_Name__r.Name =: gameName
                                           AND Id != :currPGIId
                                           Order by CreatedDate DESC
                                           LIMIT 49990];
                        system.debug('Third Query:'+peopleLikeYouPGIList.size());
        		}
        }
        if(peopleLikeYouPGIList !=null && peopleLikeYouPGIList.size() >= 25){ 
            if(gameName == 'DLTRS' || gameName == 'Deary Simple And Complex Reaction Time' || gameName == 'Flanker'){
                        Decimal sumReationTime = 0;
                        List<Decimal> reacttimeList = new List<Decimal>();
                        for (Participant_Game_Info__c peopleLikeYouPGI : peopleLikeYouPGIList) {
                            Decimal reactTime = peopleLikeYouPGI.Count_Of_Total_Reaction_Time__c / peopleLikeYouPGI.Count_Of_No_of_Question_Attempted__c;
                            sumReationTime += reactTime;
                            reacttimeList.add(reactTime);      
                        }
                        Decimal reactTimeAvg =   sumReationTime / peopleLikeYouPGIList.size();
                        if(reactTimeAvg != null){
                            mapOtherData.put ('People Like You', Integer.valueOf(reactTimeAvg));
                        }
                		quartileValues.addAll(reacttimeList);
                	}
            else{      
                        Decimal sumcorrAnswer = 0;    
                        Decimal corrAnswerMax = 0;
                        List<Decimal> corrAnswersList = new List<Decimal>();
                        for (Participant_Game_Info__c peopleLikeYouPGI : peopleLikeYouPGIList) { 
                            Decimal corrAnswer = peopleLikeYouPGI.Count_Of_No_Of_Correct_Answered__c;
                            sumcorrAnswer += corrAnswer;
                            corrAnswersList.add(corrAnswer);
                        }
                        Decimal corrAnswerAvg =   sumcorrAnswer / peopleLikeYouPGIList.size();
                        if(corrAnswerAvg != null){
                            mapOtherData.put ('People Like You', Integer.valueOf(corrAnswerAvg));
                        }  
                		quartileValues.addAll(corrAnswersList);
                	}            
                      	quartileValues.sort();                
                        Integer dataSize = quartileValues.size();
                        Integer q1Index = Math.ceil((dataSize + 1) / 4.0).intValue();
                        Integer q2Index = Math.ceil((dataSize + 1) / 2.0).intValue();
                        Integer q3Index = Math.ceil(3 * (dataSize + 1) / 4.0).intValue();
                        
                        if (dataSize > 0) {
                            Integer lowAverage = Integer.valueOf(quartileValues[q1Index - 1]);
                            Integer highAverage = Integer.valueOf(quartileValues[q3Index - 1]);
                            if(lowAverage != null){
                                mapPlyAverageValuesData.put ('LowAverage', lowAverage);
                            }
                            if(highAverage != null){
                                mapPlyAverageValuesData.put ('HighAverage', highAverage);                                      
                            }
                        }
        	}
        	else{
            List<People_Like_You_Data__c> objLikeYouList = [SELECT Education__c,Sex__c, Age__c,Average__c,High_Average__c,Low_Average__c,Game_Name__r.Max_Score__c
            FROM People_Like_You_Data__c
            WHERE Game_Name__r.Name =:gameName 
            AND Sex__c =:objCon.Sex__c AND Education__c>=: edu_att
            AND Age__c =:pluage Order BY Education__c ASC LIMIT 1];
            for(People_Like_You_Data__c peopleLikeYouData : objLikeYouList){
                if(gameName=='Flanker'){
                	mapPlyAverageValuesData.put ('LowAverage', 564);
                	mapPlyAverageValuesData.put ('HighAverage', 963);    
                }
                else
                {
                    mapPlyAverageValuesData.put ('LowAverage', Integer.valueOf(peopleLikeYouData.Low_Average__c));
                    mapPlyAverageValuesData.put ('HighAverage', Integer.valueOf(peopleLikeYouData.High_Average__c)); 
                }  
            } 
           }
      List<Participant_Dashboard__c> partDashboard = [SELECT Data_Value__c FROM Participant_Dashboard__c WHERE Game_Detail__r.Name=:gameName LIMIT 1];
            if(partDashboard !=null && partDashboard.size()>0){
            	mapOtherData.put('Overall Average', Integer.valueOf(partDashboard[0].Data_Value__c));
            }
            else{
                mapOtherData.put('Overall Average', 0);
            }
        objDashboardData.mapOtherData = mapOtherData;
        objDashboardData.mapPlyAverageValuesData = mapPlyAverageValuesData;
        return objDashboardData;
    }
    @AuraEnabled 
    public static void saveSign(String base64Data, String contentType, String currentUserId, String gameName) {
        List<Participant_Game_Info__c> lstPartGameInfo=[SELECT Id, Game_Name__c, participantFeatureImageURL__c, Contact_Name__c, Game_Play_Status__c FROM Participant_Game_Info__c Where Participant_Game_Info__c.Contact_Name__c=:currentUserId];  
        List<ContentDocument> condocvar=new List<ContentDocument>();
        List<Participant_Game_Info__c> updateListPaticipantGameInfo =new List<Participant_Game_Info__c>();
         for(Participant_Game_Info__c objDashboard:lstPartGameInfo)
         {
            Game_Detail__c gName=[SELECT Name, Id FROM Game_Detail__c where id=:objDashboard.Game_Name__c];  
           // ContentDocumentLink checkDocLink=[SELECT ContentDocumentId, LinkedEntityId FROM ContentDocumentLink where LinkedEntityId=:objDashboard.Id LIMIT 1];
            if((gName.Name==gameName) && (objDashboard.participantFeatureImageURL__c==null || objDashboard.participantFeatureImageURL__c=='')){
                    // String yourFiles = 'Lets assume this is your binary string of the files';
                    ContentVersion conVer = new ContentVersion();
                    conVer.ContentLocation = 'S'; // S specify this document is in SF, use E for external files
                    conVer.PathOnClient = contentType;//'ionicLogo1.png'; // The files name, extension is very important here which will help the file in preview.
                    conVer.Title = gameName +'.png'; // Display name of the files
                    conVer.VersionData =  EncodingUtil.base64Decode(base64Data); //EncodingUtil.base64Decode(base64Data); // converting your binary string to Blog
                    insert conVer;
                    //Get Content Documents
                    Id conDoc = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:conVer.Id].ContentDocumentId;
                    //Create ContentDocumentLink
                    ContentDocumentLink cDe = new ContentDocumentLink();
                    cDe.ContentDocumentId = conDoc;
                    cDe.LinkedEntityId = objDashboard.Id; // you can use objectId,GroupId etc
                    cDe.ShareType = 'I'; // Inferred permission, checkout description of ContentDocumentLink object for more details
                    //cDe.Visibility = 'InternalUsers';
                    cDe.Visibility = 'AllUsers';
                    insert cDe;
                    //Create ContentDistribution
                    system.debug('conVer.Title 1:'+conVer.Title);
                    system.debug('conVer.Id:'+conVer.Id);
                    Participant_Game_Info__c partiGameInfo=[SELECT Id, Game_Name__c,participantFeatureImageURL__c, Contact_Name__c, Game_Play_Status__c FROM Participant_Game_Info__c where Id=:objDashboard.id];
                    partiGameInfo.participantFeatureImageURL__c=conDoc;
                    update partiGameInfo;
                    system.debug('partiGameInfo:'+partiGameInfo);  
                    updateListPaticipantGameInfo.add(partiGameInfo);
            }
         }
         //update updateListPaticipantGameInfo;
     }
    public class DashboardData
    {
        @AuraEnabled
        public Map<String, Integer> mapOtherData;
        /* @AuraEnabled
        public Integer age;
        @AuraEnabled
        public Map<String, Integer> mapWhatHappendWithAgeData; */
        @AuraEnabled
        public Map<String,Integer> mapPlyAverageValuesData;     
    }
  
}