objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ADL__c</fullName>
        <label>ADL</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>QPAR__c</fullName>
        <label>QPAR</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SES__c</fullName>
        <label>SES</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QPAR__c.object
<CustomObject>
    <description>cREATED FOR MARKETING CLOUD</description>
    <label>QPAR</label>
    <nameField>
        <displayFormat>QPAR-{0000000000}</displayFormat>
        <label>QPAR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QPARs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SES__c.object
<CustomObject>
    <label>SES</label>
    <nameField>
        <displayFormat>SES-{0000000000}</displayFormat>
        <label>SES Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SESs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GenericBatchClass.cls
global class GenericBatchClass implements Database.Batchable<SObject> {
    private String objectName;
    private String relatedFieldName;

    global GenericBatchClass(String objName, String relFieldName) {
        objectName = objName;
        relatedFieldName = relFieldName;
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Id, ' + relatedFieldName + ' FROM ' + objectName + ' WHERE ' + relatedFieldName + ' != null';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext bc, List<SObject> scope) {
        Set<Id> contactIds = new Set<Id>();

        // Gather Contact Ids from records
        for (SObject obj : scope) {
            contactIds.add((Id)obj.get(relatedFieldName));
        }

        // Query Contacts based on the gathered Contact Ids
        List<Contact> contUpd = [SELECT Id, SES__c, QPAR__c, ADL__c FROM Contact WHERE Id IN :contactIds];

        // Update Contact field if necessary
        for (SObject obj : scope) {
            Id contactId = (Id)obj.get(relatedFieldName);
            String objValue = (String)obj.get(objectName);

            for (Contact con : contUpd) {
                if (con.Id == contactId) {
                    if (objectName == 'SES__c' && con.SES__c != 'Opened') {
                        con.SES__c = 'Opened';
                    } else if (objectName == 'QPAR__c' && con.QPAR__c != 'Opened') {
                        con.QPAR__c = 'Opened';
                    } else if (objectName == 'ADL__c' && con.ADL__c != 'Opened') {
                        con.ADL__c = 'Opened';
                    }
                }
            }
        }

        // Update contacts using database.update
        if (!contUpd.isEmpty()) {
            Database.update(contUpd);
        }
    }

    global void finish(Database.BatchableContext context) {
        System.debug('---IN FINISH');
        //  Add next survey for chain process 
    }
}