objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Education_Attainment__c</fullName>
        <formula>IF( OR(ISPICKVAL( Highest_level_of_education_completed__c , &apos;Up to 8 Years&apos;), ISPICKVAL( Highest_level_of_education_completed__c , &apos;Completed 8th Grade (Elementary or Primary School Graduate)&apos;), ISPICKVAL( Highest_level_of_education_completed__c , &apos;Some High School&apos;) ) , 1,
 IF(ISPICKVAL( Highest_level_of_education_completed__c , &apos;High School Diploma (Baccalaureate)&apos;), 2,  IF(ISPICKVAL( Highest_level_of_education_completed__c , &apos;Some College (Some University)&apos;), 3,  IF(ISPICKVAL( Highest_level_of_education_completed__c , &apos;College Degree (University Graduate)&apos;), 4,  IF(ISPICKVAL( Highest_level_of_education_completed__c , &apos;Post Graduate Degree (Masters or Doctorate)&apos;), 5, 0) ) ) ) 
 )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Education Attainment</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sex__c</fullName>
        <description>Test-taker&apos;s biological sex</description>
        <label>Sex</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Intersex</fullName>
                </value>
                <value>
                    <fullName>Prefer not to answer</fullName>
                    <isActive>false</isActive>
                    <label>Prefer not to answer</label>
                </value>
                <value>
                    <fullName>unknown</fullName>
                    <isActive>false</isActive>
                    <label>unknown</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Game_Detail__c.object
<CustomObject>
    <description>This object is having game information and dependency for other game.</description>
    <fields>
        <fullName>Max_Score__c</fullName>
        <description>The Maximum Score that participant can Score By Playing the Game</description>
        <inlineHelpText>The Maximum Score that participant can Score By Playing the Game</inlineHelpText>
        <label>Max Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Game Detail</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Game Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Participant_Dashboard__c.object
<CustomObject>
    <fields>
        <fullName>Data_Name__c</fullName>
        <label>Data Name</label>
        <length>26</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Data_Value__c</fullName>
        <label>Data Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Game_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Game Detail</label>
        <referenceTo>Game_Detail__c</referenceTo>
        <relationshipLabel>Participant Dashboards</relationshipLabel>
        <relationshipName>DashBoard_Datas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Participant Dashboard</label>
    <nameField>
        <label>Participant Dashboard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participant Dashboards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Participant_Game_Info__c.object
<CustomObject>
    <description>This object is having details of the participant&apos;s game.</description>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to contact, saving contact id, will show contact name at front-end.</description>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Participant Game Infos</relationshipLabel>
        <relationshipName>Participant_Game_Infos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Count_Of_No_Of_Correct_Answered__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Count Of No Of Correct Answered</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Count_Of_No_of_Question_Attempted__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Count Of No of Question Attempted</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Count_Of_Total_Reaction_Time__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Count Of Total Reaction Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Game_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to game, saving game id, will show game name at front-end.</description>
        <label>Game Name</label>
        <referenceTo>Game_Detail__c</referenceTo>
        <relationshipLabel>Participant Game Infos</relationshipLabel>
        <relationshipName>Participant_Game_Infos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Device__c</fullName>
        <description>Device at which test was conducted.(e.g. Desktop, iPad, iPhone, Android.)</description>
        <label>User Device</label>
        <length>56</length>
        <type>Text</type>
    </fields>
    <label>Participant Game Info</label>
    <nameField>
        <displayFormat>PGI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Game Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BatchGameResultDashboardAVG.cls
public class BatchGameResultDashboardAVG implements Database.Batchable<sObject>,Database.Stateful, Schedulable{
        Map<String, Decimal> sumCorrectAnswers;
        Map<String, Integer> countGames;
        Decimal reactTimeMax;
    
       public void execute(SchedulableContext sc) {
        BatchGameResultDashboardAVG ResultAVG = new BatchGameResultDashboardAVG();
        Database.executeBatch(ResultAVG);
       }
    
       public BatchGameResultDashboardAVG() {
            initializeMaps();
        }   
       public Database.QueryLocator start(Database.BatchableContext context) {
        return Database.getQueryLocator([
            SELECT Game_Name__r.Name, User_Device__c, Count_Of_No_Of_Correct_Answered__c,Count_Of_No_of_Question_Attempted__c, 
            Count_Of_Total_Reaction_Time__c
            FROM Participant_Game_Info__c
            WHERE Contact_Name__r.Age__c > 0
            AND Contact_Name__r.Sex__c != ''
            AND Contact_Name__r.Education_Attainment__c != null
            AND Count_Of_No_Of_Correct_Answered__c > 0
            AND Count_Of_No_of_Question_Attempted__c > 0
            AND Count_Of_Total_Reaction_Time__c >0            
        ]);
    }

    public void execute(Database.BatchableContext context, List<Participant_Game_Info__c> gameInfoList) {   
        System.debug('No. of records: '+gameInfoList.size());
        for(Participant_Game_Info__c gameInfo : gameInfoList) {               
            String gameName = gameInfo.Game_Name__r.Name;
            if(gameName == 'Flanker' || gameName == 'DLTRS' || gameName == 'Deary Simple And Complex Reaction Time'){
                Decimal reactionTimeTotal = gameInfo.Count_Of_Total_Reaction_Time__c;  
                Decimal questionsCount = gameInfo.Count_Of_No_of_Question_Attempted__c;  
                Decimal reactionTime = (questionsCount > 0) ? reactionTimeTotal/questionsCount : 0;    
                System.debug('Current Reaction Time: '+reactionTime+ ' / Previous Reaction Time of '+gameInfo.Id+': '+reactTimeMax);
                sumCorrectAnswers.put(gameName, (Decimal)sumCorrectAnswers.get(gameName) + reactionTime);
                if(gameName == 'Flanker'){
                    reactTimeMax = (reactTimeMax == null || reactionTime > reactTimeMax) ? reactionTime : reactTimeMax; 
                }
            }
            else{
                Decimal correctAnswerCount = gameInfo.Count_Of_No_Of_Correct_Answered__c;
                sumCorrectAnswers.put(gameName,  (Decimal)sumCorrectAnswers.get(gameName) + correctAnswerCount);                
            }
            	countGames.put(gameName, countGames.get(gameName) + 1);
        }
   }

    public void finish(Database.BatchableContext context) {  
        Map<String, Decimal> averageCorrectAnswers = new Map<String, Decimal>();
        for (String key : sumCorrectAnswers.keySet()) {
            Decimal sum = sumCorrectAnswers.get(key);
            Integer count = countGames.get(key);
            Decimal average = (count > 0) ? sum/count : 0;
            averageCorrectAnswers.put(key, average);
        }    
    	List<Participant_Dashboard__c> gameStatsToUpdate=[SELECT Data_Value__c,Game_Detail__r.Name FROM Participant_Dashboard__c
                                                         WHERE Data_Name__c ='Overall Average'];

        for (Participant_Dashboard__c gameStat : gameStatsToUpdate) {
            for (String key : averageCorrectAnswers.keySet()) {
                if (gameStat.Game_Detail__r.Name == key){
                     gameStat.Data_Value__c = (Integer)Math.round(averageCorrectAnswers.get(key));
                         break;
                    }
                }
            }     
        Game_Detail__c flankerGame=[SELECT Max_Score__c FROM Game_Detail__c WHERE name='Flanker'];
        flankerGame.Max_Score__c = (Integer)Math.round(reactTimeMax);
        
		update gameStatsToUpdate; 
        update flankerGame;
    }
       private void initializeMaps() {
        sumCorrectAnswers = new Map<String, Decimal>();
        countGames = new Map<String, Integer>();
        List<Game_Detail__c> gameDetails = [SELECT Name from Game_Detail__c where name !='Speech Tasks' and name !='Bean Game'];  
        for (Game_Detail__c gameDetail : gameDetails) {
            sumCorrectAnswers.put(gameDetail.Name, 0);
            countGames.put(gameDetail.Name, 0);
        }
    }
}