objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Flanker__c</fullName>
        <label>Flanker</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>Language selected by test-taker at public application.</description>
        <inlineHelpText>If you are multi-lingual you may want to select the language that you are most fluent in</inlineHelpText>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                </value>
                <value>
                    <fullName>Español</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Participant_Game_Info__c.object
<CustomObject>
    <description>This object is having details of the participant&apos;s game.</description>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to contact, saving contact id, will show contact name at front-end.</description>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Participant Game Infos</relationshipLabel>
        <relationshipName>Participant_Game_Infos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Count_Of_No_Of_Correct_Answered__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Count Of No Of Correct Answered</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Count_Of_No_of_Question_Attempted__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Count Of No of Question Attempted</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Count_Of_Total_Reaction_Time__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Count Of Total Reaction Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Game_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to game, saving game id, will show game name at front-end.</description>
        <label>Game Name</label>
        <referenceTo>Game_Detail__c</referenceTo>
        <relationshipLabel>Participant Game Infos</relationshipLabel>
        <relationshipName>Participant_Game_Infos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>test language get from consent page. ( Language selected by test-taker at public application.)</description>
        <label>Language</label>
        <length>56</length>
        <type>Text</type>
    </fields>
    <label>Participant Game Info</label>
    <nameField>
        <displayFormat>PGI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Game Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BatchContactGameStatusUpdateTest.cls
//Apex Class BatchContactGameStatusUpdate

@IsTest
public with sharing class BatchContactGameStatusUpdateTest {
    
    @IsTest
    static void testBatch() {
        // Create test data
        List<Contact> contacts = new List<Contact>();
        for (Integer i = 0; i < 10; i++) {
            Contact c = new Contact(FirstName = 'Santhosh',Language__c = 'English', LastName = 'Nookilla' + i);
            contacts.add(c);
        }
        insert contacts;
        
        List<Participant_Game_Info__c> pgis = new List<Participant_Game_Info__c>();
        for (Contact c : contacts) {
            pgis.add(new Participant_Game_Info__c(
                Contact_Name__c = c.Id,
                Game_Name__c = 'a028G000002Sg4cQAC',
                Count_Of_No_Of_Correct_Answered__c = 5,
                Count_Of_No_of_Question_Attempted__c = 10,
                Count_Of_Total_Reaction_Time__c = 100
            ));
        }
        insert pgis;
        
        // Call batch
        Test.startTest();
        Database.executeBatch(new BatchContactGameStatusUpdate(), 10);
        Test.stopTest();
        
        // Verify results
        List<Contact> updatedContacts = [SELECT Id, Flanker__c FROM Contact WHERE Id IN :contacts];
        for (Contact c : updatedContacts) {
        System.assertEquals('Opened', c.Flanker__c);
        }
    }
}