objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Deary_Simple_And_Complex_Reaction_Time__c</fullName>
        <label>Deary Simple And Complex Reaction Time</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Face_Name_Associates__c</fullName>
        <label>Face-Name Associates</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Flanker__c</fullName>
        <label>Flanker</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Keep_Track__c</fullName>
        <label>Keep Track</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>Language selected by test-taker at public application.</description>
        <inlineHelpText>If you are multi-lingual you may want to select the language that you are most fluent in</inlineHelpText>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                </value>
                <value>
                    <fullName>Español</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Letter_Number_Sequencing__c</fullName>
        <label>Letter-Number Sequencing</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_Discrimination__c</fullName>
        <label>Object Discrimination</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_Recognition_And_Similarity__c</fullName>
        <label>Object Recognition And Similarity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_Spatial__c</fullName>
        <label>Object Spatial</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_Temporal__c</fullName>
        <label>Object Temporal</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project2_Enrollment_Date__c</fullName>
        <label>Project2 Enrollment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Verbal_Paired_Associates__c</fullName>
        <label>Verbal Paired Associates</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BatchProject2ContactGameStatusUpdate.cls
global class BatchProject2ContactGameStatusUpdate implements Database.Batchable<SObject>, Schedulable {
    
    
    global void execute(SchedulableContext sc) {
        BatchProject2ContactGameStatusUpdate GameUn = new BatchProject2ContactGameStatusUpdate();
        Database.executeBatch(GameUn);
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {   
        return Database.getQueryLocator([Select id,Flanker__c, Letter_Number_Sequencing__c, Keep_Track__c, 
                                         Deary_Simple_And_Complex_Reaction_Time__c,	Object_Discrimination__c, 
                                         Object_Temporal__c, Face_Name_Associates__c, Object_Spatial__c,
                                         Verbal_Paired_Associates__c, Object_Recognition_And_Similarity__c 
										 FROM Contact
										 WHERE Project2_Enrollment_Date__c = N_DAYS_AGO:730
                                         AND Project2_Enrollment_Date__c != null
                                         AND Language__c='English'
                                         AND (Flanker__c != 'Opened' OR Verbal_Paired_Associates__c != 'Opened'
                                              OR Letter_Number_Sequencing__c != 'Opened' OR Keep_Track__c != 'Opened'
                                              OR Deary_Simple_And_Complex_Reaction_Time__c != 'Opened' 
                                              OR Object_Temporal__c != 'Opened'OR Object_Recognition_And_Similarity__c != 'Opened' 
                                              OR Object_Discrimination__c != 'Opened'OR Face_Name_Associates__c != 'Opened' 
                                              OR Object_Spatial__c != 'Opened')]);   
    }

    global void execute(Database.BatchableContext bc, List<Contact> scope) {
        List<Contact> contUpd = new List<Contact>();    
		for(Contact con: scope) {  
            	Boolean isContUpd = false;
				if(con.Flanker__c != 'Opened') {
                    con.Flanker__c = 'Opened';
                    isContUpd=true;
                } 
            
                if(con.Verbal_Paired_Associates__c != 'Opened'){
                   con.Verbal_Paired_Associates__c = 'Opened';
                    isContUpd=true;
                } 
            
                if(con.Letter_Number_Sequencing__c != 'Opened'){
                   con.Letter_Number_Sequencing__c = 'Opened';
                    isContUpd=true;
                } 
            
                if(con.Deary_Simple_And_Complex_Reaction_Time__c != 'Opened'){
                    con.Deary_Simple_And_Complex_Reaction_Time__c = 'Opened';
                    isContUpd=true;
				} 
            
                if(con.Keep_Track__c != 'Opened'){
                   con.Keep_Track__c = 'Opened';
                   isContUpd=true;
				} 
            
                if(con.Object_Recognition_And_Similarity__c != 'Opened'){
                   con.Object_Recognition_And_Similarity__c = 'Opened';
                   isContUpd=true;
				} 
            
                if(con.Object_Discrimination__c != 'Opened'){
                   con.Object_Discrimination__c = 'Opened';
                   isContUpd=true;
				} 
            
                if(con.Object_Temporal__c != 'Opened'){
                   con.Object_Temporal__c = 'Opened';
                   isContUpd=true;
				}       
            
                if(con.Face_Name_Associates__c != 'Opened'){
                   con.Face_Name_Associates__c = 'Opened';
                   isContUpd=true;
				} 
            
                if(con.Object_Spatial__c != 'Opened'){
                   con.Object_Spatial__c = 'Opened';
                   isContUpd=true;
				} 
            if(isContUpd){
                contUpd.add(con);
            }
		}
        
        Database.SaveResult[] srList = database.update(contUpd, false);

		for (Database.SaveResult sr : srList) {
    	 if (!sr.isSuccess()) {              
          for(Database.Error err : sr.getErrors()) {
            String description =  'Error occured updating record: '+sr.getId()+'- Error Message: '+err.getMessage();
            ExceptionLogHandler.logException(null,'BatchContactGameStatusUpdate','Execute',description);                
          }
         }
       }
        
	}

	global void finish(Database.BatchableContext context) {
        System.debug('---IN FINISH');
    }
}