objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Deary_Simple_And_Complex_Reaction_Time__c</fullName>
        <label>Deary Simple And Complex Reaction Time</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Face_Name_Associates__c</fullName>
        <label>Face-Name Associates</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Flanker__c</fullName>
        <label>Flanker</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Keep_Track__c</fullName>
        <label>Keep Track</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Letter_Number_Sequencing__c</fullName>
        <label>Letter-Number Sequencing</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_Discrimination__c</fullName>
        <label>Object Discrimination</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_Recognition_And_Similarity__c</fullName>
        <label>Object Recognition And Similarity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_Spatial__c</fullName>
        <label>Object Spatial</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_Temporal__c</fullName>
        <label>Object Temporal</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project2_Enrollment_Date__c</fullName>
        <label>Project2 Enrollment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Verbal_Paired_Associates__c</fullName>
        <label>Verbal Paired Associates</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Game_Detail__c.object
<CustomObject>
    <description>This object is having game information and dependency for other game.</description>
    <label>Game Detail</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Game Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Participant_Game_Info__c.object
<CustomObject>
    <description>This object is having details of the participant&apos;s game.</description>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to contact, saving contact id, will show contact name at front-end.</description>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Participant Game Infos</relationshipLabel>
        <relationshipName>Participant_Game_Infos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Game_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to game, saving game id, will show game name at front-end.</description>
        <label>Game Name</label>
        <referenceTo>Game_Detail__c</referenceTo>
        <relationshipLabel>Participant Game Infos</relationshipLabel>
        <relationshipName>Participant_Game_Infos</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Participant Game Info</label>
    <nameField>
        <displayFormat>PGI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Game Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BatchContactGameStatusUpdate.cls
global class BatchContactGameStatusUpdate implements Database.Batchable<SObject>, Schedulable {
    
    
    global void execute(SchedulableContext sc) {
        BatchContactGameStatusUpdate GameUn = new BatchContactGameStatusUpdate();
        Database.executeBatch(GameUn);
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {   
        //Step - 1 : Get All the PGI records / contacts
        return Database.getQueryLocator([Select id, Game_Name__r.Name,Contact_Name__r.Id, Contact_Name__c, Game_Name__c
										FROM Participant_Game_Info__c 
										WHERE
										((Game_Name__r.Name IN ('Flanker', 'Letter-Number Sequencing', 'Keep Track', 'Deary Simple And Complex Reaction Time')
													AND CreatedDate = N_DAYS_AGO:91)
										OR (Game_Name__r.Name IN ('Object Discrimination', 'Object Temporal', 'Face-Name Associates', 'Object Spatial') 
													AND CreatedDate = N_DAYS_AGO:183)
										OR (Game_Name__r.Name IN ('Verbal Paired Associates', 'Object Recognition And Similarity') 
													AND CreatedDate = N_DAYS_AGO:365))
													AND Contact_Name__r.Project2_Enrollment_Date__c = null
                                                    ]);  
   
    }

    global void execute(Database.BatchableContext bc, List<Participant_Game_Info__c> scope) {
       
        //Step - 2 : In execute method get All unique contact Ids from scope and store in below variable List<Id> contIds;
        
        Set<Id> contactIds = new Set<Id>();
		for (Participant_Game_Info__c pgi : scope) {
        contactIds.add(pgi.Contact_Name__r.Id);
    	}
        
        //Step - 3 : Run a query to get all contact with all 10 game status fields using above contactIds
        
    	List<Id> contIds = new List<Id>(contactIds);
    	List<Contact> contUpd = [SELECT Flanker__c, Letter_Number_Sequencing__c, Keep_Track__c, Deary_Simple_And_Complex_Reaction_Time__c,
								Object_Discrimination__c, Object_Temporal__c, Face_Name_Associates__c, Object_Spatial__c,
								Verbal_Paired_Associates__c, Object_Recognition_And_Similarity__c FROM Contact WHERE Id IN :contIds];
        
        //Step - 4 : Loop throgh the PGI records and write if condition for each game and update the correpsonding status field in contUpd
    
		for(Participant_Game_Info__c pgi : scope) {    
            for(Contact con : contUpd) {
                if(con.Id == pgi.Contact_Name__r.Id) {
                    
				if(pgi.Game_Name__r.Name == 'Flanker' && con.Flanker__c != 'Opened') {
                        con.Flanker__c = 'Opened';

                } else if(pgi.Game_Name__r.Name == 'Verbal Paired Associates' && con.Verbal_Paired_Associates__c != 'Opened'){
                        con.Verbal_Paired_Associates__c = 'Opened';

                } else if(pgi.Game_Name__r.Name == 'Letter-Number Sequencing' && con.Letter_Number_Sequencing__c != 'Opened'){
                        con.Letter_Number_Sequencing__c = 'Opened';

                } else if(pgi.Game_Name__r.Name == 'Deary Simple And Complex Reaction Time' && con.Deary_Simple_And_Complex_Reaction_Time__c != 'Opened'){
                        con.Deary_Simple_And_Complex_Reaction_Time__c = 'Opened';

				} else if(pgi.Game_Name__r.Name == 'Keep Track' && con.Keep_Track__c != 'Opened'){
                        con.Keep_Track__c = 'Opened';

				} else if(pgi.Game_Name__r.Name == 'Object Recognition And Similarity' && con.Object_Recognition_And_Similarity__c != 'Opened'){
                        con.Object_Recognition_And_Similarity__c = 'Opened';

				} else if(pgi.Game_Name__r.Name == 'Object Discrimination' && con.Object_Discrimination__c != 'Opened'){
                        con.Object_Discrimination__c = 'Opened';

				} else if(pgi.Game_Name__r.Name == 'Object Temporal' && con.Object_Temporal__c != 'Opened'){
                        con.Object_Temporal__c = 'Opened';

				} else if(pgi.Game_Name__r.Name == 'Face-Name Associates' && con.Face_Name_Associates__c != 'Opened'){
                        con.Face_Name_Associates__c = 'Opened';

				} else if(pgi.Game_Name__r.Name == 'Object Spatial' && con.Object_Spatial__c != 'Opened'){
                        con.Object_Spatial__c = 'Opened';

				} 
			}
		}    
     }
        
     Database.SaveResult[] srList = database.update(contUpd, false);

		for (Database.SaveResult sr : srList) {
    	 if (!sr.isSuccess()) {              
          for(Database.Error err : sr.getErrors()) {
            String description =  'Error occured updating record: '+sr.getId()+'- Error Message: '+err.getMessage();
            ExceptionLogHandler.logException(null,'BatchContactGameStatusUpdate','Execute',description);                
          }
         }
       }
        
	}

	global void finish(Database.BatchableContext context) {
        System.debug('---IN FINISH');
    }
}