objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Activation_Date__c</fullName>
        <description>Set current date when user created for new contact or historical contact.</description>
        <label>Activation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Enrolled_in_Paid_Campaign__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enrolled in Paid Campaign</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>Language selected by test-taker at public application.</description>
        <inlineHelpText>If you are multi-lingual you may want to select the language that you are most fluent in</inlineHelpText>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                </value>
                <value>
                    <fullName>Español</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tremendous_Award_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tremendous Award Sent</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Game_Detail__c.object
<CustomObject>
    <description>This object is having game information and dependency for other game.</description>
    <label>Game Detail</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Game Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Participant_Game_Info__c.object
<CustomObject>
    <description>This object is having details of the participant&apos;s game.</description>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to contact, saving contact id, will show contact name at front-end.</description>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Participant Game Infos</relationshipLabel>
        <relationshipName>Participant_Game_Infos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Count_Of_No_Of_Correct_Answered__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Count Of No Of Correct Answered</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Count_Of_No_of_Question_Attempted__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Count Of No of Question Attempted</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Count_Of_Total_Reaction_Time__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Count Of Total Reaction Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Game_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to game, saving game id, will show game name at front-end.</description>
        <label>Game Name</label>
        <referenceTo>Game_Detail__c</referenceTo>
        <relationshipLabel>Participant Game Infos</relationshipLabel>
        <relationshipName>Participant_Game_Infos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Game_Play_Status__c</fullName>
        <label>Game Play Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not-Completed</fullName>
                    <default>true</default>
                    <label>Not-Completed</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>test language get from consent page. ( Language selected by test-taker at public application.)</description>
        <label>Language</label>
        <length>56</length>
        <type>Text</type>
    </fields>
    <label>Participant Game Info</label>
    <nameField>
        <displayFormat>PGI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Game Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Research_Campaign__c.object
<CustomObject>
    <description>It consists of the campaigns type of mindcrowd like Covid, DBS, Bean game</description>
    <label>Research Campaign</label>
    <nameField>
        <label>Research Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Shipping_Detail__c.object
<CustomObject>
    <description>This Object comprises of all the fields which are related to shipment process.</description>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field has a mandatory lookup to ResearchCampaign object.</description>
        <label>Campaign</label>
        <referenceTo>Research_Campaign__c</referenceTo>
        <relationshipLabel>Shipping Details</relationshipLabel>
        <relationshipName>Shipping_Details</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Id__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>A mandatory look up field to contact so that every shipment has a contact linked to it.</description>
        <label>Contact Id</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Shipping Details</relationshipLabel>
        <relationshipName>Shipping_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <formula>TEXT(Contact_Id__r.Language__c )</formula>
        <label>Language</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipment_Status__c</fullName>
        <description>This field is used to track whether the shipment is created, sent to the participant or received by the Mindcrowd team.</description>
        <label>Shipment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Consented</fullName>
                    <default>true</default>
                    <label>Consented</label>
                </value>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Invalid Address</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Shipping Detail</label>
    <nameField>
        <displayFormat>SD-{00000000}</displayFormat>
        <label>Shipping Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TremendousSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>TremendousSettings</label>
    <fields>
        <fullName>AuthToken__c</fullName>
        <label>AuthToken</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Authorization__c</fullName>
        <label>Authorization</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CampaignId__c</fullName>
        <label>CampaignId</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContentType__c</fullName>
        <label>ContentType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DeliveryMethod__c</fullName>
        <label>DeliveryMethod</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Denomination__c</fullName>
        <label>Denomination</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EndpointURL__c</fullName>
        <label>EndpointURL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FundingSourceId__c</fullName>
        <label>FundingSourceId</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RestMethod__c</fullName>
        <label>RestMethod</label>
        <length>80</length>
        <type>Text</type>
    </fields>
</CustomObject>

classes/SendRewardsToUsersBatchTest.cls
@isTest
private class SendRewardsToUsersBatchTest {
    @testSetup
static void setupTestData() {
    // Create custom setting records
  
  TremendousSetting__c  customSettingRecords = new TremendousSetting__c();
    customSettingRecords.Name ='RewardsSetting';
    customSettingRecords.Authorization__c='Bearer';
    customSettingRecords.AuthToken__c='TEST_5n1O4iBqt--GrYym0iu2LBgOZgZ_NvV2QgnSM2YUjHl';
    customSettingRecords.CampaignId__c='NBCOGE73UBCZ';
    customSettingRecords.FundingSourceId__c = 'BALANCE';
    customSettingRecords.EndpointURL__c = 'https://testflight.tremendous.com/api/v2/ping';
    customSettingRecords.Denomination__c = 50;
    customSettingRecords.DeliveryMethod__c = 'Email';
    customSettingRecords.ContentType__c = 'application/json';
    customSettingRecords.RestMethod__c= 'POST';
    insert customSettingRecords; 
      List<Contact> testContacts = new List<Contact>();
       for (Integer i = 0; i < 1; i++) {
            testContacts.add(new Contact(
                FirstName = 'TestFirstName' + i,
                LastName = 'TestLastName' + i,
                Email = 'testemail' + i + '@example.com',
                Enrolled_in_Paid_Campaign__c = True,
                Tremendous_Award_Sent__c = False,
                Language__c='English',
                Activation_Date__c = System.today()
               
            ));
        }
    
        insert testContacts;
    Research_Campaign__c rc = new Research_Campaign__c(Name = 'DBS');
    insert rc;
    Shipping_Detail__c sd = new Shipping_Detail__c(Shipment_Status__c = 'Received', Campaign__c=rc.Id,contact_Id__c=testContacts[0].Id);
    insert sd;
       
    List<Game_Detail__c> games = new List<Game_Detail__c>();
    List<String> gameNames = new List<String>{'Flanker', 'Letter-Number Sequencing', 'Keep Track', 'Object Spatial', 'Deary Simple And Complex Reaction Time', 'Object Discrimination', 'Object Temporal', 'Face-Name Associates', 'Verbal Paired Associates', 'Object Recognition And Similarity'};
        for(String gameName: gameNames){
            Game_Detail__c game = new Game_Detail__c();
            game.Name = gameName;
			games.add(game);           
        } 
    insert games;
    
    List<Participant_Game_Info__c> pgis = new List<Participant_Game_Info__c>();
    for(Game_Detail__c game: [Select Id, Name from Game_Detail__c]){
        Participant_Game_Info__c pgi = new Participant_Game_Info__c();
            pgi.Contact_Name__c = testContacts[0].Id;
            pgi.Game_Name__c = game.Id;
            pgi.Game_Play_Status__c = 'Completed';
            pgi.Count_Of_No_Of_Correct_Answered__c = 10;
            pgi.Count_Of_No_of_Question_Attempted__c = 10;
            pgi.Count_Of_Total_Reaction_Time__c = 10;
            pgi.Count_Of_No_Of_Correct_Answered__c = 10;
            pgi.Count_Of_No_of_Question_Attempted__c = 10;
            pgi.Count_Of_Total_Reaction_Time__c = 10;
			pgis.add(pgi);
		}
    insert pgis;
}

    @isTest
    static void testSendRewardsBatch() {
       

        
         // Set up the mock callout class
        Test.setMock(HttpCalloutMock.class, new SendRewardsToUsersBatchMock());

        // Schedule the batch job
        Test.startTest();
        SendRewardsToUsersBatch sendRewardBatch = new SendRewardsToUsersBatch();
        
        String jobId = System.schedule('SendRewardsBatchTest', '0 0 0 15 3 ?', sendRewardBatch);
        Test.stopTest();

        // Check if the batch job ran successfully
        //AsyncApexJob job = [SELECT Id, Status, NumberOfErrors FROM AsyncApexJob WHERE Id = :jobId];
        //System.assertEquals('Completed', job.Status);
        //System.assertEquals(0, job.NumberOfErrors);

    }
    @isTest
    static void testSendRewardsBatch1_WrongPayload() {
    TremendousSetting__c  customSettingRecords = [Select id,EndpointURL__c from TremendousSetting__c limit 1];
        customSettingRecords.EndpointURL__c='wrong';
        update customSettingRecords;
         // Create test data
     
         // Set up the mock callout class
        Test.setMock(HttpCalloutMock.class, new SendRewardsToUsersBatchMock());

        // Schedule the batch job
        Test.startTest();
        SendRewardsToUsersBatch sendRewardBatch = new SendRewardsToUsersBatch();
        
        String jobId = System.schedule('SendRewardsBatchTest', '0 0 0 15 3 ?', sendRewardBatch);
        Test.stopTest();

        
        }
     @isTest
    static void testSendRewardsBatch1_CatchError() {
    TremendousSetting__c  customSettingRecords = [Select id,EndpointURL__c from TremendousSetting__c limit 1];
        customSettingRecords.EndpointURL__c=NULL;
        update customSettingRecords;
       
        
        
         // Set up the mock callout class
        Test.setMock(HttpCalloutMock.class, new SendRewardsToUsersBatchMock());

        // Schedule the batch job
        Test.startTest();
        SendRewardsToUsersBatch sendRewardBatch = new SendRewardsToUsersBatch();
        
        String jobId = System.schedule('SendRewardsBatchTest', '0 0 0 15 3 ?', sendRewardBatch);
        Test.stopTest();

        
        }
}