objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Consent_Catchment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Consent Catchment</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Game_Detail__c.object
<CustomObject>
    <description>This object is having game information and dependency for other game.</description>
    <label>Game Detail</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Game Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Participant_Game_Info__c.object
<CustomObject>
    <description>This object is having details of the participant&apos;s game.</description>
    <fields>
        <fullName>Game_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to game, saving game id, will show game name at front-end.</description>
        <label>Game Name</label>
        <referenceTo>Game_Detail__c</referenceTo>
        <relationshipLabel>Participant Game Infos</relationshipLabel>
        <relationshipName>Participant_Game_Infos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Game_Play_Status__c</fullName>
        <label>Game Play Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not-Completed</fullName>
                    <default>true</default>
                    <label>Not-Completed</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Participant Game Info</label>
    <nameField>
        <displayFormat>PGI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Game Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Research_Campaign__c.object
<CustomObject>
    <description>It consists of the campaigns type of mindcrowd like Covid, DBS, Bean game</description>
    <label>Research Campaign</label>
    <nameField>
        <label>Research Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Shipping_Detail__c.object
<CustomObject>
    <description>This Object comprises of all the fields which are related to shipment process.</description>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field has a mandatory lookup to ResearchCampaign object.</description>
        <label>Campaign</label>
        <referenceTo>Research_Campaign__c</referenceTo>
        <relationshipLabel>Shipping Details</relationshipLabel>
        <relationshipName>Shipping_Details</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment_Status__c</fullName>
        <description>This field is used to track whether the shipment is created, sent to the participant or received by the Mindcrowd team.</description>
        <label>Shipment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Consented</fullName>
                    <default>true</default>
                    <label>Consented</label>
                </value>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Invalid Address</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Shipping Detail</label>
    <nameField>
        <displayFormat>SD-{00000000}</displayFormat>
        <label>Shipping Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AdminDashBoardcontroller.cls
public class AdminDashBoardcontroller 
{
    @AuraEnabled
    public static Map<String,Integer> getGroupChartMap(Date startDate, Date endDate, String campaignId)
    {
        Map<String,Integer> mapGroupData = new Map<String,Integer>();
        Map<String,Integer> mapOrdData = new Map<String,Integer>();
        System.debug('StartDate endDate'+startDate +' '+endDate +' '+ campaignId);
        Datetime startDateTime = startDate;
        Datetime endDateTime =endDate;
        Schema.DescribeFieldResult fieldDescription = Shipping_Detail__c.Shipment_Status__c.getDescribe();
        
        for (Schema.PicklistEntry entry : fieldDescription.getPicklistValues()) 
        {
            if(entry.isActive())
            {
                mapGroupData.put(entry.getLabel(), 0);
            }
        } 
        
        for (AggregateResult ar : [SELECT Shipment_Status__c, count(name)
                                   from Shipping_Detail__c
                                   where Campaign__c= :campaignId
                                   AND CreatedDate >= :startDateTime AND CreatedDate <= :endDateTime
                                   group by Shipment_Status__c])  
        {
            System.debug('Shipment records are...'+ar);
            if(ar.get('Shipment_Status__c') != null)
                mapGroupData.put(String.valueOf(ar.get('Shipment_Status__c')), Integer.valueOf(ar.get('expr0')));
            
        }
        
        if (mapGroupData.containsKey('Consented')) {
        mapOrdData.put('Consented', mapGroupData.get('Consented'));
      }
    if (mapGroupData.containsKey('Created')) {
        mapOrdData.put('Created', mapGroupData.get('Created'));
    }
    if (mapGroupData.containsKey('Sent')) {
        mapOrdData.put('Sent', mapGroupData.get('Sent'));
    }
    if (mapGroupData.containsKey('Delivered')) {
        mapOrdData.put('Delivered', mapGroupData.get('Delivered'));
    }
    if (mapGroupData.containsKey('Received')) {
        mapOrdData.put('Received', mapGroupData.get('Received'));
    }
        
        System.debug('MapOrdData...'+mapOrdData);
        return mapOrdData;
        
    }
    
    @AuraEnabled
    public static Map<String,Integer> getOtherGroupChartMap(Date startDate, Date endDate)
    {
        Map<String,Integer> mapGroupData = new Map<String,Integer>();
        Map<String,Integer> mapRegData = new Map<String,Integer>();
        System.debug('StartDate endDate'+startDate +' '+endDate );
        
        Datetime startDateTime = startDate;
        Datetime endDateTime =endDate;
        
        for (AggregateResult ar : [SELECT Game_Play_Status__c, count(Name) FROM Participant_Game_Info__c 
                                   WHERE Game_Name__c  in (SELECT Id from Game_Detail__c WHERE Name ='DLTRS') 
                                   AND CreatedDate >= :startDateTime AND CreatedDate <= :endDateTime
                                   Group By Game_Play_Status__c])  
        {
            if(ar.get('Game_Play_Status__c') != null)
                mapGroupData.put(String.valueOf(ar.get('Game_Play_Status__c')) +' Game', Integer.valueOf(ar.get('expr0')));
            
        }
        List<AggregateResult>  lstResults = [SELECT Count(Id), Count(Email) FROM Contact Where Consent_Catchment__c = true 
                                             AND CreatedDate >= :startDateTime AND CreatedDate <= :endDateTime];
        if(lstResults != null && !lstResults.isEmpty())
        {
            mapGroupData.put('Enrolled People(Consents)', Integer.valueOf(lstResults[0].get('expr0')));
            mapGroupData.put('Email Addresses Collected', Integer.valueOf(lstResults[0].get('expr1')));
        }
        
        // Re-arrange the Data in shorting order as below
        if (mapGroupData.containsKey('Enrolled People(Consents)')) {
        mapRegData.put('Enrolled People(Consents)', mapGroupData.get('Enrolled People(Consents)'));
      }
    if (mapGroupData.containsKey('Not-Completed Game')) {
        mapRegData.put('Not-Completed Game', mapGroupData.get('Not-Completed Game'));
    }
    if (mapGroupData.containsKey('Completed Game')) {
        mapRegData.put('Completed Game', mapGroupData.get('Completed Game'));
    }
    if (mapGroupData.containsKey('Email Addresses Collected')) {
        mapRegData.put('Email Addresses Collected', mapGroupData.get('Email Addresses Collected'));
    }
        return mapRegData;
    }
    
    @AuraEnabled
    public static List<Option> getResearchCampaigns()
    {
        List<Option> lstOptions = new List<Option>();
        for (Research_Campaign__c objCampaign : [SELECT Id, Name FROM Research_Campaign__c]){
            lstOptions.add(new Option(objCampaign.Name, objCampaign.Id));
        }
        return lstOptions;
    }
    public class Option
    {
        @AuraEnabled
        public String value;
        @AuraEnabled
        public String label;
        public Option(String label, String value)
        {
            this.label = label;
            this.value =value;
        }
    }
}