objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Education_Attainment__c</fullName>
        <formula>IF( OR(ISPICKVAL( Highest_level_of_education_completed__c , &apos;Up to 8 Years&apos;), ISPICKVAL( Highest_level_of_education_completed__c , &apos;Completed 8th Grade (Elementary or Primary School Graduate)&apos;), ISPICKVAL( Highest_level_of_education_completed__c , &apos;Some High School&apos;) ) , 1,
 IF(ISPICKVAL( Highest_level_of_education_completed__c , &apos;High School Diploma (Baccalaureate)&apos;), 2,  IF(ISPICKVAL( Highest_level_of_education_completed__c , &apos;Some College (Some University)&apos;), 3,  IF(ISPICKVAL( Highest_level_of_education_completed__c , &apos;College Degree (University Graduate)&apos;), 4,  IF(ISPICKVAL( Highest_level_of_education_completed__c , &apos;Post Graduate Degree (Masters or Doctorate)&apos;), 5, 0) ) ) ) 
 )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Education Attainment</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sex__c</fullName>
        <description>Test-taker&apos;s biological sex</description>
        <label>Sex</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Intersex</fullName>
                </value>
                <value>
                    <fullName>Prefer not to answer</fullName>
                    <isActive>false</isActive>
                    <label>Prefer not to answer</label>
                </value>
                <value>
                    <fullName>unknown</fullName>
                    <isActive>false</isActive>
                    <label>unknown</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Game_Detail__c.object
<CustomObject>
    <description>This object is having game information and dependency for other game.</description>
    <fields>
        <fullName>Max_Score__c</fullName>
        <description>The Maximum Score that participant can Score By Playing the Game</description>
        <inlineHelpText>The Maximum Score that participant can Score By Playing the Game</inlineHelpText>
        <label>Max Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Game Detail</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Game Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Participant_Dashboard__c.object
<CustomObject>
    <fields>
        <fullName>Data_Category__c</fullName>
        <label>Data Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Age</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Data_Name__c</fullName>
        <label>Data Name</label>
        <length>26</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Data_Value__c</fullName>
        <label>Data Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Game_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Game Detail</label>
        <referenceTo>Game_Detail__c</referenceTo>
        <relationshipLabel>Participant Dashboards</relationshipLabel>
        <relationshipName>DashBoard_Datas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Participant Dashboard</label>
    <nameField>
        <label>Participant Dashboard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participant Dashboards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Participant_Game_Info__c.object
<CustomObject>
    <description>This object is having details of the participant&apos;s game.</description>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to contact, saving contact id, will show contact name at front-end.</description>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Participant Game Infos</relationshipLabel>
        <relationshipName>Participant_Game_Infos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Count_Of_No_Of_Correct_Answered__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Count Of No Of Correct Answered</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Count_Of_No_of_Question_Attempted__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Count Of No of Question Attempted</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Count_Of_Total_Reaction_Time__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Count Of Total Reaction Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Game_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to game, saving game id, will show game name at front-end.</description>
        <label>Game Name</label>
        <referenceTo>Game_Detail__c</referenceTo>
        <relationshipLabel>Participant Game Infos</relationshipLabel>
        <relationshipName>Participant_Game_Infos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Game_Play_Status__c</fullName>
        <label>Game Play Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not-Completed</fullName>
                    <default>true</default>
                    <label>Not-Completed</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>No_Of_Correct_Answered__c</fullName>
        <description>Count the correct answers were responded by the participant</description>
        <label>No. Of Correct Answered</label>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Is_Correct__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Is_Practice_Question__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>Participant_Game_Response__c.Participant_Game_InfoID__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>No_of_Question_Attempted__c</fullName>
        <description>Count of question from participant responses.</description>
        <label>No. of Question Attempted</label>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Is_Practice_Question__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>Participant_Game_Response__c.Participant_Game_InfoID__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Reaction_Time__c</fullName>
        <description>This field represents, the total time taken by the participant.</description>
        <label>Total Reaction Time</label>
        <summarizedField>Participant_Game_Response__c.Reaction_Time_in_ms__c</summarizedField>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Is_Practice_Question__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>Participant_Game_Response__c.Participant_Game_InfoID__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>User_Device__c</fullName>
        <description>Device at which test was conducted.(e.g. Desktop, iPad, iPhone, Android.)</description>
        <label>User Device</label>
        <length>56</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>participantFeatureImageURL__c</fullName>
        <label>participantFeatureImageURL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Participant Game Info</label>
    <nameField>
        <displayFormat>PGI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Game Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/People_Like_You_Data__c.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <label>Age</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Average__c</fullName>
        <formula>( High_Average__c  +  Low_Average__c )/2</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Average</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Education__c</fullName>
        <label>Education</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Game_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Game Name</label>
        <referenceTo>Game_Detail__c</referenceTo>
        <relationshipLabel>People Like You Data</relationshipLabel>
        <relationshipName>People_Like_You_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>High_Average__c</fullName>
        <label>High Average</label>
        <precision>8</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Low_Average__c</fullName>
        <label>Low Average</label>
        <precision>8</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sex__c</fullName>
        <label>Sex</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Intersex</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>People Like You Data</label>
    <nameField>
        <displayFormat>PLUD-{000000}</displayFormat>
        <label>People Like You Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People Like You Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ParticipantResultsControllerES.cls
// Created By: {Girikon(Manikumar Meruva)}
// Created On: 17/08/2021
// Description/Purpose: Why and where it is used [TM-203]-It was Created for Catchment and Expanded Game Users Dashboards
// Methods: {getMyGameDetails,getDashboardDataForloggedInUser,getGuestUserGameDetails,getDashboardData}
// Test Class: {ParticipantResultsController_Test} {Code Coverage:96%}
/**
* Controller for catchment results page and Expanded myResults page
* Modify By : {ManiKumar Meruva}
* 
*/
public without sharing class ParticipantResultsControllerES
{    
    
    @AuraEnabled(cacheable=true)
    public static DashboardData getDashboardDataForloggedInUser (String gameName)
    {
        List<User> lstUsers = [SELECT Id,ContactId 
                               From User 
                               where Id =: UserInfo.getUserId()
                               AND ContactId != null];
        String ContactId = lstUsers[0].ContactId;
        return getDashboardData(ContactId, gameName);
    }
    
    @AuraEnabled(cacheable=true) 
    public static DashboardData getDashboardData (String contactId, String gameName)
    {
        
        Map<String, Integer> mapOtherData = new Map<String, Integer>();
        Map<String, Integer> mapWhatHappendWithAgeData = new Map<String, Integer>();
        Map<String, Integer> mapPlyAverageValuesData = new Map<String, Integer>();
        Map<String, Integer> overaallAvgMap = new Map<String, Integer>{'DLTRS'=>498,'Deary Simple And Complex Reaction Time'=>498,
            'Face-Name Associates'=>28,'Keep Track'=>14,'Letter-Number Sequencing'=>89,'Object Discrimination'=>22,
            'Object Recognition And Similarity'=>92,'Object Spatial'=>22,'Object Temporal'=>22,'PAIRED GAME'=>17,'Flanker'=>23,
            'Verbal Paired Associates'=>17};
        
        mapOtherData.put('YourScore',0);
        mapOtherData.put('isGamePlayed',0); 
        mapOtherData.put('CorrectAnswers',0); 
        mapOtherData.put('ReactionTime',0); 
        
        DashboardData objDashboardData = new DashboardData();
        
        for(Participant_Game_Info__c objInfo:[SELECT 
                                              /*Added three fields to remove dependency PGR from PGI*/
                                              /* Added on 27/07/2022 */
                                              Count_Of_No_Of_Correct_Answered__c,
                                              Count_Of_No_of_Question_Attempted__c,
                                              Count_Of_Total_Reaction_Time__c,
                                              No_Of_Correct_Answered__c,
                                              No_of_Question_Attempted__c,
                                              Total_Reaction_Time__c,
                                              User_Device__c                                        
                                              FROM Participant_Game_Info__c 
                                              WHERE Contact_Name__c =: contactId  
                                              AND Game_Name__r.Name =:gameName 
                                              ORDER BY CreatedDate DESC LIMIT 1])
        {
            System.debug(objInfo.No_of_Question_Attempted__c);
            System.debug(objInfo.No_Of_Correct_Answered__c );
            System.debug(objInfo.Total_Reaction_Time__c);
            /*changes was made to remove dependency of RollUp summary fields on PGI
              Commented below lines on 27/07/2022*/
            //if(objInfo.No_Of_Correct_Answered__c != null && objInfo.No_of_Question_Attempted__c != null   && objInfo.Total_Reaction_Time__c != null &&  Integer.valueOf(objInfo.No_of_Question_Attempted__c) >0 &&  Integer.valueOf(objInfo.No_Of_Correct_Answered__c)>0 && Integer.valueOf(objInfo.Total_Reaction_Time__c)>0)  
             if(objInfo.Count_Of_No_Of_Correct_Answered__c != null && objInfo.Count_Of_No_of_Question_Attempted__c != null   && objInfo.Count_Of_Total_Reaction_Time__c != null &&  Integer.valueOf(objInfo.Count_Of_No_of_Question_Attempted__c) >0 &&  Integer.valueOf(objInfo.Count_Of_No_Of_Correct_Answered__c)>0 && Integer.valueOf(objInfo.Count_Of_Total_Reaction_Time__c)>0)                             
            {
                mapOtherData.put('isGamePlayed',1);
                //mapOtherData.put('YourScore', Integer.valueOf(objInfo.Total_Reaction_Time__c/objInfo.No_of_Question_Attempted__c));
                //mapOtherData.put('CorrectAnswers', Integer.valueOf(objInfo.No_Of_Correct_Answered__c));
                //mapOtherData.put('ReactionTime', Integer.valueOf(objInfo.Total_Reaction_Time__c / objInfo.No_of_Question_Attempted__c));
                mapOtherData.put('YourScore', Integer.valueOf(objInfo.Count_Of_Total_Reaction_Time__c/objInfo.Count_Of_No_of_Question_Attempted__c));
                mapOtherData.put('CorrectAnswers', Integer.valueOf(objInfo.Count_Of_No_Of_Correct_Answered__c));
                mapOtherData.put('ReactionTime', Integer.valueOf(objInfo.Count_Of_Total_Reaction_Time__c / objInfo.Count_Of_No_of_Question_Attempted__c));
                mapOtherData.put('UserDevice', objInfo.User_Device__c=='DESKTOP'?0:1);
                
            }else
            {
                mapOtherData.put('CorrectAnswers',0); 
                mapOtherData.put('ReactionTime',0);
                
            }
        }
        Contact objCon = [SELECT Sex__c,Age__c,Education_Attainment__c FROM Contact WHERE Id=:contactId ];
        System.debug('contactId: '+contactId+ ' ,age: '+ objCon.Age__c);
        Decimal age = objCon.Age__c;
        age = age == null ? 18 : age;
        age = age < 18 ? 18 : age;
        age = age > 90 ? 90 : age;
        Decimal edu_att = objCon.Education_Attainment__c;
        edu_att = edu_att == null ? 1 : edu_att;
      //  edu_att = edu_att <= 2 ? 3 : edu_att;
      //  String sexData = objCon.Sex__c;
     //   sexData = sexData == '' ? 'Female' : sexData;
      //  sexData = sexData == null ? 'Female' : sexData;

        List<People_Like_You_Data__c> objLikeYouList = [SELECT Education__c,Sex__c, Age__c,Average__c,High_Average__c,Low_Average__c,Game_Name__r.Max_Score__c
            FROM People_Like_You_Data__c
            WHERE Game_Name__r.Name =:gameName 
            AND Sex__c =:objCon.Sex__c AND Education__c>=: edu_att
            AND Age__c =:age Order BY Education__c ASC LIMIT 1];
            for(People_Like_You_Data__c peopleLikeYouData : objLikeYouList){
                //People_Like_You_Data__c peopleLikeYouData=new People_Like_You_Data__c();
                mapOtherData.put ('People Like You', Integer.valueOf(peopleLikeYouData.Average__c));
                mapPlyAverageValuesData.put ('LowAverage', Integer.valueOf(peopleLikeYouData.Low_Average__c));
                mapPlyAverageValuesData.put ('HighAverage', Integer.valueOf(peopleLikeYouData.High_Average__c));
                mapPlyAverageValuesData.put ('MaxValue', Integer.valueOf(peopleLikeYouData.Game_Name__r.Max_Score__c));
                System.debug('People Like You');          
            }      
            
        
        // for(People_Like_You_Data__c objLikeYou : [SELECT Education__c,Sex__c, Age__c,Average__c,High_Average__c,Low_Average__c,Game_Name__r.Max_Score__c
        //                                           FROM People_Like_You_Data__c
        //                                           WHERE Game_Name__r.Name =:gameName 
        //                                           AND Sex__c =:objCon.Sex__c AND Education__c =: objCon.Education_Attainment__c
        //                                           AND Age__c =: objCon.Age__c])
        // {
            
        //     if(String.isNotblank(objCon.Sex__c)  
        //        && objCon.Education_Attainment__c != null
        //        && null !=  objCon.Age__c 
        //       )
        //     {
                
        //         mapOtherData.put ('People Like You', Integer.valueOf(objLikeYou.Average__c));
        //         mapPlyAverageValuesData.put ('LowAverage', Integer.valueOf(objLikeYou.Low_Average__c));
        //         mapPlyAverageValuesData.put ('HighAverage', Integer.valueOf(objLikeYou.High_Average__c));
        //         mapPlyAverageValuesData.put ('MaxValue', Integer.valueOf(objLikeYou.Game_Name__r.Max_Score__c));
        //         System.debug('People Like You');
        //     }
            
        // } 
        // for(People_Like_You_Data__c objLikeYou1 : [SELECT Education__c,Sex__c, Age__c,Average__c,High_Average__c,Low_Average__c,Game_Name__r.Max_Score__c
        //                                            FROM People_Like_You_Data__c
        //                                            WHERE Game_Name__r.Name =:gameName 
        //                                            AND Sex__c =:objCon.Sex__c AND Education__c =: objCon.Education_Attainment__c
        //                                            AND Age__c =: 18]) 
        // {
        //     //System.debug('Age<18 contactId: '+contactId+ ' ,age: '+ objCon.Age__c);
            
        //     if(objCon.Age__c <18)
        //     {
        //         mapOtherData.put ('People Like You', Integer.valueOf(objLikeYou1.Average__c));
        //         mapPlyAverageValuesData.put ('LowAverage', Integer.valueOf(objLikeYou1.Low_Average__c));
        //         mapPlyAverageValuesData.put ('HighAverage', Integer.valueOf(objLikeYou1.High_Average__c));
        //         mapPlyAverageValuesData.put ('MaxValue', Integer.valueOf(objLikeYou1.Game_Name__r.Max_Score__c));
        //     }
        // }
        //     for(People_Like_You_Data__c objLikeYou2 : [SELECT Education__c,Sex__c, Age__c,Average__c,High_Average__c,Low_Average__c,Game_Name__r.Max_Score__c
        //                                                FROM People_Like_You_Data__c
        //                                                WHERE Game_Name__r.Name =:gameName 
        //                                                AND Sex__c =:objCon.Sex__c AND Education__c =: objCon.Education_Attainment__c
        //                                                AND Age__c =: 90]) 
        //     {   
        //         //System.debug('Age>90 contactId: '+contactId+ ' ,age: '+ objCon.Age__c);
        //         if(objCon.Age__c >90)
        //         {               
        //             mapOtherData.put ('People Like You', Integer.valueOf(objLikeYou2.Average__c));
        //             mapPlyAverageValuesData.put ('LowAverage', Integer.valueOf(objLikeYou2.Low_Average__c));
        //             mapPlyAverageValuesData.put ('HighAverage', Integer.valueOf(objLikeYou2.High_Average__c));
        //             mapPlyAverageValuesData.put ('MaxValue', Integer.valueOf(objLikeYou2.Game_Name__r.Max_Score__c));
                    
        //         }
        //     }
        
        /*for(Participant_Dashboard__c objDashboard:[SELECT Data_Name__c,Data_Category__c, Data_Value__c 
                                                   FROM Participant_Dashboard__c 
                                                   WHERE Data_Name__c ='Overall Average'
                                                   AND Game_Detail__r.Name =:gameName
                                                  ])
        {
            mapOtherData.put('Overall Average', Integer.valueOf(objDashboard.Data_Value__c));
            System.debug('Overall Average');  
        }*/
         mapOtherData.put('Overall Average', overaallAvgMap.get(gameName));
        
        objDashboardData.mapOtherData = mapOtherData;
        // objDashboardData.age = objCon.Age__c != null ?Integer.valueOf(objCon.Age__c):null;
        // objDashboardData.mapWhatHappendWithAgeData = mapWhatHappendWithAgeData;
        objDashboardData.mapPlyAverageValuesData = mapPlyAverageValuesData;
        return objDashboardData;
    }
        @AuraEnabled 
    public static void saveSign(String base64Data, String contentType, String currentUserId, String gameName) {
        List<Participant_Game_Info__c> lstPartGameInfo=[SELECT Id, Game_Name__c, participantFeatureImageURL__c, Contact_Name__c, Game_Play_Status__c FROM Participant_Game_Info__c Where Participant_Game_Info__c.Contact_Name__c=:currentUserId];  
        List<ContentDocument> condocvar=new List<ContentDocument>();
        List<Participant_Game_Info__c> updateListPaticipantGameInfo =new List<Participant_Game_Info__c>();
         for(Participant_Game_Info__c objDashboard:lstPartGameInfo)
         {
            Game_Detail__c gName=[SELECT Name, Id FROM Game_Detail__c where id=:objDashboard.Game_Name__c];  
           // ContentDocumentLink checkDocLink=[SELECT ContentDocumentId, LinkedEntityId FROM ContentDocumentLink where LinkedEntityId=:objDashboard.Id LIMIT 1];
            if((gName.Name==gameName) && (objDashboard.participantFeatureImageURL__c==null || objDashboard.participantFeatureImageURL__c=='')){
                    // String yourFiles = 'Lets assume this is your binary string of the files';
                    ContentVersion conVer = new ContentVersion();
                    conVer.ContentLocation = 'S'; // S specify this document is in SF, use E for external files
                    conVer.PathOnClient = contentType;//'ionicLogo1.png'; // The files name, extension is very important here which will help the file in preview.
                    conVer.Title = gameName +'.png'; // Display name of the files
                    conVer.VersionData =  EncodingUtil.base64Decode(base64Data); //EncodingUtil.base64Decode(base64Data); // converting your binary string to Blog
                    insert conVer;
                    //Get Content Documents
                    Id conDoc = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:conVer.Id].ContentDocumentId;
                    //Create ContentDocumentLink
                    ContentDocumentLink cDe = new ContentDocumentLink();
                    cDe.ContentDocumentId = conDoc;
                    cDe.LinkedEntityId = objDashboard.Id; // you can use objectId,GroupId etc
                    cDe.ShareType = 'I'; // Inferred permission, checkout description of ContentDocumentLink object for more details
                    //cDe.Visibility = 'InternalUsers';
                    cDe.Visibility = 'AllUsers';
                    insert cDe;
                    //Create ContentDistribution
                    system.debug('conVer.Title 1:'+conVer.Title);
                    system.debug('conVer.Id:'+conVer.Id);
                    Participant_Game_Info__c partiGameInfo=[SELECT Id, Game_Name__c,participantFeatureImageURL__c, Contact_Name__c, Game_Play_Status__c FROM Participant_Game_Info__c where Id=:objDashboard.id];
                    partiGameInfo.participantFeatureImageURL__c=conDoc;
                    update partiGameInfo;
                    system.debug('partiGameInfo:'+partiGameInfo);  
                    updateListPaticipantGameInfo.add(partiGameInfo);
            }
         }
         //update updateListPaticipantGameInfo;
     }
    public class DashboardData
    {
        @AuraEnabled
        public Map<String, Integer> mapOtherData;
        /* @AuraEnabled
        public Integer age;
        @AuraEnabled
        public Map<String, Integer> mapWhatHappendWithAgeData; */
        @AuraEnabled
        public Map<String,Integer> mapPlyAverageValuesData;     
    }
  
}