objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Deary_Simple_And_Complex_Reaction_Time__c</fullName>
        <label>Deary Simple And Complex Reaction Time</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Face_Name_Associates__c</fullName>
        <label>Face-Name Associates</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Flanker__c</fullName>
        <label>Flanker</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Test-taker gender.</description>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Transgender Male</fullName>
                </value>
                <value>
                    <fullName>Transgender Female</fullName>
                </value>
                <value>
                    <fullName>Gender Variant/Non-Conforming</fullName>
                </value>
                <value>
                    <fullName>Not Listed</fullName>
                </value>
                <value>
                    <fullName>Prefer Not to Answer</fullName>
                </value>
                <value>
                    <fullName>Not Listed (Free Text Field)</fullName>
                    <isActive>false</isActive>
                    <label>Not Listed (Free Text Field)</label>
                </value>
                <value>
                    <fullName>Not Listed(Free Text Field)</fullName>
                    <isActive>false</isActive>
                    <label>Not Listed(Free Text Field)</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Keep_Track__c</fullName>
        <label>Keep Track</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>Language selected by test-taker at public application.</description>
        <inlineHelpText>If you are multi-lingual you may want to select the language that you are most fluent in</inlineHelpText>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                </value>
                <value>
                    <fullName>Español</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Letter_Number_Sequencing__c</fullName>
        <label>Letter-Number Sequencing</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Most_fluent_language__c</fullName>
        <description>Language in which test-taker is most fluent</description>
        <label>Most fluent language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                    <label>Español</label>
                </value>
                <value>
                    <fullName>Afrikaans</fullName>
                </value>
                <value>
                    <fullName>Arabia</fullName>
                    <label>العربية</label>
                </value>
                <value>
                    <fullName>Bulgarian</fullName>
                    <label>Български</label>
                </value>
                <value>
                    <fullName>Catalan; Valencia</fullName>
                    <label>Català  valencià</label>
                </value>
                <value>
                    <fullName>Czech</fullName>
                    <label>Čeština</label>
                </value>
                <value>
                    <fullName>Welsh</fullName>
                    <label>Cymraeg</label>
                </value>
                <value>
                    <fullName>Dansk</fullName>
                </value>
                <value>
                    <fullName>Deutsch</fullName>
                </value>
                <value>
                    <fullName>Greek</fullName>
                    <label>Ελληνικά</label>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                    <label>Eesti</label>
                </value>
                <value>
                    <fullName>Basque</fullName>
                    <label>Euskara</label>
                </value>
                <value>
                    <fullName>Persian</fullName>
                    <label>فارسی</label>
                </value>
                <value>
                    <fullName>Finnish</fullName>
                    <label>Suomi</label>
                </value>
                <value>
                    <fullName>French</fullName>
                    <label>Français</label>
                </value>
                <value>
                    <fullName>Irish</fullName>
                    <label>Gaeilge</label>
                </value>
                <value>
                    <fullName>Gujarati</fullName>
                    <label>ગુજરાતી</label>
                </value>
                <value>
                    <fullName>Abrit</fullName>
                    <label>עברית</label>
                </value>
                <value>
                    <fullName>Hindi</fullName>
                    <label>हिंदी</label>
                </value>
                <value>
                    <fullName>Croatian</fullName>
                    <label>Hrvatski</label>
                </value>
                <value>
                    <fullName>Hungarian</fullName>
                    <label>Magyar</label>
                </value>
                <value>
                    <fullName>Indonesian</fullName>
                    <label>Bahasa Indonesia</label>
                </value>
                <value>
                    <fullName>Icelandic</fullName>
                    <label>Íslenska</label>
                </value>
                <value>
                    <fullName>Italian</fullName>
                    <label>Italiano</label>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                    <label>日本語</label>
                </value>
                <value>
                    <fullName>Korean</fullName>
                    <label>한국어</label>
                </value>
                <value>
                    <fullName>Latvian</fullName>
                    <label>Latviešu</label>
                </value>
                <value>
                    <fullName>Lithuanian</fullName>
                    <label>Lietuvių</label>
                </value>
                <value>
                    <fullName>Malayalam</fullName>
                    <label>മലയാളം</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_daily_medications__c</fullName>
        <description>Number of time test-taker takes medication in a day.</description>
        <label>Number of daily medications</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>One</fullName>
                </value>
                <value>
                    <fullName>Two</fullName>
                </value>
                <value>
                    <fullName>Three</fullName>
                </value>
                <value>
                    <fullName>More than three</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_fluent_languages_spoken__c</fullName>
        <description>Number of  languages spoken by test-taker</description>
        <label>Number of fluent languages spoken</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_fluent_languages_written__c</fullName>
        <description>Number of languages which test-taker can write fluently</description>
        <label>Number of fluent languages written</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_Recognition_And_Similarity__c</fullName>
        <label>Object Recognition And Similarity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Verbal_Paired_Associates__c</fullName>
        <label>Verbal Paired Associates</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opened</fullName>
                    <default>true</default>
                    <label>Unlocked</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CustomLoginController.cls
/*
*
@author            : Vicky kumar
@last modified on  : 06-05-2021
@modified by       : Shweta Khunteta
@description       : This is the Footer for the Research Guest/Community Login User.
@test class        : CustomLoginControllerTest
*  
*/

public with sharing class CustomLoginController {
    
    @AuraEnabled(cacheable=true)
    public static User getCurrentUser(){
        User u = [SELECT firstname,  ContactId, Profile.Name FROM User where id=:userinfo.getuserid()];
        
        return u;
    }
    @AuraEnabled
    public static Boolean upsertContact1(Contact con)
    {     
        
        try
        {         
            if(con!=null)
            {
                update con;   
                User currUser =[SELECT Username, Email, ContactId, Id FROM User Where ContactId=:con.id];
                if(currUser!=null){
                    currUser.Email=con.Email;
                    update currUser;
                }
                return true;
            }       
        } 
        catch (Exception e) 
        {
            System.debug('updateUsersFULL CONTACT error: ' + e.getMessage());
        } 
        return false;       
    }
    
    @AuraEnabled(cacheable=true)
    public static string  changePassword(String newPassword,string confirmNewPassword, String oldPassword){
        try{
            Pagereference qr= site.changePassword(newPassword,confirmNewPassword,oldPassword);
            System.debug('Pagereff :'+qr);
            if (qr != null) {
                return 'SUCCESS';
            } else {
                return null;
            }
        }
        catch (Exception ex) {
            System.debug(ex.getMessage());
            return null;
        }  
    }
    
    @AuraEnabled(cacheable=true)
    public static List<FeedItem> getFeedItem(){
        List<FeedItem> feeds=[Select id,body from FeedItem where parentId=:UserInfo.getUserId()];
        return feeds;
    }
    @AuraEnabled(cacheable=true)
    public static boolean getCurrentProfile(){
        Boolean communityUserProfile=false;
        Id profileId=userinfo.getProfileId();
        String profileName=[Select Id,Name from Profile where Id=:profileId].Name;
        system.debug('ProfileName'+profileName);
        if(profileName=='Customer Community Login User'){
            communityUserProfile=true;
        }
        return communityUserProfile;
    }
    
    @AuraEnabled(cacheable=true)
    public static Contact getCurrentContact()
    {
        User u = [SELECT firstname,  ContactId, Profile.Name FROM User where id=:userinfo.getuserid()];
        Contact con= new Contact();
        if(u!=null && u.ContactId!=null)
        {
            con=[SELECT Email,Phone,FirstName,LastName,Language__c,Deary_Simple_And_Complex_Reaction_Time__c
                     ,Verbal_Paired_Associates__c
                     ,Object_Recognition_And_Similarity__c
                     ,Flanker__c,Number_of_daily_medications__c,Gender__c
                     ,Face_Name_Associates__c,Most_fluent_language__c
                     ,Letter_Number_Sequencing__c,Number_of_fluent_languages_written__c
                     ,Keep_Track__c,Number_of_fluent_languages_spoken__c
                     ,Object_Discrimination__c,Object_Temporal__c,Object_Spatial__c,MailingCity,MailingCountryCode,
                     MailingStreet,MailingStateCode,MailingPostalCode,Sex__c,Second_degree_family_history_of_AD__c,
                     First_degree_family_history_of_AD__c,First_degree_family_history_of_EO_AD__c,Age_at_second_spoken_language__c,
                     Health_Lifestyle_and_Medical__c ,Highest_level_of_education_completed__c FROM Contact where id=:u.ContactId];
        }
        return con;
    }
    //Added by Sibi on 28 Feb 2023 for TSS-31-Enable games in mobile based on Zip Codes
    @AuraEnabled
    public static Boolean restrictExpandedGames(String Zipcode){
        Boolean restrictGames = false;
        List<Zipcodes__mdt> Zipcodes = [SELECT Id FROM Zipcodes__mdt WHERE Zipcode__c = :Zipcode];
        if(Zipcodes !=null && Zipcodes.size()>0)
        {
            restrictGames = true;
        }     
        return restrictGames;
    }
}