objects/Game_Detail__c.object
<CustomObject>
    <description>This object is having game information and dependency for other game.</description>
    <label>Game Detail</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Game Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Participant_Game_Info__c.object
<CustomObject>
    <description>This object is having details of the participant&apos;s game.</description>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to contact, saving contact id, will show contact name at front-end.</description>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Participant Game Infos</relationshipLabel>
        <relationshipName>Participant_Game_Infos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Game_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to game, saving game id, will show game name at front-end.</description>
        <label>Game Name</label>
        <referenceTo>Game_Detail__c</referenceTo>
        <relationshipLabel>Participant Game Infos</relationshipLabel>
        <relationshipName>Participant_Game_Infos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Game_Play_Status__c</fullName>
        <label>Game Play Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not-Completed</fullName>
                    <default>true</default>
                    <label>Not-Completed</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>participantFeatureImageURL__c</fullName>
        <label>participantFeatureImageURL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Participant Game Info</label>
    <nameField>
        <displayFormat>PGI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Game Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/attentionshareController_Test.cls
/*
    @Author          :  Sunil Singh
    @Descriptoin     :  Test class for attentinshareController.
    
*/
@isTest
public class attentionshareController_Test{

    public static testMethod void unitTest(){
        
        Contact con = new Contact();
        con.LastName= 'test last name';
        con.Email = 'Test@test.com';
        Insert con;        
        
        Game_Detail__c gd = new Game_Detail__c();
        gd.Name ='DLTRS';       
        insert gd;
        
        Participant_Game_Info__c pg = new Participant_Game_Info__c();
        pg.Contact_Name__c = con.Id;
        pg.Game_Name__c = gd.Id;
        pg.Game_Play_Status__c = 'Completed';
        pg.participantFeatureImageURL__c = '069XXXXXXXX';
        insert pg;
        
        ApexPages.CurrentPage().getParameters().put('id', con.Id);
        ApexPages.CurrentPage().getParameters().put('gameName','DLTRS');
        
        
        attentinshareController cntrl = new attentinshareController();
        system.assertEquals('069XXXXXXXX', cntrl.contentDocumentId);
        
    }
}