objects/Game_Detail__c.object
<CustomObject>
    <description>This object is having game information and dependency for other game.</description>
    <fields>
        <fullName>Reactivation_Days__c</fullName>
        <description>After how many days, game will be re-activated for a user.</description>
        <label>Reactivation Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Game Detail</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Game Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/IpAddressData__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This &quot;IpAddressData&quot; custom setting is used for getting the IPAddress related data from user side.</description>
    <fields>
        <fullName>apiKey__c</fullName>
        <description>This field is used for &quot;api-key&quot; value.</description>
        <label>apiKey</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>url__c</fullName>
        <label>url</label>
        <length>56</length>
        <type>Text</type>
    </fields>
    <label>IpAddressData</label>
</CustomObject>

objects/Participant_Game_Info__c.object
<CustomObject>
    <description>This object is having details of the participant&apos;s game.</description>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to contact, saving contact id, will show contact name at front-end.</description>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Participant Game Infos</relationshipLabel>
        <relationshipName>Participant_Game_Infos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Game_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to game, saving game id, will show game name at front-end.</description>
        <label>Game Name</label>
        <referenceTo>Game_Detail__c</referenceTo>
        <relationshipLabel>Participant Game Infos</relationshipLabel>
        <relationshipName>Participant_Game_Infos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IP_Address__c</fullName>
        <label>IP Address</label>
        <length>56</length>
        <type>Text</type>
    </fields>
    <label>Participant Game Info</label>
    <nameField>
        <displayFormat>PGI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Game Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BatchUpdatePGI_Test.cls
// Created By: {Girikon(Sunil kumar)}
// Created On: 08/09/2022
// Description/Purpose: test class for testing BatchUpdatePGI
// Apex Class: {BatchOfGames}
@isTest
public with sharing class BatchUpdatePGI_Test {
    Static testMethod void testBatchExecuteMethod()
    { 
        Account acc=new Account();
        acc.Name='Test Account';
        insert acc;
        Contact con=new Contact();
        con.FirstName='Test';
        con.LastName='Contact';
        con.AccountId=acc.Id;
        insert con;
        Game_Detail__c gd=new Game_Detail__c();
        gd.Name='DLTRS';
        gd.Reactivation_Days__c=365;
        insert gd;
       
        Participant_Game_Info__c insertPGI=new Participant_Game_Info__c();
        insertPGI.Contact_Name__c=con.Id;
        insertPGI.IP_Address__c='103.147.0.90';
        insertPGI.Game_Name__c=gd.Id;
        insert insertPGI;
         IpAddressData__c IPD= new IpAddressData__c();
        IPD.Name='userOne';
        IPD.apiKey__c='8289ac328847197b92c5fa681c2168959470f6c0345d44c353e3cccd';
        IPD.url__c='https://api.ipdata.co/';
        insert IPD;
        String ipAddre='103.147.0.90';

        Map<String, Object> results=new Map<String, Object>();
        results.put('ID',insertPGI.Id);

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        BatchUpdatePGI buPgi = new BatchUpdatePGI();
        database.executeBatch(buPgi);
        Test.stopTest();

     }
}