objects/Game_Detail__c.object
<CustomObject>
    <description>This object is having game information and dependency for other game.</description>
    <label>Game Detail</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Game Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Participant_Game_Info__c.object
<CustomObject>
    <description>This object is having details of the participant&apos;s game.</description>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to contact, saving contact id, will show contact name at front-end.</description>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Participant Game Infos</relationshipLabel>
        <relationshipName>Participant_Game_Infos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Game_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to game, saving game id, will show game name at front-end.</description>
        <label>Game Name</label>
        <referenceTo>Game_Detail__c</referenceTo>
        <relationshipLabel>Participant Game Infos</relationshipLabel>
        <relationshipName>Participant_Game_Infos</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Participant Game Info</label>
    <nameField>
        <displayFormat>PGI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Game Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BatchClassSpeechTaskUnlock.cls
global class BatchClassSpeechTaskUnlock implements Database.Batchable<SObject>, Schedulable {
    
    global void execute(SchedulableContext sc) {
        BatchClassSpeechTaskUnlock SpeechTaskUn = new BatchClassSpeechTaskUnlock();
        Database.executeBatch(SpeechTaskUn);
    }

    // Step - 1: Get All the Bean Game records / contacts
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([Select id, Game_Name__r.Name,Contact_Name__r.Id, Contact_Name__c, Game_Name__c
										FROM Participant_Game_Info__c 
										WHERE Game_Name__r.Name = 'Speech Tasks' AND CreatedDate = N_DAYS_AGO:365]);
    }

    global void execute(Database.BatchableContext bc, List<Participant_Game_Info__c> scope) {
        // Step - 2: In the execute method, get All unique contact Ids from scope and store in the below variable List<Id> contIds;

        Set<Id> contactIds = new Set<Id>();
        for (Participant_Game_Info__c pgi : scope) {
            contactIds.add(pgi.Contact_Name__r.id);
        }

        // Step - 3: Run a query to get all contacts with all 10 game status fields using above contactIds
        List<Id> contIds = new List<Id>(contactIds); // Changed from Set to List
        List<Contact> contUpd = [SELECT Id, Speech_Task__c FROM Contact WHERE Id IN :contIds];

        // Step - 4: Update the contacts
        for (Participant_Game_Info__c pgi : scope) {
            for (Contact con : contUpd) {
                if (con.Id == pgi.Contact_Name__r.id) {
                    if (con.Speech_Task__c != 'Opened') {
                        con.Speech_Task__c = 'Opened';
                    }
                }
            }
        }

        // Update the contacts after processing the Bean Game records
        database.update(contUpd);
    }

    global void finish(Database.BatchableContext context) {
        System.debug('---IN FINISH');
    }
}