objects/Game_Detail__c.object
<CustomObject>
    <description>This object is having game information and dependency for other game.</description>
    <label>Game Detail</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Game Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Participant_Game_Info__c.object
<CustomObject>
    <description>This object is having details of the participant&apos;s game.</description>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to contact, saving contact id, will show contact name at front-end.</description>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Participant Game Infos</relationshipLabel>
        <relationshipName>Participant_Game_Infos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Game_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to game, saving game id, will show game name at front-end.</description>
        <label>Game Name</label>
        <referenceTo>Game_Detail__c</referenceTo>
        <relationshipLabel>Participant Game Infos</relationshipLabel>
        <relationshipName>Participant_Game_Infos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Game_Play_Status__c</fullName>
        <label>Game Play Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not-Completed</fullName>
                    <default>true</default>
                    <label>Not-Completed</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Participant Game Info</label>
    <nameField>
        <displayFormat>PGI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Game Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Research_Campaign__c.object
<CustomObject>
    <description>It consists of the campaigns type of mindcrowd like Covid, DBS, Bean game</description>
    <fields>
        <fullName>Usps_Service_Type__c</fullName>
        <description>service which the Mindcrowd team uses TO send their parcels through USPS</description>
        <label>Usps Service Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FIRST CLASS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Weight_in_Ounces__c</fullName>
        <description>It consists of weight of each campaign type</description>
        <label>Weight in Ounces</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Research Campaign</label>
    <nameField>
        <label>Research Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Shipping_Detail__c.object
<CustomObject>
    <description>This Object comprises of all the fields which are related to shipment process.</description>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field has a mandatory lookup to ResearchCampaign object.</description>
        <label>Campaign</label>
        <referenceTo>Research_Campaign__c</referenceTo>
        <relationshipLabel>Shipping Details</relationshipLabel>
        <relationshipName>Shipping_Details</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Id__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>A mandatory look up field to contact so that every shipment has a contact linked to it.</description>
        <label>Contact Id</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Shipping Details</relationshipLabel>
        <relationshipName>Shipping_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment_Status__c</fullName>
        <description>This field is used to track whether the shipment is created, sent to the participant or received by the Mindcrowd team.</description>
        <label>Shipment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Consented</fullName>
                    <default>true</default>
                    <label>Consented</label>
                </value>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Invalid Address</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Shipping Detail</label>
    <nameField>
        <displayFormat>SD-{00000000}</displayFormat>
        <label>Shipping Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AdminDashBoardcontrollerTest.cls
@isTest
public class AdminDashBoardcontrollerTest 
{
    @isTest
    private static void getGroupChartMapTest()
    {
        Contact c = new Contact();
        c.LastName= 'test last name';
        c.Email = 'Test@test.com';
        Insert c;
        
        Research_Campaign__c res= new Research_Campaign__c();
        res.Name='Covid';
        res.Weight_in_Ounces__c=3;
        res.Usps_Service_Type__c='FIRST CLASS';
        insert res;
        
        Shipping_Detail__c sdc =new Shipping_Detail__c();
        sdc.Shipment_Status__c='Sent';
        sdc.Campaign__c=res.Id;
        sdc.Contact_Id__c=c.Id;
        insert sdc;
        
        Shipping_Detail__c sdc1=new Shipping_Detail__c();
        sdc1.Shipment_Status__c='Created';
        sdc1.Campaign__c=res.Id;
        sdc1.Contact_Id__c=c.Id;
        insert sdc1;
        AdminDashBoardcontroller.getResearchCampaigns();
        AdminDashBoardcontroller.getGroupChartMap(Date.Today().addDays(-30), Date.Today().addDays(2), res.Id);
        AdminDashBoardcontroller.getGroupChartMap(Date.Today().addDays(-30), Date.Today().addDays(2), res.Id);  
        
    }
    
    @isTest
    private static void getOtherGroupChartMap()
    {
        Game_Detail__c gd = new Game_Detail__c();
        gd.Name ='DLTRS';       
        insert gd;
        
        Contact co = new Contact();
        co.Email = 'test@test.com';
        co.LastName = 'test1';
        insert co;
        Participant_Game_Info__c pg = new Participant_Game_Info__c();
        pg.Contact_Name__c = co.Id;
        pg.Game_Name__c = gd.Id;
        pg.Game_Play_Status__c = 'Completed';
        insert pg;
        //AdminDashBoardcontroller.getOtherGroupChartMap(Date.Today().addDays(-30), Date.Today().addDays(1));
        Participant_Game_Info__c pg1 = new Participant_Game_Info__c();
        pg1.Game_Play_Status__c = 'Not-Completed';
        pg1.Contact_Name__c = co.Id;
        pg1.Game_Name__c = gd.Id;
        insert pg1;     
     AdminDashBoardcontroller.getOtherGroupChartMap(Date.Today().addDays(-30), Date.Today().addDays(2));
    }
}