objects/Game_Detail__c.object
<CustomObject>
    <description>This object is having game information and dependency for other game.</description>
    <label>Game Detail</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Game Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Participant_Game_Info__c.object
<CustomObject>
    <description>This object is having details of the participant&apos;s game.</description>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to contact, saving contact id, will show contact name at front-end.</description>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Participant Game Infos</relationshipLabel>
        <relationshipName>Participant_Game_Infos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Game_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to game, saving game id, will show game name at front-end.</description>
        <label>Game Name</label>
        <referenceTo>Game_Detail__c</referenceTo>
        <relationshipLabel>Participant Game Infos</relationshipLabel>
        <relationshipName>Participant_Game_Infos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>participantFeatureImageURL__c</fullName>
        <label>participantFeatureImageURL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Participant Game Info</label>
    <nameField>
        <displayFormat>PGI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Game Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/attentinshareController.cls
/*
    @Author          :  Raj Kumar
    @Descriptoin     :  This class will be used to show game image.
    
*/

public without sharing class attentinshareController {
    public String contentDocumentId {get;set;}
    public attentinshareController() {
        contentDocumentId = null; 
        String conId = ApexPages.CurrentPage().getParameters().get('id');
        String gameName ='DLTRS'; // ApexPages.CurrentPage().getParameters().get('gameName');
        
        for(Participant_Game_Info__c obj : [SELECT id,participantFeatureImageURL__c FROM Participant_Game_Info__c 
                                            WHERE Contact_Name__c =: conId AND Game_Name__r.Name =: gameName AND participantFeatureImageURL__c != null limit 1]){
            contentDocumentId = obj.participantFeatureImageURL__c;
        }
    }
}