objects/Integration_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This setting is used to keep the values for integration with USPS api</description>
    <fields>
        <fullName>USPS_URL__c</fullName>
        <description>It contains the API URL.</description>
        <label>USPS URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <description>This is the id given By USPS to Mindcrowd .</description>
        <label>UserId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Integration Settings</label>
</CustomObject>

objects/Research_Campaign__c.object
<CustomObject>
    <description>It consists of the campaigns type of mindcrowd like Covid, DBS, Bean game</description>
    <fields>
        <fullName>Usps_Service_Type__c</fullName>
        <description>service which the Mindcrowd team uses TO send their parcels through USPS</description>
        <label>Usps Service Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FIRST CLASS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Weight_in_Ounces__c</fullName>
        <description>It consists of weight of each campaign type</description>
        <label>Weight in Ounces</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Research Campaign</label>
    <nameField>
        <label>Research Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Shipping_Detail__c.object
<CustomObject>
    <description>This Object comprises of all the fields which are related to shipment process.</description>
    <fields>
        <fullName>Barcode__c</fullName>
        <formula>IF(DATEVALUE(CreatedDate) &lt; DATEVALUE( &quot;2022-09-01&quot; ), &apos;SM&apos;+ MID( Id ,10,2)+ &apos;BA&apos;+RIGHT(Id,4)+&apos;CD&apos;,   Name )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Barcode</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field has a mandatory lookup to ResearchCampaign object.</description>
        <label>Campaign</label>
        <referenceTo>Research_Campaign__c</referenceTo>
        <relationshipLabel>Shipping Details</relationshipLabel>
        <relationshipName>Shipping_Details</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Id__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>A mandatory look up field to contact so that every shipment has a contact linked to it.</description>
        <label>Contact Id</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Shipping Details</relationshipLabel>
        <relationshipName>Shipping_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <description>This field shows the price of each shipment.</description>
        <label>Price</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Return_TrackingId__c</fullName>
        <description>This Id consists of returning track id</description>
        <label>Return TrackingId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipment_Status__c</fullName>
        <description>This field is used to track whether the shipment is created, sent to the participant or received by the Mindcrowd team.</description>
        <label>Shipment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Consented</fullName>
                    <default>true</default>
                    <label>Consented</label>
                </value>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Invalid Address</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tracking_Id__c</fullName>
        <description>This field comprises of the tracking number provided by USPS for tracking the shipments</description>
        <label>Tracking Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>USPSLabelImage__c</fullName>
        <description>It contains the label image IN TEXT format returned by USPS Label API</description>
        <label>USPSLabelImage</label>
        <length>131070</length>
        <type>LongTextArea</type>
    </fields>
    <label>Shipping Detail</label>
    <nameField>
        <displayFormat>SD-{00000000}</displayFormat>
        <label>Shipping Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BatchTrackShipmentTest.cls
// Created By: {Girikon(Shweta Khunteta)}
// Created On: 24/08/2021(DD/MM/YYYY)
// Description/Purpose: test class for testing BatchTrackShipment
// Methods: {Methods name in class}
// Apex Class: {BatchTrackShipment}


@isTest
public with sharing class BatchTrackShipmentTest 
{
    
    @testSetup static void setup() 
    {
        
        Integration_Settings__c ints1 = new Integration_Settings__c();
        ints1.Name='test';
        ints1.UserId__c='548GIRIK0509';
        ints1.USPS_URL__c='https://secure.shippingapis.com/ShippingAPI.dll';
        insert ints1;
        TrackShipment.integrationsettings=ints1;
        List<Contact> testContact = new List<Contact>();
        for(Integer i=0;i<1;i++) 
        {
            testContact.add(new Contact (LastName = 'TestContact'+i));
        }
        insert testContact; 
        Research_Campaign__c res= new Research_Campaign__c();
            res.Name='Covid';
            res.Weight_in_Ounces__c=3;
            res.Usps_Service_Type__c='FIRST CLASS';
            insert res;
        Shipping_Detail__c testShipping1 = new Shipping_Detail__c();
        
            testShipping1.Campaign__c=res.Id;
            testShipping1.Contact_Id__c=testContact[0].id;
            testShipping1.Tracking_Id__c='9400111298370071281345';
            testShipping1.Return_TrackingId__c='LY715967151CN';
            testShipping1.Shipment_Status__c='Sent'; 
            testShipping1.Price__c=3.0;
            testShipping1.USPSLabelImage__c='dffddfdkjfdjfkdfjdkfjdkfdjkfkdj';

            List<Shipping_Detail__c> myList = new List<Shipping_Detail__c>();
            myList.add(testShipping1);
            insert myList; 
            myList = [select Id, Name,Barcode__c from Shipping_Detail__c];
        }
 @isTest
public static void testBatch()
{
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new  TrackHttpCallOutTest());
        BatchTrackShipment obj = new BatchTrackShipment();
        DataBase.executeBatch(obj); 
        Test.stopTest();
}

        
       
}