objects/Integration_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This setting is used to keep the values for integration with USPS api</description>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Image_Parameters__c</fullName>
        <description>comprise of what type of label image needs to be created.</description>
        <label>Image Parameters</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Label_Service_Api__c</fullName>
        <label>Label Service Api</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MindCrowdAddress2__c</fullName>
        <description>It contains the mindcrowd Address2.</description>
        <label>MindCrowdAddress2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MindCrowdCity__c</fullName>
        <description>contains the city of mindcrowd office location.</description>
        <label>MindCrowdCity</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MindCrowdFirmName__c</fullName>
        <description>consists of mindcrowd firm name .</description>
        <label>MindCrowdFirmName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MindCrowdName__c</fullName>
        <label>MindCrowdName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MindCrowdPhone__c</fullName>
        <description>consists of phone number of mindcrowd</description>
        <label>MindCrowdPhone</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MindCrowdState__c</fullName>
        <description>contains the state of mindcrowd address.</description>
        <label>MindCrowdState</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MindCrowdZip5__c</fullName>
        <description>contains zip5 of mindcrowd address.</description>
        <label>MindCrowdZip5</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <description>This is the id given By USPS to Mindcrowd .</description>
        <label>UserId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>eVSLabelUrl__c</fullName>
        <description>USPS URL for generating eVS Label</description>
        <label>eVSLabelUrl</label>
        <type>Url</type>
    </fields>
    <label>Integration Settings</label>
</CustomObject>

objects/Research_Campaign__c.object
<CustomObject>
    <description>It consists of the campaigns type of mindcrowd like Covid, DBS, Bean game</description>
    <fields>
        <fullName>Usps_Service_Type__c</fullName>
        <description>service which the Mindcrowd team uses TO send their parcels through USPS</description>
        <label>Usps Service Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FIRST CLASS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Weight_in_Ounces__c</fullName>
        <description>It consists of weight of each campaign type</description>
        <label>Weight in Ounces</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>isReturnLabelNeeded__c</fullName>
        <defaultValue>false</defaultValue>
        <description>It tells whether the campaign requires return label or not</description>
        <label>isReturnLabelNeeded</label>
        <type>Checkbox</type>
    </fields>
    <label>Research Campaign</label>
    <nameField>
        <label>Research Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Shipping_Detail__c.object
<CustomObject>
    <description>This Object comprises of all the fields which are related to shipment process.</description>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <type>Address</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field has a mandatory lookup to ResearchCampaign object.</description>
        <label>Campaign</label>
        <referenceTo>Research_Campaign__c</referenceTo>
        <relationshipLabel>Shipping Details</relationshipLabel>
        <relationshipName>Shipping_Details</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Id__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>A mandatory look up field to contact so that every shipment has a contact linked to it.</description>
        <label>Contact Id</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Shipping Details</relationshipLabel>
        <relationshipName>Shipping_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment_Status__c</fullName>
        <description>This field is used to track whether the shipment is created, sent to the participant or received by the Mindcrowd team.</description>
        <label>Shipment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Consented</fullName>
                    <default>true</default>
                    <label>Consented</label>
                </value>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Invalid Address</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Shipping Detail</label>
    <nameField>
        <displayFormat>SD-{00000000}</displayFormat>
        <label>Shipping Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ShipmentLabelTest.cls
// Created By: {Girikon(ShwetaKhunteta)}
// Created On: 05/08/2021 (dd/mm/yyyy)
// Description/Purpose:created to test the ShipmentLabel class
// Methods: {getLabel}
// Apex Class: {ShipmentLabel)}
@isTest
public with sharing class ShipmentLabelTest 
{   
   @isTest
    public static void getLabelTest() 
    {    
        Integration_Settings__c ints1 = new Integration_Settings__c();
        ints1.Name='test';
        ints1.UserId__c='548GIRIK0509';
        ints1.Password__c = '752HH00UA860';
        ints1.Label_Service_Api__c='eVSCertify';
        ints1.eVSLabelUrl__c='https://stg-secure.shippingapis.com/ShippingAPI.dll';
        ints1.MindCrowdName__c='TGen headquarters';
        ints1.MindCrowdFirmName__c='TGen';
        ints1.MindCrowdAddress2__c='445 N 5TH ST';
        ints1.MindCrowdCity__c='Phoenix';
        ints1.MindCrowdState__c='AZ';
        ints1.MindCrowdZip5__c= 85004;
        //ints1.MindCrowdPhone__c='6023438400';
        ints1.Image_Parameters__c = '4X6LABELP';
        ints1.grant_type__c = 'client_credentials';
        ints1.client_id__c = 'clientId';
        ints1.client_secret__c = 'clientSecret';
        ints1.AccessToken_url__c = 'https://test.access.token';
        ints1.CRID__c = 'testCRID';
        ints1.Role_Name_P__c = 'payerRole';
        ints1.Role_Name_LO__c = 'labelOwnerRole';
        ints1.MID__c = 'testMID';
        ints1.Manifest_MID__c = 'testManifestMID';
        ints1.Account_Type__c = 'Business';
        ints1.Account_Number__c = '123456789';
        ints1.Payment_Access_Token_URL__c = 'https://test.payment.token';
        ints1.USPS_Label_API_URL__c = 'https://test.usps.label.api';
        ints1.Packaging_Type__c = 'Package';
        ints1.Processing_Category__c = 'Processing';
        insert ints1;
        ShipmentLabel.integrationsettings=ints1;
        
        Contact con= new Contact();
        con.FirstName='Adam';
        con.LastName='Smith';
        con.MailingStreet='PO Box 100';
        con.MailingCity='Washington';
        con.MailingStateCode='DC';
        con.MailingPostalCode='20260';
        insert con;
        System.debug(con);
        
        Research_Campaign__c res= new Research_Campaign__c();
        res.Name='Covid';
        res.Weight_in_Ounces__c=3;
        res.isReturnLabelNeeded__c=true;
        res.Usps_Service_Type__c='FIRST CLASS';
        insert res;
        
        List <Shipping_Detail__c> lstShipping = new List<Shipping_Detail__c>();
        Shipping_Detail__c testshippingbarcode = new Shipping_Detail__c();
        testshippingbarcode.Shipment_Status__c='Consented';
        testshippingbarcode.Campaign__c=res.Id;
        testshippingbarcode.Contact_Id__c=con.Id;
 
        Address ard=new Address();
           // ard.Address__Street__s='';
           // ard.Address__StateCode__s='';
           // ard.Address__CountryCode__s='';
           // ard.Address__City__s='';
           // ard.Address__PostalCode__s='';
           // insert ard;
       // testshippingbarcode.Address__c.add(ard);
        lstShipping.add(testshippingbarcode);
        System.debug(lstShipping);
        insert lstShipping;
        String strid=testshippingbarcode.Id;
        String stridConName= 'james';
 
        Map<String,Address> idAddressMap = new Map<String,Address>();
        Map<String,Research_Campaign__c> campaignTestMap = new Map<String,Research_Campaign__c>();
        Map<String,String> idContactName = new Map<String,String>();
        idAddressMap.put(strid,ard);
        campaignTestMap.put(strid,res);
        idContactName.put(strid,stridConName);
        
        Test.setMock(HttpCalloutMock.class, new LabelHttpCallOutMock());
        Test.StartTest();
        ShipmentLabel.getLabel(idAddressMap,campaignTestMap,idContactName);
        Test.StopTest();
    } 

    @isTest
    public static void testParseUSPSLabelResponseXML_Error() {
        // Sample XML for an error response
        String errorXML = '<?xml version="1.0"?>'
            + '<Error>'
            + '  <Number>123</Number>'
            + '  <Description>Invalid address</Description>'
            + '  <Source>AddressValidation</Source>'
            + '</Error>';

        // Call the method under test
        USPSLabel parsedLabel = ShipmentLabel.parseUSPSLabelResponseXML(errorXML, false);

        // Assertions
        System.assertEquals('123', parsedLabel.USPS_ERROR_CODE, 'Error code should match.');
        System.assertEquals('Invalid address', parsedLabel.USPS_ERROR_DESC, 'Error description should match.');
        System.assertEquals('AddressValidation', parsedLabel.USPS_ERROR_SOURCE, 'Error source should match.');
    }
    
}