objects/Integration_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This setting is used to keep the values for integration with USPS api</description>
    <fields>
        <fullName>MindCrowdAddress2__c</fullName>
        <description>It contains the mindcrowd Address2.</description>
        <label>MindCrowdAddress2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MindCrowdCity__c</fullName>
        <description>contains the city of mindcrowd office location.</description>
        <label>MindCrowdCity</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MindCrowdName__c</fullName>
        <label>MindCrowdName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MindCrowdState__c</fullName>
        <description>contains the state of mindcrowd address.</description>
        <label>MindCrowdState</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MindCrowdZip5__c</fullName>
        <description>contains zip5 of mindcrowd address.</description>
        <label>MindCrowdZip5</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Integration Settings</label>
</CustomObject>

objects/Shipping_Detail__c.object
<CustomObject>
    <description>This Object comprises of all the fields which are related to shipment process.</description>
    <fields>
        <fullName>Tracking_Id__c</fullName>
        <description>This field comprises of the tracking number provided by USPS for tracking the shipments</description>
        <label>Tracking Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>USPSLabelImage__c</fullName>
        <description>It contains the label image IN TEXT format returned by USPS Label API</description>
        <label>USPSLabelImage</label>
        <length>131070</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>USPSReturnLabelImage__c</fullName>
        <description>this field will hold the return label image returned by USPS EVS Label API.</description>
        <label>USPSReturnLabelImage</label>
        <length>131070</length>
        <type>LongTextArea</type>
    </fields>
    <label>Shipping Detail</label>
    <nameField>
        <displayFormat>SD-{00000000}</displayFormat>
        <label>Shipping Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PrintLabelController.cls
// Created By: {Girikon(Shweta Khunteta)}
// Created On: 06/08/2021
// Description/Purpose: Why and where it is used [TM-186]-It was created to  print the labels of      selectedShipping ids 
//
// 
// Methods: {doSomething}
// Test Class: {PrintLabelControllerTest} {Code Coverage:94%}

public with sharing class PrintLabelController 
{       
    public Integration_Settings__c customSettingAddress{get;set;}
    public List<Shipping_Detail__c> shippingDetailList{get;set;}
    
    public PrintLabelController(ApexPages.StandardSetController standardSetController) 
    {
        List<Shipping_Detail__c> selectedItems = standardSetController.getSelected();

        // List<Integration_Settings__c> isList = [SELECT Id, MindCrowdAddress2__c, MindCrowdCity__c,MindCrowdName__c,
        //                         MindCrowdState__c, MindCrowdZip5__c FROM Integration_Settings__c Where Name='Integration Settings' WITH SECURITY_ENFORCED];
        
        // customSettingAddress = new Integration_Settings__c();
        // if(!isList.isEmpty()){
        //     customSettingAddress = isList[0];
        // }

        shippingDetailList = [SELECT Id, USPSLabelImage__c,USPSReturnLabelImage__c FROM Shipping_Detail__c
                              WHERE Id IN :selectedItems AND Tracking_Id__c!=null WITH SECURITY_ENFORCED];                
    }
}