objects/Integration_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This setting is used to keep the values for integration with USPS api</description>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Image_Parameters__c</fullName>
        <description>comprise of what type of label image needs to be created.</description>
        <label>Image Parameters</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Label_Service_Api__c</fullName>
        <label>Label Service Api</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MindCrowdAddress2__c</fullName>
        <description>It contains the mindcrowd Address2.</description>
        <label>MindCrowdAddress2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MindCrowdCity__c</fullName>
        <description>contains the city of mindcrowd office location.</description>
        <label>MindCrowdCity</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MindCrowdFirmName__c</fullName>
        <description>consists of mindcrowd firm name .</description>
        <label>MindCrowdFirmName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MindCrowdName__c</fullName>
        <label>MindCrowdName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MindCrowdPhone__c</fullName>
        <description>consists of phone number of mindcrowd</description>
        <label>MindCrowdPhone</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MindCrowdState__c</fullName>
        <description>contains the state of mindcrowd address.</description>
        <label>MindCrowdState</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MindCrowdZip5__c</fullName>
        <description>contains zip5 of mindcrowd address.</description>
        <label>MindCrowdZip5</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <description>This is the id given By USPS to Mindcrowd .</description>
        <label>UserId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>eVSLabelUrl__c</fullName>
        <description>USPS URL for generating eVS Label</description>
        <label>eVSLabelUrl</label>
        <type>Url</type>
    </fields>
    <label>Integration Settings</label>
</CustomObject>

objects/Research_Campaign__c.object
<CustomObject>
    <description>It consists of the campaigns type of mindcrowd like Covid, DBS, Bean game</description>
    <fields>
        <fullName>Usps_Service_Type__c</fullName>
        <description>service which the Mindcrowd team uses TO send their parcels through USPS</description>
        <label>Usps Service Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FIRST CLASS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Weight_in_Ounces__c</fullName>
        <description>It consists of weight of each campaign type</description>
        <label>Weight in Ounces</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>isReturnLabelNeeded__c</fullName>
        <defaultValue>false</defaultValue>
        <description>It tells whether the campaign requires return label or not</description>
        <label>isReturnLabelNeeded</label>
        <type>Checkbox</type>
    </fields>
    <label>Research Campaign</label>
    <nameField>
        <label>Research Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Shipping_Detail__c.object
<CustomObject>
    <description>This Object comprises of all the fields which are related to shipment process.</description>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <type>Address</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field has a mandatory lookup to ResearchCampaign object.</description>
        <label>Campaign</label>
        <referenceTo>Research_Campaign__c</referenceTo>
        <relationshipLabel>Shipping Details</relationshipLabel>
        <relationshipName>Shipping_Details</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Id__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>A mandatory look up field to contact so that every shipment has a contact linked to it.</description>
        <label>Contact Id</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Shipping Details</relationshipLabel>
        <relationshipName>Shipping_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment_Status__c</fullName>
        <description>This field is used to track whether the shipment is created, sent to the participant or received by the Mindcrowd team.</description>
        <label>Shipment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Consented</fullName>
                    <default>true</default>
                    <label>Consented</label>
                </value>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Invalid Address</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Shipping Detail</label>
    <nameField>
        <displayFormat>SD-{00000000}</displayFormat>
        <label>Shipping Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ShipmentLabelTestSravyaTest.cls
@isTest
public class ShipmentLabelTestSravyaTest {

//public class MockUSPSLabelAccessToken {
    public static String requestAccessToken(String grantType, String clientId, String clientSecret, String endPointAccessToken) {
        // Return a mock access token value
        return 'mockAccessTokenValue';
    }
//}
/*    
    @isTest
    static void testIntegrationSettingsInitialization() {
        // Create test Integration_Settings__c record
        Integration_Settings__c settings = new Integration_Settings__c(
            Name = 'Int Settings',
            UserId__c = 'testUser',
            Password__c = 'testPassword',
            Label_Service_Api__c = 'LabelServiceAPI',
            eVSLabelUrl__c = 'https://test.usps.com',
            MindCrowdName__c = 'Test Name',
            MindCrowdFirmName__c = 'Test Firm',
            MindCrowdAddress2__c = '123 Test St',
            MindCrowdCity__c = 'Test City',
            MindCrowdState__c = 'TS',
            //MindCrowdZip5__c = '12345',
            MindCrowdPhone__c = '6023438400',
            Image_Parameters__c = '4X6LABELP',
            grant_type__c = 'client_credentials',
            client_id__c = 'clientId',
            client_secret__c = 'clientSecret',
            AccessToken_url__c = 'https://test.access.token',
            CRID__c = 'testCRID',
            Role_Name_P__c = 'payerRole',
            Role_Name_LO__c = 'labelOwnerRole',
            MID__c = 'testMID',
            Manifest_MID__c = 'testManifestMID',
            Account_Type__c = 'Business',
            Account_Number__c = '123456789',
            Payment_Access_Token_URL__c = 'https://test.payment.token',
            USPS_Label_API_URL__c = 'https://test.usps.label.api',
            Packaging_Type__c = 'Package',
            Processing_Category__c = 'Processing'
        );
        insert settings;

        // Re-initialize the static variable to ensure it's loaded
        Test.startTest();
        ShipmentLabel.integrationsettings = Integration_Settings__c.getAll().get('Int Settings');
        Test.stopTest();
		
        // Validate that the static variables are initialized
        System.assertEquals('testUser', ShipmentLabel.userid);
        System.assertEquals('testPassword', ShipmentLabel.password);
        System.assertEquals('LabelServiceAPI', ShipmentLabel.LabelServiceApi);
        System.assertEquals('https://test.usps.com', ShipmentLabel.UspsUrl);
        
        //Contact Creation
        Contact con= new Contact();
        con.FirstName='Adam';
        con.LastName='Smith';
        con.MailingStreet='PO Box 100';
        con.MailingCity='Washington';
        con.MailingStateCode='DC';
        con.MailingPostalCode='20260';
        insert con;
        System.debug(con);
        
        //Insert Test Research Campaign
        Research_Campaign__c res= new Research_Campaign__c();
        res.Name='Covid';
        res.Weight_in_Ounces__c=3;
        res.isReturnLabelNeeded__c=true;
        res.Usps_Service_Type__c='FIRST CLASS';
        insert res;


    /*
    @isTest
    static void testGetLabelFromUSPS() {
        // Mock the HTTP response
        Test.startTest();
        HttpResponseMock mockResponse = new HttpResponseMock();
        mockResponse.setStatusCode(200);
        mockResponse.setBody('<Response><LabelImage>testImage</LabelImage></Response>');

        HttpMock.register(mockResponse);
        
        String response = ShipmentLabel.getLabelFromUSPS('https://test.usps.com');
        System.assertEquals('<Response><LabelImage>testImage</LabelImage></Response>', response);
        Test.stopTest();
    } */
   		
        /*
        // Create mock Address
        Address testAddress = new Address();
        testAddress.Street = '123 Test St';
        testAddress.City = 'Test City';
        testAddress.StateCode = 'TS';
        testAddress.PostalCode = '12345';  

        // Create mock Research Campaign
        Research_Campaign__c testCampaign = new Research_Campaign__c(
            Weight_in_Ounces__c = 10,
            Usps_Service_Type__c = 'Priority',
            isReturnLabelNeeded__c = false
        );
        insert testCampaign; 
        
		List <Shipping_Detail__c> lstShipping = new List<Shipping_Detail__c>();
        Shipping_Detail__c testshippingbarcode = new Shipping_Detail__c();
        testshippingbarcode.Shipment_Status__c='Consented';
        testshippingbarcode.Campaign__c=res.Id;
        testshippingbarcode.Contact_Id__c=con.Id;
        
        Address ard=new Address();
           // ard.Address__Street__s='';
           // ard.Address__StateCode__s='';
           // ard.Address__CountryCode__s='';
           // ard.Address__City__s='';
           // ard.Address__PostalCode__s='';
           // insert ard;
       // testshippingbarcode.Address__c.add(ard);
		lstShipping.add(testshippingbarcode);
        System.debug(lstShipping);
        insert lstShipping;
        String strid=testshippingbarcode.Id;
        String stridConName= 'james';
		        
        // Prepare test data
        Map<String, Address> idAddressMap = new Map<String, Address> ();
        idAddressMap.put(strid,ard);
        Map<String, Research_Campaign__c> idCampaignMap = new Map<String, Research_Campaign__c>();
        idCampaignMap.put(strid,res);
        Map<String, String> idContactNameMap = new Map<String, String>();
        idContactNameMap.put(strid,stridConName);

        // Call the getLabel method
        Test.setMock(HttpCalloutMock.class, new LabelHttpCallOutMock());
        Test.startTest();
        Boolean result = ShipmentLabel.getLabel(idAddressMap, idCampaignMap, idContactNameMap);
        Test.stopTest();

        System.assert(result);
    } */
}