objects/IpAddressData__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This &quot;IpAddressData&quot; custom setting is used for getting the IPAddress related data from user side.</description>
    <fields>
        <fullName>apiKey__c</fullName>
        <description>This field is used for &quot;api-key&quot; value.</description>
        <label>apiKey</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>url__c</fullName>
        <label>url</label>
        <length>56</length>
        <type>Text</type>
    </fields>
    <label>IpAddressData</label>
</CustomObject>

classes/WebServiceForIpDataTest.cls
// Created By: {Girikon(Sunil)}
// Created On: 08/13/2021
// Apex Class: {WebServiceForIpData)}
@isTest
public with sharing class WebServiceForIpDataTest 
{ 
    @isTest
    public static void getIPDataTest()
    {
        //Create custom setting record
        IpAddressData__c IPD= new IpAddressData__c();
        IPD.Name='userOne';
        IPD.apiKey__c='8289ac328847197b92c5fa681c2168959470f6c0345d44c353e3cccd';
        IPD.url__c='https://api.ipdata.co/';
        insert IPD;
        String ipAddre='103.147.0.90';
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        Map<String, Object> res = WebServiceForIpData.getIPData(ipAddre);
        Test.stopTest();
        //WebServiceForIpData.getIPData(ipAddre);
       // Test.stopTest();
        //System.assertNotEquals(null,result, 'The callout returned a null response.');
    }
}