objects/IpAddressData__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This &quot;IpAddressData&quot; custom setting is used for getting the IPAddress related data from user side.</description>
    <fields>
        <fullName>apiKey__c</fullName>
        <description>This field is used for &quot;api-key&quot; value.</description>
        <label>apiKey</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>url__c</fullName>
        <label>url</label>
        <length>56</length>
        <type>Text</type>
    </fields>
    <label>IpAddressData</label>
</CustomObject>

classes/WebServiceForIpData.cls
public without sharing class WebServiceForIpData 
{
    public static Map<String, Object> getIPData(String ipAddress)
    {
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        IpAddressData__c obj= IpAddressData__c.getValues('userOne'); 
        String apiKey=obj.apiKey__c;
        String url=obj.url__c;
        request.setEndpoint(url+ipAddress+'?api-key='+apiKey);
        request.setMethod('GET');
        System.debug('WebServiceForIpData requesting: '+request);
        HttpResponse response = http.send(request);
        Map<String, Object> addResult=new Map<String, Object>();
        // If the request is successful, parse the JSON response.
        if(response.getStatusCode() == 200) 
        {
            // Deserialize the JSON string into collections of primitive data types.
            Map<String, Object> results = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
            System.debug('WebServiceForIpData HttpResponse:'+results);
            return results;
        }
        else
        {
            String errorMessage= 'ERROR for ipAddress '+ipAddress+' in WebServiceForIpData & HttpResponse is:'+ response;
            UtilityMethods.ErrorReportToEmail(errorMessage);
            return null;
        }        
    } 
}