objects/Participant_Game_Info__c.object
<CustomObject>
    <description>This object is having details of the participant&apos;s game.</description>
    <fields>
        <fullName>Count_Of_No_Of_Correct_Answered__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Count Of No Of Correct Answered</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Count_Of_No_of_Question_Attempted__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Count Of No of Question Attempted</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Count_Of_Number_of_attempts_for_STACKS__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Count Of Number of attempts for STACKS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Count_Of_Total_Reaction_Time__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Count Of Total Reaction Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Count_Of_Total_correct_for_Round_0__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Count Of Total correct for Round 0</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Count_Of_Total_correct_for_Round_1__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Count Of Total correct for Round 1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Count_Of_Total_correct_for_Round_2__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Count Of Total correct for Round 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Count_Of_Total_correct_for_Round_3__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Count Of Total correct for Round 3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Count_Of_Total_correct_for_Round_4__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Count Of_Total correct for Round 4</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Count_Of_Total_correct_for_Round_5__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Count Of Total correct for Round 5</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Count_Of_Total_correct_for_Round_6__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Count Of Total correct for Round 6</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Count_Of_Total_correct_for_Round_7__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Count Of Total correct for Round 7</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_Of_Correct_Answered__c</fullName>
        <description>Count the correct answers were responded by the participant</description>
        <label>No. Of Correct Answered</label>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Is_Correct__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Is_Practice_Question__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>Participant_Game_Response__c.Participant_Game_InfoID__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>No_of_Question_Attempted__c</fullName>
        <description>Count of question from participant responses.</description>
        <label>No. of Question Attempted</label>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Is_Practice_Question__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>Participant_Game_Response__c.Participant_Game_InfoID__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Number_of_attempts_for_STACKS__c</fullName>
        <label>Number of attempts for STACKS</label>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Round__c</field>
            <operation>equals</operation>
            <value>STACKS</value>
        </summaryFilterItems>
        <summaryForeignKey>Participant_Game_Response__c.Participant_Game_InfoID__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Reaction_Time__c</fullName>
        <description>This field represents, the total time taken by the participant.</description>
        <label>Total Reaction Time</label>
        <summarizedField>Participant_Game_Response__c.Reaction_Time_in_ms__c</summarizedField>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Is_Practice_Question__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>Participant_Game_Response__c.Participant_Game_InfoID__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_correct_for_Round_0__c</fullName>
        <label>Total correct for Round 0</label>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Round__c</field>
            <operation>equals</operation>
            <value>0</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Is_Correct__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Participant_Game_Response__c.Participant_Game_InfoID__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_correct_for_Round_10__c</fullName>
        <label>Total correct for Round 10</label>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Is_Correct__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Round__c</field>
            <operation>equals</operation>
            <value>10</value>
        </summaryFilterItems>
        <summaryForeignKey>Participant_Game_Response__c.Participant_Game_InfoID__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_correct_for_Round_11__c</fullName>
        <label>Total correct for Round 11</label>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Round__c</field>
            <operation>equals</operation>
            <value>11</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Is_Correct__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Participant_Game_Response__c.Participant_Game_InfoID__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_correct_for_Round_1__c</fullName>
        <label>Total correct for Round 1</label>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Round__c</field>
            <operation>equals</operation>
            <value>1</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Is_Correct__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Participant_Game_Response__c.Participant_Game_InfoID__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_correct_for_Round_2__c</fullName>
        <label>Total correct for Round 2</label>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Round__c</field>
            <operation>equals</operation>
            <value>2</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Is_Correct__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Participant_Game_Response__c.Participant_Game_InfoID__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_correct_for_Round_3__c</fullName>
        <label>Total correct for Round 3</label>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Round__c</field>
            <operation>equals</operation>
            <value>3</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Is_Correct__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Participant_Game_Response__c.Participant_Game_InfoID__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_correct_for_Round_4__c</fullName>
        <description>This field is having the total correct responses for the second practice round.</description>
        <label>Total correct for Round 4</label>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Round__c</field>
            <operation>equals</operation>
            <value>4</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Is_Correct__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Participant_Game_Response__c.Participant_Game_InfoID__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_correct_for_Round_5__c</fullName>
        <description>This field is having the total correct responses for the third practice round.</description>
        <label>Total correct for Round 5</label>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Round__c</field>
            <operation>equals</operation>
            <value>5</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Is_Correct__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Participant_Game_Response__c.Participant_Game_InfoID__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_correct_for_Round_6__c</fullName>
        <label>Total correct for Round 6</label>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Is_Correct__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Round__c</field>
            <operation>equals</operation>
            <value>6</value>
        </summaryFilterItems>
        <summaryForeignKey>Participant_Game_Response__c.Participant_Game_InfoID__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_correct_for_Round_7__c</fullName>
        <description>This field is created mainly for the FACENAME game, It is having the correct answers for participants&apos; practice.</description>
        <label>Total correct for Round 7</label>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Is_Correct__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Round__c</field>
            <operation>equals</operation>
            <value>7</value>
        </summaryFilterItems>
        <summaryForeignKey>Participant_Game_Response__c.Participant_Game_InfoID__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_correct_for_Round_8__c</fullName>
        <label>Total correct for Round 8</label>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Round__c</field>
            <operation>equals</operation>
            <value>8</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Is_Correct__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Participant_Game_Response__c.Participant_Game_InfoID__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_correct_for_Round_9__c</fullName>
        <label>Total correct for Round 9</label>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Round__c</field>
            <operation>equals</operation>
            <value>9</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Participant_Game_Response__c.Is_Correct__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Participant_Game_Response__c.Participant_Game_InfoID__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Participant Game Info</label>
    <nameField>
        <displayFormat>PGI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Game Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BatchUpdatePGIRecords.cls
public class BatchUpdatePGIRecords implements Database.Batchable<sObject>,Schedulable {
    private Integer startMin;
    private Integer endmin;
    public BatchUpdatePGIRecords(Integer startMin, Integer endmin){
        this.startMin = startMin;
        this.endmin = endmin;
    }
    public void execute(SchedulableContext sc) {
        BatchUpdatePGIRecords updPGI = new BatchUpdatePGIRecords(startMin,endmin);
        Database.executeBatch(updPGI,2000);
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC) {
        DateTime startTime = Datetime.now().addMinutes(startMin);
        DateTime endTime = Datetime.now().addMinutes(endmin);
        return Database.getQueryLocator([
            SELECT Id, No_Of_Correct_Answered__c,No_of_Question_Attempted__c,Number_of_attempts_for_STACKS__c,
            Total_Reaction_Time__c,Total_correct_for_Round_0__c,Total_correct_for_Round_1__c,Total_correct_for_Round_2__c,
            Total_correct_for_Round_3__c,Total_correct_for_Round_4__c,Total_correct_for_Round_5__c,Total_correct_for_Round_6__c,
            Total_correct_for_Round_7__c,Total_correct_for_Round_8__c,Total_correct_for_Round_9__c,Total_correct_for_Round_10__c,
            Total_correct_for_Round_11__c,Count_Of_No_Of_Correct_Answered__c,Count_Of_No_of_Question_Attempted__c,
            Count_Of_Number_of_attempts_for_STACKS__c,Count_Of_Total_Reaction_Time__c,Count_Of_Total_correct_for_Round_0__c,
            Count_Of_Total_correct_for_Round_1__c,Count_Of_Total_correct_for_Round_2__c,Count_Of_Total_correct_for_Round_3__c,
            Count_Of_Total_correct_for_Round_4__c,Count_Of_Total_correct_for_Round_5__c,Count_Of_Total_correct_for_Round_6__c,
            Count_Of_Total_correct_for_Round_7__c,Count_Of_Total_correct_for_Round_8__c,Count_Of_Total_correct_for_Round_9__c,
            Count_Of_Total_correct_for_Round_10__c,Count_Of_Total_correct_for_Round_11__c,Version__c,Game_Name__r.Version__c
            FROM Participant_Game_Info__c            
            WHERE Version__c = null 
            AND CreatedDate >=: startTime
            AND CreatedDate <=: endTime
        ]);
    }
    
    public void execute(Database.BatchableContext BC, List<Participant_Game_Info__c> scope) {
        system.debug(scope);
        for (Participant_Game_Info__c obj : scope) {
                obj.Count_Of_No_Of_Correct_Answered__c = obj.No_Of_Correct_Answered__c;
                obj.Count_Of_No_of_Question_Attempted__c = obj.No_of_Question_Attempted__c;
                obj.Count_Of_Number_of_attempts_for_STACKS__c = obj.Number_of_attempts_for_STACKS__c;
                obj.Count_Of_Total_Reaction_Time__c = obj.Total_Reaction_Time__c;
                obj.Count_Of_Total_correct_for_Round_0__c = obj.Total_correct_for_Round_0__c;
                obj.Count_Of_Total_correct_for_Round_1__c = obj.Total_correct_for_Round_1__c;
                obj.Count_Of_Total_correct_for_Round_2__c = obj.Total_correct_for_Round_2__c;
                obj.Count_Of_Total_correct_for_Round_3__c = obj.Total_correct_for_Round_3__c;
                obj.Count_Of_Total_correct_for_Round_4__c = obj.Total_correct_for_Round_4__c;
                obj.Count_Of_Total_correct_for_Round_5__c = obj.Total_correct_for_Round_5__c;
                obj.Count_Of_Total_correct_for_Round_6__c = obj.Total_correct_for_Round_6__c;
                obj.Count_Of_Total_correct_for_Round_7__c = obj.Total_correct_for_Round_7__c;
                obj.Count_Of_Total_correct_for_Round_8__c = obj.Total_correct_for_Round_8__c;
                obj.Count_Of_Total_correct_for_Round_9__c = obj.Total_correct_for_Round_9__c;
                obj.Count_Of_Total_correct_for_Round_10__c = obj.Total_correct_for_Round_10__c;
                obj.Count_Of_Total_correct_for_Round_11__c = obj.Total_correct_for_Round_11__c;
            	obj.Version__c = obj.Game_Name__r.Version__c;
        	}
       Database.update(scope,false);
    }
    
    public void finish(Database.BatchableContext BC) {
        BatchUpdatePGRRecords updPGR = new BatchUpdatePGRRecords(startMin,endmin);
        Database.executeBatch(updPGR,2000);
    }
}