objects/Participant_Game_Info__c.object
<CustomObject>
    <description>This object is having details of the participant&apos;s game.</description>
    <fields>
        <fullName>Game_Play_Status__c</fullName>
        <label>Game Play Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not-Completed</fullName>
                    <default>true</default>
                    <label>Not-Completed</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Participant Game Info</label>
    <nameField>
        <displayFormat>PGI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Game Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Participant_Game_Response__c.object
<CustomObject>
    <description>It is having the Information about participant response.</description>
    <fields>
        <fullName>Participant_Game_InfoID__c</fullName>
        <description>Lookup to Participant Game Info, saving Participant Game InfoID, will show at front-end.</description>
        <label>Participant Game InfoID</label>
        <referenceTo>Participant_Game_Info__c</referenceTo>
        <relationshipLabel>Participant Game Responses</relationshipLabel>
        <relationshipName>Participant_Game_Responses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Participant Game Response</label>
    <nameField>
        <displayFormat>PGR-{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Game Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BatchUpdatePGIRecordsTest.cls
@isTest
private class BatchUpdatePGIRecordsTest {
    
    static testMethod void testBatchUpdatePGIRecords() {
        // Create test data
        List<Participant_Game_Info__c> testRecords = new List<Participant_Game_Info__c>();
        List<Participant_Game_Response__c> testPGRRecords = new List<Participant_Game_Response__c>();        
        for(Integer i=0; i<10; i++) {
            testRecords.add(new Participant_Game_Info__c(Game_Play_Status__c = 'Completed'));
        }
        insert testRecords;
        for(Participant_Game_Info__c pgi: [select createddate, id, Version__c from Participant_Game_Info__c]) {
            Test.setCreatedDate(pgi.Id,DateTime.newInstance(2024,03,13));
            testPGRRecords.add(new Participant_Game_Response__c(Participant_Game_InfoID__c = pgi.Id, Version__c=null));
        }
        insert testPGRRecords;
        for(Participant_Game_Response__c pgr: [select createddate, id from Participant_Game_Response__c]) {
            Test.setCreatedDate(pgr.Id, DateTime.newInstance(2024,03,13));           
        }       

        Test.startTest();
        String jobId = System.schedule('Test Batch Job', 
                                        '0 0 23 * * ?', 
                                        new BatchUpdatePGIRecords(-1440,0));
        Test.stopTest();
        System.assertEquals(1, [SELECT count() FROM CronTrigger WHERE Id = :jobId]);
    }
}