objects/Participant_Game_Info__c.object
<CustomObject>
    <description>This object is having details of the participant&apos;s game.</description>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to contact, saving contact id, will show contact name at front-end.</description>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Participant Game Infos</relationshipLabel>
        <relationshipName>Participant_Game_Infos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IP_Address__c</fullName>
        <label>IP Address</label>
        <length>56</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IP_Data__c</fullName>
        <label>IP Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_Zone_Offset__c</fullName>
        <description>time(Allows users to enter a local time.)</description>
        <label>Time Zone Offset</label>
        <length>56</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Participant Game Info</label>
    <nameField>
        <displayFormat>PGI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Game Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BatchUpdatePGI.cls
// Created By: {Girikon(Sunil Kumar)}
// Updated On: 08/09/2022
// Description/Purpose: [TM-185]-It will be used for updating PGI records where IP address is avaible.
// Test Class: {BatchUpdatePGI_Test} {100%}

global class BatchUpdatePGI implements Database.Batchable<SObject>,Database.AllowsCallouts,Database.Stateful
{
    global Database.QueryLocator start(Database.BatchableContext bc)
    {
             
     return Database.getQueryLocator('SELECT Id, Contact_Name__c, IP_Address__c, Geolocation__Longitude__s, Geolocation__Latitude__s,Zip_Code__c,Region__c,Country__c,City__c, Time_Zone_Offset__c,createdDate, IP_Data__c FROM Participant_Game_Info__c where createdDate>=2022-06-01T23:19:06.000+0000 and Geolocation__Latitude__s=null and IP_Address__c!=null order by createdDate desc');
        
    }
    global void execute(Database.BatchableContext bc, List<Participant_Game_Info__c > scope)
     {   
        List <Participant_Game_Info__c> toUpdatePGI = new List <Participant_Game_Info__c> ();
         System.debug('batchable context--'+bc);
         try{
            for(Participant_Game_Info__c pgi:scope){
                Participant_Game_Info__c pgiObj=new Participant_Game_Info__c();
                String ipAddress=pgi.IP_Address__c;
                system.debug('ipAddress==>'+ipAddress);
                Map<String, Object> results=WebServiceForIpData.getIPData(ipAddress);
      
                if(results !=null)
                 {
                    System.debug('longitude--'+decimal.valueOf(JSON.serialize(results.get('longitude'))));
                     Map<String, Object> lmap =(Map<String, Object>) results.get('time_zone');
                     pgiObj.Time_Zone_Offset__c=(String)lmap.get('offset');
                     pgiObj.City__c=string.valueOf(JSON.serialize(results.get('city'))).replace('"','');
                     pgiObj.Country__c=string.valueOf(JSON.serialize(results.get('country_name'))).replace('"','');
                     pgiObj.Region__c=string.valueOf(JSON.serialize(results.get('region'))).replace('"','');
                     pgiObj.IP_Data__c=JSON.serialize(results);
                     pgiObj.Zip_Code__c=string.valueOf(JSON.serialize(results.get('postal'))).replace('"','');
                     pgiObj.Geolocation__Longitude__s= decimal.valueOf(JSON.serialize(results.get('longitude')));
                     pgiObj.ID= pgi.id;
                     pgiObj.Geolocation__Latitude__s= decimal.valueOf(JSON.serialize(results.get('latitude')));
                 }
                toUpdatePGI.Add(pgiObj);   
            }
            if(toUpdatePGI.size()>0){
                update toUpdatePGI;
            }      
         }
         catch(Exception ex){
                  System.debug('exception here:'+ex);
         }
        
        
     }
     global void finish(Database.BatchableContext BC)
     {
     }  
}