objects/Participant_Game_Info__c.object
<CustomObject>
    <description>This object is having details of the participant&apos;s game.</description>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Participant Game Info</label>
    <nameField>
        <displayFormat>PGI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Game Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Participant_Game_Response__c.object
<CustomObject>
    <description>It is having the Information about participant response.</description>
    <fields>
        <fullName>Participant_Game_InfoID__c</fullName>
        <description>Lookup to Participant Game Info, saving Participant Game InfoID, will show at front-end.</description>
        <label>Participant Game InfoID</label>
        <referenceTo>Participant_Game_Info__c</referenceTo>
        <relationshipLabel>Participant Game Responses</relationshipLabel>
        <relationshipName>Participant_Game_Responses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Participant Game Response</label>
    <nameField>
        <displayFormat>PGR-{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Game Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BatchUpdatePGRRecords.cls
public class BatchUpdatePGRRecords implements Database.Batchable<sObject> {
    private Integer startMin;
    private Integer endmin;
    public BatchUpdatePGRRecords(Integer startMin, Integer endmin){
        this.startMin = startMin;
        this.endmin = endmin;
    }
    public Database.QueryLocator start(Database.BatchableContext BC) {
        DateTime startTime = Datetime.now().addMinutes(startMin);
        DateTime endTime = Datetime.now().addMinutes(endmin);
        return Database.getQueryLocator([
            SELECT Id, Version__c,Participant_Game_InfoID__r.Version__c
            FROM Participant_Game_Response__c
            WHERE CreatedDate >=: startTime
            AND CreatedDate <=: endTime
            AND Version__c = null
        ]);
    }
    
    public void execute(Database.BatchableContext BC, List<Participant_Game_Response__c> scope) {
        for (Participant_Game_Response__c obj : scope) {
                obj.Version__c = obj.Participant_Game_InfoID__r.Version__c;
        	}
        Database.update(scope,false);
    }
    
    public void finish(Database.BatchableContext BC) {
    }
}