objects/Research_Campaign__c.object
<CustomObject>
    <description>It consists of the campaigns type of mindcrowd like Covid, DBS, Bean game</description>
    <label>Research Campaign</label>
    <nameField>
        <label>Research Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Shipping_Detail__c.object
<CustomObject>
    <description>This Object comprises of all the fields which are related to shipment process.</description>
    <fields>
        <fullName>Barcode__c</fullName>
        <formula>IF(DATEVALUE(CreatedDate) &lt; DATEVALUE( &quot;2022-09-01&quot; ), &apos;SM&apos;+ MID( Id ,10,2)+ &apos;BA&apos;+RIGHT(Id,4)+&apos;CD&apos;,   Name )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Barcode</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field has a mandatory lookup to ResearchCampaign object.</description>
        <label>Campaign</label>
        <referenceTo>Research_Campaign__c</referenceTo>
        <relationshipLabel>Shipping Details</relationshipLabel>
        <relationshipName>Shipping_Details</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Return_Status_Code__c</fullName>
        <description>This field will contain the Event code returned by USPS Track API. it will hold the value for the packet which is returned by participant.</description>
        <label>Return Status Code</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Return_Status__c</fullName>
        <description>This field will contain the StatusCategory returned by USPS Track API. This is created to track return status of the packet.</description>
        <label>Return Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Return_Track_Summary__c</fullName>
        <description>This field will hold the return tracking summary provided by USPS track API.</description>
        <label>Return Track Summary</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Return_TrackingId__c</fullName>
        <description>This Id consists of returning track id</description>
        <label>Return TrackingId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipment_Sent_Date__c</fullName>
        <description>This field defines the date on which shipment was sent to participant.</description>
        <label>Shipment Sent Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Shipment_Status__c</fullName>
        <description>This field is used to track whether the shipment is created, sent to the participant or received by the Mindcrowd team.</description>
        <label>Shipment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Consented</fullName>
                    <default>true</default>
                    <label>Consented</label>
                </value>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Invalid Address</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Track_Summary__c</fullName>
        <description>This field will store the StatusSummary returned by USPS Tracking API. It will tell us where the packet is located along with other info like date and time in a single line.</description>
        <label>Track Summary</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Tracking_Id__c</fullName>
        <description>This field comprises of the tracking number provided by USPS for tracking the shipments</description>
        <label>Tracking Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>USPS_Status_Code__c</fullName>
        <description>This field will contain the EventCode provided by USPS Tracking API.</description>
        <label>USPS Status Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>USPS_Status__c</fullName>
        <description>This field will contain the StatusCategory returned by USPS Track API.</description>
        <label>USPS Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Shipping Detail</label>
    <nameField>
        <displayFormat>SD-{00000000}</displayFormat>
        <label>Shipping Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BatchTrackShipmentHandler.cls
public class BatchTrackShipmentHandler {
    
    public static Shipping_Detail__c UpdateTrackingDetails(String trackingId,String returnTrackingId,String uspsstatus,
                                                           String uspsstatuscode,String tracksummary,String recordId) 
        
    {
        Shipping_Detail__c shipDetails=new Shipping_Detail__c();
        system.debug('tracking id  is----'+trackingId);
        List<Shipping_Detail__c> shipmenttoTrack=  [SELECT Id,Barcode__c,Shipment_Sent_Date__c,
                                                    Shipment_Status__c,Return_TrackingId__c,Campaign__r.Name,
                                                    USPS_Status_Code__c,Return_Status__c,
                                                    Return_Status_Code__c,Return_Track_Summary__c,
                                                    Tracking_Id__c,Track_Summary__c
                                                    FROM Shipping_Detail__c
                                                    where Id =:recordId];
        
        for(Shipping_Detail__c sdTrack:shipmenttoTrack){
            if(sdTrack.Shipment_Status__c=='Sent' ){
                sdTrack.USPS_Status__c = uspsstatus;
                System.debug('apex value of status--'+uspsstatus);
                sdTrack.USPS_Status_Code__c = uspsstatuscode;
                sdTrack.Track_Summary__c = tracksummary;
                if(sdTrack.USPS_Status_Code__c =='01'){
                    sdTrack.Shipment_Status__c='Delivered';
                    sdTrack.USPS_Status_Code__c = uspsstatuscode; 
                    System.debug(' apex value of status--'+uspsstatuscode);
                    sdTrack.Track_Summary__c = tracksummary;
                    System.debug(' apex value of summary--'+tracksummary);
                }
                System.debug('value of summary--'+tracksummary);
                System.debug('I am in track shipment--');
                
            }
            else if (sdTrack.USPS_Status_Code__c!='01') {
                sdTrack.Track_Summary__c = tracksummary;
                
            }
            else if(sdTrack.Shipment_Status__c=='Delivered')
            {
                sdTrack.Return_Status__c = uspsstatus;
                sdTrack.Return_Status_Code__c = uspsstatuscode; 
                sdTrack.Return_Track_Summary__c = tracksummary;
                System.debug('value of return summary--'+tracksummary);
            }
            shipDetails=sdTrack;
            }
            
        
        
        /*if(!shipmenttoTrack.isEmpty())
        {
            System.debug('--in if statement--'+shipmenttoTrack[0].Shipment_Status__c);
            if(shipmenttoTrack[0].Shipment_Status__c=='Sent' )
            {
                shipmenttoTrack[0].USPS_Status__c = uspsstatus;
                System.debug('apex value of status--'+uspsstatus);
                shipmenttoTrack[0].USPS_Status_Code__c = uspsstatuscode; 
                shipmenttoTrack[0].Track_Summary__c = tracksummary;
                if(shipmenttoTrack[0].USPS_Status_Code__c=='01')
                {
                    shipmenttoTrack[0].Shipment_Status__c='Delivered';
                    shipmenttoTrack[0].USPS_Status_Code__c = uspsstatuscode; 
                    System.debug(' apex value of status--'+uspsstatuscode);
                    shipmenttoTrack[0].Track_Summary__c = tracksummary;
                    System.debug(' apex value of summary--'+tracksummary);
                }
                System.debug('value of summary--'+tracksummary);
                System.debug('I am in track shipment--');
                
            }
            else if (shipmenttoTrack[0].USPS_Status_Code__c!='01') {
                shipmenttoTrack[0].Track_Summary__c = tracksummary;
                
            }
            else if(shipmenttoTrack[0].Shipment_Status__c=='Delivered')
            {
                shipmenttoTrack[0].Return_Status__c = uspsstatus;
                shipmenttoTrack[0].Return_Status_Code__c = uspsstatuscode; 
                shipmenttoTrack[0].Return_Track_Summary__c = tracksummary;
                System.debug('value of return summary--'+tracksummary);
            }
            update shipmenttoTrack;
            System.debug('Tracking details updated');
            //return true;
        }*/
        //return true;
        return shipDetails;
    }
}