objects/Research_Campaign__c.object
<CustomObject>
    <description>It consists of the campaigns type of mindcrowd like Covid, DBS, Bean game</description>
    <label>Research Campaign</label>
    <nameField>
        <label>Research Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Shipping_Detail__c.object
<CustomObject>
    <description>This Object comprises of all the fields which are related to shipment process.</description>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field has a mandatory lookup to ResearchCampaign object.</description>
        <label>Campaign</label>
        <referenceTo>Research_Campaign__c</referenceTo>
        <relationshipLabel>Shipping Details</relationshipLabel>
        <relationshipName>Shipping_Details</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Id__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>A mandatory look up field to contact so that every shipment has a contact linked to it.</description>
        <label>Contact Id</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Shipping Details</relationshipLabel>
        <relationshipName>Shipping_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Shipping Detail</label>
    <nameField>
        <displayFormat>SD-{00000000}</displayFormat>
        <label>Shipping Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PrintLabelControllerTest.cls
@isTest
public with sharing class PrintLabelControllerTest 
{
    public PrintLabelControllerTest() 
    {

    }
    @isTest
    public static void doSomethingTest()
    {
        Contact c= new Contact();
        c.FirstName='MindCrowd';
        c.LastName='Research';
        insert c;
        Research_Campaign__c rcampaign= new Research_Campaign__c();
        rcampaign.Name='Covid';
        insert rcampaign;
        List <Shipping_Detail__c> printlabeltestlist = new List<Shipping_Detail__c>();

        Shipping_Detail__c testshipping = new Shipping_Detail__c();
        testshipping.Campaign__c= rcampaign.Id;
        testshipping.Contact_Id__c= c.Id;
        printlabeltestlist.add(testshipping);
        insert printlabeltestlist;
       
        Test.startTest();
        Test.setCurrentPage(Page.PrintLabelVF);
        ApexPages.StandardSetController stdSetController = new ApexPages.StandardSetController(printlabeltestlist);
        stdSetController.setSelected(printlabeltestlist);
        PrintLabelController ext = new PrintLabelController(stdSetController);        
        Test.stopTest();
    }
}