objects/Research_Campaign__c.object
<CustomObject>
    <description>It consists of the campaigns type of mindcrowd like Covid, DBS, Bean game</description>
    <label>Research Campaign</label>
    <nameField>
        <label>Research Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Research Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Shipping_Detail__c.object
<CustomObject>
    <description>This Object comprises of all the fields which are related to shipment process.</description>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field has a mandatory lookup to ResearchCampaign object.</description>
        <label>Campaign</label>
        <referenceTo>Research_Campaign__c</referenceTo>
        <relationshipLabel>Shipping Details</relationshipLabel>
        <relationshipName>Shipping_Details</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Id__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>A mandatory look up field to contact so that every shipment has a contact linked to it.</description>
        <label>Contact Id</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Shipping Details</relationshipLabel>
        <relationshipName>Shipping_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment_Status__c</fullName>
        <description>This field is used to track whether the shipment is created, sent to the participant or received by the Mindcrowd team.</description>
        <label>Shipment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Consented</fullName>
                    <default>true</default>
                    <label>Consented</label>
                </value>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Invalid Address</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Shipping Detail</label>
    <nameField>
        <displayFormat>SD-{00000000}</displayFormat>
        <label>Shipping Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SendShipmentVFTest.cls
@isTest
public with sharing class SendShipmentVFTest {
    public SendShipmentVFTest() {

    }
    @isTest  
    public static void sendShipmenttestMethod1() 
    {
        Contact con= new Contact();
        con.FirstName='Shweta';
        con.LastName='khunteta';
        insert con;
        System.debug(con);
        Research_Campaign__c res= new Research_Campaign__c();
        res.Name='Covid';
        insert res;
        List <Shipping_Detail__c> lstShipping = new List<Shipping_Detail__c>();

        Shipping_Detail__c testshippingbarcode = new Shipping_Detail__c();
        testshippingbarcode.Shipment_Status__c='Consented' ;
        testshippingbarcode.Contact_Id__c=con.Id;
        testshippingbarcode.Campaign__c=res.Id;
        lstShipping.add(testshippingbarcode);
        System.debug(lstShipping);
       
        insert  lstShipping;

        Test.startTest();
        Test.setCurrentPage(Page.SendandReceiveVF);
        ApexPages.StandardSetController stdSetController = new ApexPages.StandardSetController(lstShipping);
        stdSetController.setSelected(lstShipping);
        SendShipmentVF ext = new SendShipmentVF(stdSetController);
        ext.sendshippingId();
        Test.stopTest();
    }
   
}