objects/Shipping_Detail__c.object
<CustomObject>
    <description>This Object comprises of all the fields which are related to shipment process.</description>
    <fields>
        <fullName>Barcode__c</fullName>
        <formula>IF(DATEVALUE(CreatedDate) &lt; DATEVALUE( &quot;2022-09-01&quot; ), &apos;SM&apos;+ MID( Id ,10,2)+ &apos;BA&apos;+RIGHT(Id,4)+&apos;CD&apos;,   Name )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Barcode</label>
        <type>Text</type>
    </fields>
    <label>Shipping Detail</label>
    <nameField>
        <displayFormat>SD-{00000000}</displayFormat>
        <label>Shipping Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PassBarCodeIdToVF.cls
// Created By: {Girikon(Shweta Khunteta)}
// Created On: 14/07/2021
// Description/Purpose: Why and where it is used [TM-22]-It was created to  send the selectedShipping ids by
//                      clicking on GenerateBarcode button and pass to barCodeGenerator (LWC Component) 
// 
// Methods: {}
// Test Class: {92%} {Code Coverage:}
public with sharing class PassBarCodeIdToVF 
{
    public List<String> barCodes{get;set;}
    public String barCode{get;set;}
    public PassBarCodeIdToVF(ApexPages.StandardSetController cntlr) 
    {
        try{
            
            List<Shipping_Detail__c> selShipLst = cntlr.getSelected(); //get selected records from shippingdetail list view
             System.debug('--selected shipping id are--'+selShipLst);

             selShipLst = [select  Barcode__c from Shipping_Detail__c
                            where id = :selShipLst];
                barCodes= new List<String>();
                barCode='';
                for (Shipping_Detail__c shipDetailObj : selShipLst) {
                        barCodes.add(shipDetailObj.Barcode__c);
                       // barCode+=shipDetailObj.Barcode__c;
                        
                 }
                 System.debug('barcodes selected are--'+barCodes);
                
                 barCode = JSON.serialize(barCodes);
                //  System.debug('barcode selected inserialized form--'+barCode);
               
             }
             catch(Exception e){
                 System.debug('Exception ->'+e.getMessage()+' on line number-->'+e.getLineNumber());
             }
        } 

    }