objects/Shipping_Detail__c.object
<CustomObject>
    <description>This Object comprises of all the fields which are related to shipment process.</description>
    <fields>
        <fullName>Barcode__c</fullName>
        <formula>IF(DATEVALUE(CreatedDate) &lt; DATEVALUE( &quot;2022-09-01&quot; ), &apos;SM&apos;+ MID( Id ,10,2)+ &apos;BA&apos;+RIGHT(Id,4)+&apos;CD&apos;,   Name )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Barcode</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QR_Code__c</fullName>
        <formula>IF( Campaign__r.Name == &apos;Bean Game&apos;,(IF( ISPICKVAL(Contact_Id__r.Language__c,&apos;English&apos;), $Label.Community_Url + &quot;/s/add-beangame?participantcode=&quot; +  Contact_Id__r.ParticipantCode__c, $Label.Community_Url_Spanish + &quot;/s/adic/juegofrijol?participantcode=&quot; +  Contact_Id__r.ParticipantCode__c)),&apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>QR Code</label>
        <type>Text</type>
    </fields>
    <label>Shipping Detail</label>
    <nameField>
        <displayFormat>SD-{00000000}</displayFormat>
        <label>Shipping Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PassQRCodeToVF.cls
// Created By: {Girikon(Sunil)}
// Created On: 20/10/2021
// Description/Purpose: 
public with sharing class PassQRCodeToVF
{
    public List<String> QRCodes{get;set;}
    public String QRCode{get;set;}
    public List<String> barCodes{get;set;}
    public String barCode{get;set;}
    public PassQRCodeToVF(ApexPages.StandardSetController cntlr) 
    {
        try{
            
            List<Shipping_Detail__c> selShipLst = cntlr.getSelected(); 
             System.debug('--selected shipping id are--'+selShipLst);

                selShipLst = [select  QR_Code__c,Barcode__c from Shipping_Detail__c where id = :selShipLst And QR_Code__c!=null];
                QRCodes= new List<String>();
                QRCode='';
                barCodes= new List<String>();
                barCode='';
                for (Shipping_Detail__c shipDetailObj : selShipLst) {
                    QRCodes.add(shipDetailObj.QR_Code__c);
                    QRCodes.add(shipDetailObj.Barcode__c);                
                 }
                 //System.debug('qrcodes selected are--'+QRCodes);
                 //System.debug('barcodes selected are--'+barCodes);
                 QRCode = JSON.serialize(QRCodes);
             }
             catch(Exception e){
                 System.debug('Exception ->'+e.getMessage()+' on line number-->'+e.getLineNumber());
             }
        } 

    }