objects/Shipping_Detail__c.object
<CustomObject>
    <description>This Object comprises of all the fields which are related to shipment process.</description>
    <fields>
        <fullName>Barcode__c</fullName>
        <formula>IF(DATEVALUE(CreatedDate) &lt; DATEVALUE( &quot;2022-09-01&quot; ), &apos;SM&apos;+ MID( Id ,10,2)+ &apos;BA&apos;+RIGHT(Id,4)+&apos;CD&apos;,   Name )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Barcode</label>
        <type>Text</type>
    </fields>
    <label>Shipping Detail</label>
    <nameField>
        <displayFormat>SD-{00000000}</displayFormat>
        <label>Shipping Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SendShipmentVF.cls
// Created By: {Girikon(Shweta Khunteta)}
// Created On: 16/08/2021
// Description/Purpose: Why and where it is used [TM-73]-It was created to  select multiple Shipping ids  and send to the 
//ShippingDetailsController to update their shipment status
// 
// Methods: {sendshippingId}
// Test Class: {SendShipmentVFTest} {93%}
public with sharing class SendShipmentVF {
    public List<Shipping_Detail__c> selShipLst;
    public List<String> barCodes{get;set;}
    public String barCode{get;set;}
    public SendShipmentVF(ApexPages.StandardSetController cntlr) 
    {
        try{
            
            selShipLst = cntlr.getSelected(); //get selected records from shippingdetail list view
             System.debug('--selected shipping id are--'+selShipLst);
             selShipLst = [select  Barcode__c from Shipping_Detail__c
                            where id = :selShipLst];
             System.DEBUG('SELECTED SHIPPING ID WITH BARCODES TO SEND---'+selShipLst);               
            barCodes= new List<String>();
            barCode='';
            for (Shipping_Detail__c shipDetailObj : selShipLst)
            {
                barCodes.add(shipDetailObj.Barcode__c);
            }
            System.debug('barcodes selected are--'+barCodes);
            barCode = JSON.serialize(barCodes);
            }
        catch(Exception e)
            {
                System.debug('Exception ->'+e.getMessage()+' on line number-->'+e.getLineNumber());
            }
    } 
public PageReference sendshippingId()
    {
        ShippingDetailsController.updateShipmentStatusToSent(barCodes); 
        return null;  
    }

}