objects/Test_Result__c.object
<CustomObject>
    <fields>
        <fullName>Data_Category__c</fullName>
        <label>Data Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ready to send</fullName>
                </value>
                <value>
                    <fullName>kit sent</fullName>
                </value>
                <value>
                    <fullName>Kits not received in 30 days</fullName>
                </value>
                <value>
                    <fullName>subscription</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Kits Delivered</fullName>
                </value>
                <value>
                    <fullName>Kits returned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Data_Name__c</fullName>
        <label>Data Name</label>
        <length>99</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Data_Value__c</fullName>
        <label>Data Value</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Test Result</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Test results Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestResultsControllerTest.cls
@isTest
public class TestResultsControllerTest {
@isTest
    private static void getChartMapTest(){
        Test_Result__c objDashboard= new Test_Result__c();
        objDashboard.Data_Value__c = 20;
        objDashboard.Order__c =2;
        objDashboard.Data_Category__c = 'Ready to send';
        objDashboard.Data_Name__c = 'Test';
        insert objDashboard;
         Test_Result__c objDashboard1= new Test_Result__c();
        objDashboard1.Data_Value__c = 20;
        objDashboard1.Order__c =2;
        objDashboard1.Data_Category__c = 'subscription';
        objDashboard1.Data_Name__c = 'Test';
        insert objDashboard1;
        
        
        
        
        TestResultsController.getResultsDashboardData();
    }
}